// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by objectiveai-cli-schema-codegen from objectiveai-json-schema/.

use clap::Subcommand;

#[derive(Subcommand)]
#[command(rename_all = "verbatim")]
pub enum GetCommand {
    #[command(name = "get")]
    Get,
}

#[derive(Subcommand)]
#[command(rename_all = "verbatim")]
pub enum Commands {
    #[command(name = "list")]
    List,
    AnyOfInputSchema {
        #[command(subcommand)]
        command: GetCommand,
    },
    ArrayInputSchema {
        #[command(subcommand)]
        command: GetCommand,
    },
    ArrayInputSchemaType {
        #[command(subcommand)]
        command: GetCommand,
    },
    AudioInputSchema {
        #[command(subcommand)]
        command: GetCommand,
    },
    AudioInputSchemaType {
        #[command(subcommand)]
        command: GetCommand,
    },
    BooleanInputSchema {
        #[command(subcommand)]
        command: GetCommand,
    },
    BooleanInputSchemaType {
        #[command(subcommand)]
        command: GetCommand,
    },
    Expression {
        #[command(subcommand)]
        command: GetCommand,
    },
    FileInputSchema {
        #[command(subcommand)]
        command: GetCommand,
    },
    FileInputSchemaType {
        #[command(subcommand)]
        command: GetCommand,
    },
    ImageInputSchema {
        #[command(subcommand)]
        command: GetCommand,
    },
    ImageInputSchemaType {
        #[command(subcommand)]
        command: GetCommand,
    },
    InputSchema {
        #[command(subcommand)]
        command: GetCommand,
    },
    InputValue {
        #[command(subcommand)]
        command: GetCommand,
    },
    InputValueExpression {
        #[command(subcommand)]
        command: GetCommand,
    },
    IntegerInputSchema {
        #[command(subcommand)]
        command: GetCommand,
    },
    IntegerInputSchemaType {
        #[command(subcommand)]
        command: GetCommand,
    },
    NumberInputSchema {
        #[command(subcommand)]
        command: GetCommand,
    },
    NumberInputSchemaType {
        #[command(subcommand)]
        command: GetCommand,
    },
    ObjectInputSchema {
        #[command(subcommand)]
        command: GetCommand,
    },
    ObjectInputSchemaType {
        #[command(subcommand)]
        command: GetCommand,
    },
    Params {
        #[command(subcommand)]
        command: GetCommand,
    },
    Special {
        #[command(subcommand)]
        command: GetCommand,
    },
    StringInputSchema {
        #[command(subcommand)]
        command: GetCommand,
    },
    StringInputSchemaType {
        #[command(subcommand)]
        command: GetCommand,
    },
    TaskOutput {
        #[command(subcommand)]
        command: GetCommand,
    },
    VideoInputSchema {
        #[command(subcommand)]
        command: GetCommand,
    },
    VideoInputSchemaType {
        #[command(subcommand)]
        command: GetCommand,
    },
}

impl Commands {
    pub fn handle(self) -> Result<crate::Output, crate::error::Error> {
        match self {
            Commands::List => Ok(crate::Output::Schema("[\"AnyOfInputSchema\",\"ArrayInputSchema\",\"ArrayInputSchemaType\",\"AudioInputSchema\",\"AudioInputSchemaType\",\"BooleanInputSchema\",\"BooleanInputSchemaType\",\"Expression\",\"FileInputSchema\",\"FileInputSchemaType\",\"ImageInputSchema\",\"ImageInputSchemaType\",\"InputSchema\",\"InputValue\",\"InputValueExpression\",\"IntegerInputSchema\",\"IntegerInputSchemaType\",\"NumberInputSchema\",\"NumberInputSchemaType\",\"ObjectInputSchema\",\"ObjectInputSchemaType\",\"Params\",\"Special\",\"StringInputSchema\",\"StringInputSchemaType\",\"TaskOutput\",\"VideoInputSchema\",\"VideoInputSchemaType\"]")),
            Commands::AnyOfInputSchema { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.expression.AnyOfInputSchema.json"),
            )),
            Commands::ArrayInputSchema { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.expression.ArrayInputSchema.json"),
            )),
            Commands::ArrayInputSchemaType { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.expression.ArrayInputSchemaType.json"),
            )),
            Commands::AudioInputSchema { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.expression.AudioInputSchema.json"),
            )),
            Commands::AudioInputSchemaType { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.expression.AudioInputSchemaType.json"),
            )),
            Commands::BooleanInputSchema { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.expression.BooleanInputSchema.json"),
            )),
            Commands::BooleanInputSchemaType { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.expression.BooleanInputSchemaType.json"),
            )),
            Commands::Expression { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.expression.Expression.json"),
            )),
            Commands::FileInputSchema { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.expression.FileInputSchema.json"),
            )),
            Commands::FileInputSchemaType { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.expression.FileInputSchemaType.json"),
            )),
            Commands::ImageInputSchema { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.expression.ImageInputSchema.json"),
            )),
            Commands::ImageInputSchemaType { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.expression.ImageInputSchemaType.json"),
            )),
            Commands::InputSchema { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.expression.InputSchema.json"),
            )),
            Commands::InputValue { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.expression.InputValue.json"),
            )),
            Commands::InputValueExpression { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.expression.InputValueExpression.json"),
            )),
            Commands::IntegerInputSchema { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.expression.IntegerInputSchema.json"),
            )),
            Commands::IntegerInputSchemaType { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.expression.IntegerInputSchemaType.json"),
            )),
            Commands::NumberInputSchema { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.expression.NumberInputSchema.json"),
            )),
            Commands::NumberInputSchemaType { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.expression.NumberInputSchemaType.json"),
            )),
            Commands::ObjectInputSchema { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.expression.ObjectInputSchema.json"),
            )),
            Commands::ObjectInputSchemaType { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.expression.ObjectInputSchemaType.json"),
            )),
            Commands::Params { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.expression.Params.json"),
            )),
            Commands::Special { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.expression.Special.json"),
            )),
            Commands::StringInputSchema { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.expression.StringInputSchema.json"),
            )),
            Commands::StringInputSchemaType { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.expression.StringInputSchemaType.json"),
            )),
            Commands::TaskOutput { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.expression.TaskOutput.json"),
            )),
            Commands::VideoInputSchema { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.expression.VideoInputSchema.json"),
            )),
            Commands::VideoInputSchemaType { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.expression.VideoInputSchemaType.json"),
            )),
        }
    }
}
