// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { AgentClaudeAgentSdkAgentSchema } from "./claude_agent_sdk/agent";
import { AgentMockAgentSchema } from "./mock/agent";
import { AgentOpenrouterAgentSchema } from "./openrouter/agent";

export const AgentAgentSchema = z.union([AgentOpenrouterAgentSchema, AgentClaudeAgentSdkAgentSchema, AgentMockAgentSchema]).describe("A validated Agent with its computed content-addressed ID.\n\nThis is an untagged enum that dispatches to the per-upstream Agent.").meta({ title: "agent.Agent" });
export type AgentAgent = z.infer<typeof AgentAgentSchema>;
