// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { AgentCompletionsResponseUsageSchema } from "../../../../agent/completions/response/usage";
import { ResponseErrorSchema } from "../../../../responseError";
import { VectorCompletionsResponseStreamingAgentCompletionChunkSchema } from "../../../../vector/completions/response/streaming/agentCompletionChunk";
import { VectorCompletionsResponseStreamingObjectSchema } from "../../../../vector/completions/response/streaming/object";
import { VectorCompletionsResponseVoteSchema } from "../../../../vector/completions/response/vote";

export const FunctionsExecutionsResponseStreamingVectorCompletionTaskChunkSchema = z.object({
  index: z.number().int().min(0).meta({ format: "uint64" }),
  task_index: z.number().int().min(0).meta({ format: "uint64" }),
  task_path: z.array(z.number().int().min(0).meta({ format: "uint64" })),
  id: z.string().describe("Unique identifier for this vector completion."),
  completions: z.array(VectorCompletionsResponseStreamingAgentCompletionChunkSchema).describe("Incremental agent completion chunks from each agent."),
  votes: z.array(VectorCompletionsResponseVoteSchema).describe("Votes received so far. New votes are appended in subsequent chunks."),
  scores: z.array(z.number().meta({ format: "double" })).describe("Current weighted scores. Updated as new votes arrive."),
  weights: z.array(z.number().meta({ format: "double" })).describe("Current weight distribution across responses. Updated as new votes arrive."),
  created: z.number().int().min(0).meta({ format: "uint64" }).describe("Unix timestamp when the completion was created."),
  ensemble: z.string().describe("ID of the ensemble used for this completion."),
  object: VectorCompletionsResponseStreamingObjectSchema.describe("Object type identifier (`\"vector.completion.chunk\"`)."),
  usage: AgentCompletionsResponseUsageSchema.nullable().describe("Aggregated usage statistics. Typically present only in the final chunk.").optional(),
  error: ResponseErrorSchema.nullable().optional(),
}).describe("A chunk in a streaming vector completion response.\n\nEach chunk contains incremental updates to the completion. Use the\n[`push`](Self::push) method to accumulate chunks into a complete response.").meta({ title: "functions.executions.response.streaming.VectorCompletionTaskChunk" });
export type FunctionsExecutionsResponseStreamingVectorCompletionTaskChunk = z.infer<typeof FunctionsExecutionsResponseStreamingVectorCompletionTaskChunkSchema>;
