# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_manifest_with_name_and_source_binaries():
    from objectiveai.filesystem.plugins import ManifestWithNameAndSourceBinaries
    schema = ManifestWithNameAndSourceBinaries.model_json_schema()
