use crate::tests::stream_push::stream_push_test;
use super::*;

stream_push_test!(
    single_chunk_unchanged,
    vec![VectorCompletionChunk {
        id: "vcc-1".into(),
        completions: vec![],
        votes: vec![],
        scores: vec![],
        weights: vec![],
        created: 100,
        ensemble: "ens-1".into(),
        object: Object::VectorCompletionChunk,
        usage: None,
    }],
    VectorCompletionChunk {
        id: "vcc-1".into(),
        completions: vec![],
        votes: vec![],
        scores: vec![],
        weights: vec![],
        created: 100,
        ensemble: "ens-1".into(),
        object: Object::VectorCompletionChunk,
        usage: None,
    }
);

stream_push_test!(
    scores_and_weights_replaced,
    vec![
        VectorCompletionChunk {
            id: "vcc-2".into(),
            completions: vec![],
            votes: vec![],
            scores: vec![],
            weights: vec![],
            created: 100,
            ensemble: "ens-1".into(),
            object: Object::VectorCompletionChunk,
            usage: None,
        },
        VectorCompletionChunk {
            id: "vcc-2".into(),
            completions: vec![],
            votes: vec![],
            scores: vec![
                rust_decimal::Decimal::new(60, 2),
                rust_decimal::Decimal::new(40, 2),
            ],
            weights: vec![
                rust_decimal::Decimal::new(3, 1),
                rust_decimal::Decimal::new(7, 1),
            ],
            created: 100,
            ensemble: "ens-1".into(),
            object: Object::VectorCompletionChunk,
            usage: None,
        },
    ],
    VectorCompletionChunk {
        id: "vcc-2".into(),
        completions: vec![],
        votes: vec![],
        scores: vec![
            rust_decimal::Decimal::new(60, 2),
            rust_decimal::Decimal::new(40, 2),
        ],
        weights: vec![
            rust_decimal::Decimal::new(3, 1),
            rust_decimal::Decimal::new(7, 1),
        ],
        created: 100,
        ensemble: "ens-1".into(),
        object: Object::VectorCompletionChunk,
        usage: None,
    }
);

stream_push_test!(
    completions_merged_by_index,
    vec![
        VectorCompletionChunk {
            id: "vcc-3".into(),
            completions: vec![AgentCompletionChunk {
                index: 0,
                inner: crate::agent::completions::response::streaming::AgentCompletionChunk {
                    id: "acc-1".into(),
                    created: 0,
                    messages: vec![],
                    object: crate::agent::completions::response::streaming::Object::AgentCompletionChunk,
                    usage: None,
                    upstream: crate::agent::Upstream::Openrouter,
                    error: None,
                },
            }],
            votes: vec![],
            scores: vec![],
            weights: vec![],
            created: 100,
            ensemble: "ens-1".into(),
            object: Object::VectorCompletionChunk,
            usage: None,
        },
        VectorCompletionChunk {
            id: "vcc-3".into(),
            completions: vec![AgentCompletionChunk {
                index: 1,
                inner: crate::agent::completions::response::streaming::AgentCompletionChunk {
                    id: "acc-2".into(),
                    created: 0,
                    messages: vec![],
                    object: crate::agent::completions::response::streaming::Object::AgentCompletionChunk,
                    usage: None,
                    upstream: crate::agent::Upstream::Openrouter,
                    error: None,
                },
            }],
            votes: vec![],
            scores: vec![],
            weights: vec![],
            created: 100,
            ensemble: "ens-1".into(),
            object: Object::VectorCompletionChunk,
            usage: None,
        },
    ],
    VectorCompletionChunk {
        id: "vcc-3".into(),
        completions: vec![
            AgentCompletionChunk {
                index: 0,
                inner: crate::agent::completions::response::streaming::AgentCompletionChunk {
                    id: "acc-1".into(),
                    created: 0,
                    messages: vec![],
                    object: crate::agent::completions::response::streaming::Object::AgentCompletionChunk,
                    usage: None,
                    upstream: crate::agent::Upstream::Openrouter,
                    error: None,
                },
            },
            AgentCompletionChunk {
                index: 1,
                inner: crate::agent::completions::response::streaming::AgentCompletionChunk {
                    id: "acc-2".into(),
                    created: 0,
                    messages: vec![],
                    object: crate::agent::completions::response::streaming::Object::AgentCompletionChunk,
                    usage: None,
                    upstream: crate::agent::Upstream::Openrouter,
                    error: None,
                },
            },
        ],
        votes: vec![],
        scores: vec![],
        weights: vec![],
        created: 100,
        ensemble: "ens-1".into(),
        object: Object::VectorCompletionChunk,
        usage: None,
    }
);

stream_push_test!(
    votes_appended,
    vec![
        VectorCompletionChunk {
            id: "vcc-4".into(),
            completions: vec![],
            votes: vec![crate::vector::completions::response::Vote {
                agent: "agent-a".into(),
                ensemble_index: 0,
                flat_ensemble_index: 0,
                prompt_id: "p1".into(),
                responses_ids: vec!["r1".into()],
                vote: vec![rust_decimal::Decimal::ONE],
                weight: rust_decimal::Decimal::ONE,
                retry: None,
                from_cache: None,
                completion_index: None,
            }],
            scores: vec![],
            weights: vec![],
            created: 100,
            ensemble: "ens-1".into(),
            object: Object::VectorCompletionChunk,
            usage: None,
        },
        VectorCompletionChunk {
            id: "vcc-4".into(),
            completions: vec![],
            votes: vec![crate::vector::completions::response::Vote {
                agent: "agent-b".into(),
                ensemble_index: 1,
                flat_ensemble_index: 1,
                prompt_id: "p1".into(),
                responses_ids: vec!["r1".into()],
                vote: vec![rust_decimal::Decimal::ONE],
                weight: rust_decimal::Decimal::ONE,
                retry: None,
                from_cache: Some(true),
                completion_index: None,
            }],
            scores: vec![],
            weights: vec![],
            created: 100,
            ensemble: "ens-1".into(),
            object: Object::VectorCompletionChunk,
            usage: None,
        },
    ],
    VectorCompletionChunk {
        id: "vcc-4".into(),
        completions: vec![],
        votes: vec![
            crate::vector::completions::response::Vote {
                agent: "agent-a".into(),
                ensemble_index: 0,
                flat_ensemble_index: 0,
                prompt_id: "p1".into(),
                responses_ids: vec!["r1".into()],
                vote: vec![rust_decimal::Decimal::ONE],
                weight: rust_decimal::Decimal::ONE,
                retry: None,
                from_cache: None,
                completion_index: None,
            },
            crate::vector::completions::response::Vote {
                agent: "agent-b".into(),
                ensemble_index: 1,
                flat_ensemble_index: 1,
                prompt_id: "p1".into(),
                responses_ids: vec!["r1".into()],
                vote: vec![rust_decimal::Decimal::ONE],
                weight: rust_decimal::Decimal::ONE,
                retry: None,
                from_cache: Some(true),
                completion_index: None,
            },
        ],
        scores: vec![],
        weights: vec![],
        created: 100,
        ensemble: "ens-1".into(),
        object: Object::VectorCompletionChunk,
        usage: None,
    }
);

stream_push_test!(
    usage_set_from_later_chunk,
    vec![
        VectorCompletionChunk {
            id: "vcc-5".into(),
            completions: vec![],
            votes: vec![],
            scores: vec![],
            weights: vec![],
            created: 100,
            ensemble: "ens-1".into(),
            object: Object::VectorCompletionChunk,
            usage: None,
        },
        VectorCompletionChunk {
            id: "vcc-5".into(),
            completions: vec![],
            votes: vec![],
            scores: vec![],
            weights: vec![],
            created: 100,
            ensemble: "ens-1".into(),
            object: Object::VectorCompletionChunk,
            usage: Some(crate::agent::completions::response::Usage {
                prompt_tokens: 20,
                completion_tokens: 10,
                total_tokens: 30,
                completion_tokens_details: None,
                prompt_tokens_details: None,
                cost: rust_decimal::Decimal::ZERO,
                cost_details: None,
                total_cost: rust_decimal::Decimal::ZERO,
            }),
        },
    ],
    VectorCompletionChunk {
        id: "vcc-5".into(),
        completions: vec![],
        votes: vec![],
        scores: vec![],
        weights: vec![],
        created: 100,
        ensemble: "ens-1".into(),
        object: Object::VectorCompletionChunk,
        usage: Some(crate::agent::completions::response::Usage {
            prompt_tokens: 20,
            completion_tokens: 10,
            total_tokens: 30,
            completion_tokens_details: None,
            prompt_tokens_details: None,
            cost: rust_decimal::Decimal::ZERO,
            cost_details: None,
            total_cost: rust_decimal::Decimal::ZERO,
        }),
    }
);
