# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Literal, Union
from pydantic import BaseModel, ConfigDict, Field, RootModel
from objectiveai.functions.alpha_vector.branch_task_expression import FunctionsAlphaVectorBranchTaskExpression
from objectiveai.functions.alpha_vector.expression.vector_function_input_schema import FunctionsAlphaVectorExpressionVectorFunctionInputSchema
from objectiveai.functions.alpha_vector.leaf_task_expression import FunctionsAlphaVectorLeafTaskExpression


class FunctionsAlphaVectorRemoteFunctionVariant1(BaseModel):
    description: str
    input_schema: FunctionsAlphaVectorExpressionVectorFunctionInputSchema
    tasks: list[FunctionsAlphaVectorBranchTaskExpression]
    type_: Literal['alpha.vector.branch.function'] = Field(..., alias='type')


class FunctionsAlphaVectorRemoteFunctionVariant2(BaseModel):
    description: str
    input_schema: FunctionsAlphaVectorExpressionVectorFunctionInputSchema
    tasks: list[FunctionsAlphaVectorLeafTaskExpression]
    type_: Literal['alpha.vector.leaf.function'] = Field(..., alias='type')


class FunctionsAlphaVectorRemoteFunction(RootModel):
    model_config = ConfigDict(title='functions.alpha_vector.RemoteFunction')

    root: Union[FunctionsAlphaVectorRemoteFunctionVariant1, FunctionsAlphaVectorRemoteFunctionVariant2]

