# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Literal, Union
from pydantic import BaseModel, ConfigDict, Field, RootModel
from objectiveai.functions.alpha_vector.branch_task_expression import BranchTaskExpression
from objectiveai.functions.alpha_vector.expression.vector_function_input_schema import VectorFunctionInputSchema
from objectiveai.functions.alpha_vector.leaf_task_expression import LeafTaskExpression


class RemoteFunctionVariant1(BaseModel):
    description: str
    input_schema: VectorFunctionInputSchema
    tasks: list[BranchTaskExpression]
    type_: Literal['alpha.vector.branch.function'] = Field(..., alias='type')


class RemoteFunctionVariant2(BaseModel):
    description: str
    input_schema: VectorFunctionInputSchema
    tasks: list[LeafTaskExpression]
    type_: Literal['alpha.vector.leaf.function'] = Field(..., alias='type')


class RemoteFunction(RootModel):
    model_config = ConfigDict(title='functions.alpha_vector.RemoteFunction')

    root: Union[RemoteFunctionVariant1, RemoteFunctionVariant2]

