# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from objectiveai.agent.claude_agent_sdk import Effort

schema = Effort.model_json_schema()
