# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_rich_content_part_expression_variant3():
    from objectiveai.agent.completions.message import RichContentPartExpressionVariant3
    schema = RichContentPartExpressionVariant3.model_json_schema()
