# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_message_variant5():
    from objectiveai.agent.completions.message import MessageVariant5
    schema = MessageVariant5.model_json_schema()
