# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_rich_content_part_expression_variant2_image_url_variant2():
    from objectiveai.agent.completions.message import RichContentPartExpressionVariant2Image_urlVariant2
    schema = RichContentPartExpressionVariant2Image_urlVariant2.model_json_schema()
