# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_message_variant5_variant1():
    from objectiveai.agent.completions.message import MessageVariant5Variant1
    schema = MessageVariant5Variant1.model_json_schema()
