# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from objectiveai.agent.completions.message import RichContentPartVariant3

schema = RichContentPartVariant3.model_json_schema()
