# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_assistant_message_expression_refusal_variant1():
    from objectiveai.agent.completions.message import AssistantMessageExpressionRefusalVariant1
    schema = AssistantMessageExpressionRefusalVariant1.model_json_schema()
