# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_user_message_expression_name_variant1():
    from objectiveai.agent.completions.message import UserMessageExpressionNameVariant1
    schema = UserMessageExpressionNameVariant1.model_json_schema()
