# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_developer_message_expression_content_variant1():
    from objectiveai.agent.completions.message import DeveloperMessageExpressionContentVariant1
    schema = DeveloperMessageExpressionContentVariant1.model_json_schema()
