# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_system_message_expression_name_variant1():
    from objectiveai.agent.completions.message import SystemMessageExpressionNameVariant1
    schema = SystemMessageExpressionNameVariant1.model_json_schema()
