# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_rich_content_part_expression_variant1_text_variant2():
    from objectiveai.agent.completions.message import RichContentPartExpressionVariant1TextVariant2
    schema = RichContentPartExpressionVariant1TextVariant2.model_json_schema()
