// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package alpha_scalar

type PartialPlaceholderScalarFunctionTaskExpression struct {
	Input any `json:"input"`
	InputSchema any `json:"input_schema"`
	Skip any `json:"skip,omitempty"`
	Spec string `json:"spec"`
}

func (PartialPlaceholderScalarFunctionTaskExpression) JSONSchema() map[string]any {
	return map[string]any{
		"title": "functions.alpha_scalar.PartialPlaceholderScalarFunctionTaskExpression",
		"type": "object",
		"properties": map[string]any{
			"input": map[string]any{
			"$ref": "functions.expression.Expression",
		},
			"input_schema": map[string]any{
			"$ref": "functions.expression.ObjectInputSchema",
		},
			"skip": map[string]any{
			"anyOf": []any{map[string]any{"$ref": "functions.expression.Expression"}, map[string]any{"type": "null"}},
		},
			"spec": map[string]any{
			"type": "string",
		},
		},
	}
}
