// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by objectiveai-cli-builder from objectiveai-json-schema/.

pub mod executions;

use clap::Subcommand;

#[derive(Subcommand)]
#[command(rename_all = "verbatim")]
pub enum Commands {
    #[command(name = "list")]
    List,
    #[command(name = "executions")]
    Executions {
        #[command(subcommand)]
        command: executions::Commands,
    },
}

impl Commands {
    pub async fn handle(self, handle: &objectiveai_cli_lib::output::Handle) -> Result<(), crate::error::Error> {
        match self {
            Commands::List => {
                const NAMES: &[&str] = &["executions"];
                objectiveai_cli_lib::output::Output::<objectiveai_cli_lib::output::Schemas>::Notification(
                    objectiveai_cli_lib::output::Notification {
                        value: objectiveai_cli_lib::output::Schemas {
                            schemas: NAMES.iter().map(|s| s.to_string()).collect(),
                        },
                    },
                ).emit(handle).await;
                Ok(())
            }
            Commands::Executions { command } => command.handle(handle).await,
        }
    }
}
