# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional, TYPE_CHECKING, Union
from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from objectiveai.functions.expression.input_schema import FunctionsExpressionInputSchema


class FunctionsExpressionArrayInputSchema(BaseModel):
    """Schema for an array input."""
    description: Optional[Union[str, None]] = Field(None, description='Human-readable description of the array.')
    min_items: Optional[Union[int, None]] = Field(None, alias='minItems', description='Minimum number of items required.', ge=0, json_schema_extra={'format': 'uint64'})
    max_items: Optional[Union[int, None]] = Field(None, alias='maxItems', description='Maximum number of items allowed.', ge=0, json_schema_extra={'format': 'uint64'})
    items: FunctionsExpressionInputSchema = Field(..., description='Schema for each item in the array.')

