# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional, Union
from pydantic import BaseModel


class FunctionsExpressionAudioInputSchema(BaseModel):
    """Schema for an audio input."""
    description: Optional[Union[str, None]] = None

