# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Union
from pydantic import BaseModel, ConfigDict, Field, RootModel
from objectiveai.functions.expression.special import Special


class ExpressionVariant1(BaseModel):
    """A JMESPath expression."""
    model_config = ConfigDict(extra='forbid')

    jmespath: str = Field(..., alias='$jmespath')


class ExpressionVariant2(BaseModel):
    """A Starlark expression."""
    model_config = ConfigDict(extra='forbid')

    starlark: str = Field(..., alias='$starlark')


class ExpressionVariant3(BaseModel):
    """A predefined special expression variant."""
    model_config = ConfigDict(extra='forbid')

    special: Special = Field(..., alias='$special')


class Expression(RootModel):
    """An expression that can be either JMESPath or Starlark.

Serializes as `{"$jmespath": "..."}` or `{"$starlark": "..."}` in JSON.

# Examples

JMESPath:
```json
{"$jmespath": "input.items[0].name"}
```

Starlark:
```json
{"$starlark": "input['items'][0]['name']"}
```"""
    model_config = ConfigDict(title='functions.expression.Expression')

    root: Union[ExpressionVariant1, ExpressionVariant2, ExpressionVariant3]

