# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from pydantic import RootModel
from objectiveai.functions.expression.audio_input_schema import FunctionsExpressionAudioInputSchema
from objectiveai.functions.expression.boolean_input_schema import FunctionsExpressionBooleanInputSchema
from objectiveai.functions.expression.file_input_schema import FunctionsExpressionFileInputSchema
from objectiveai.functions.expression.image_input_schema import FunctionsExpressionImageInputSchema
from objectiveai.functions.expression.integer_input_schema import FunctionsExpressionIntegerInputSchema
from objectiveai.functions.expression.number_input_schema import FunctionsExpressionNumberInputSchema
from objectiveai.functions.expression.string_input_schema import FunctionsExpressionStringInputSchema
from objectiveai.functions.expression.video_input_schema import FunctionsExpressionVideoInputSchema
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from objectiveai.functions.expression.any_of_input_schema import FunctionsExpressionAnyOfInputSchema
    from objectiveai.functions.expression.array_input_schema import FunctionsExpressionArrayInputSchema
    from objectiveai.functions.expression.object_input_schema import FunctionsExpressionObjectInputSchema


class FunctionsExpressionInputSchema(RootModel):
    """Schema for validating Function input.

Defines the expected structure and constraints for input data.
Used by remote Functions to document and validate their inputs."""
    root: dict[str, object]

