# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Union
from pydantic import ConfigDict, RootModel


class OneOrMany_stringVariant1(RootModel):
    """A single value."""
    root: str


class OneOrMany_stringVariant2(RootModel):
    """Multiple values (from array expressions)."""
    root: list[str]


class OneOrMany_string(RootModel):
    """Result of an expression that may produce one or many values."""
    model_config = ConfigDict(title='functions.expression.OneOrMany.string')

    root: Union[OneOrMany_stringVariant1, OneOrMany_stringVariant2]

