# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Annotated, Union
from objectiveai.json_value import JsonValue
from pydantic import ConfigDict, Field, RootModel


class TaskOutputRefVariant1(RootModel):
    """A single scalar score."""
    root: Annotated[float, Field(ge=-3.4028234663852886e+38, le=3.4028234663852886e+38)]


class TaskOutputRefVariant2(RootModel):
    """A vector of scores."""
    root: list[Annotated[float, Field(ge=-3.4028234663852886e+38, le=3.4028234663852886e+38)]]


class TaskOutputRefVariant3(RootModel):
    """Multiple vectors of scores (from mapped tasks)."""
    root: list[list[Annotated[float, Field(ge=-3.4028234663852886e+38, le=3.4028234663852886e+38)]]]


class TaskOutputRefVariant4(RootModel):
    """An error occurred during execution."""
    root: JsonValue


class TaskOutputRef(RootModel):
    """Borrowed task output variants."""
    model_config = ConfigDict(title='functions.expression.TaskOutputRef')

    root: Union[TaskOutputRefVariant1, TaskOutputRefVariant2, TaskOutputRefVariant3, TaskOutputRefVariant4]

