# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Union


FunctionsExpressionTaskOutputRef = Union[float, list[float], list[list[float]], object]
"""Borrowed task output variants."""

