# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional, TYPE_CHECKING, Union
from pydantic import ConfigDict, RootModel
from objectiveai.agent.completions.message.file import AgentCompletionsMessageFile
from objectiveai.agent.completions.message.image_url import AgentCompletionsMessageImageUrl
from objectiveai.agent.completions.message.input_audio import AgentCompletionsMessageInputAudio
from objectiveai.agent.completions.message.video_url import AgentCompletionsMessageVideoUrl
from objectiveai.functions.expression.expression import FunctionsExpressionExpression

if TYPE_CHECKING:
    from objectiveai.agent.completions.message.assistant_tool_call_expression import AgentCompletionsMessageAssistantToolCallExpression
    from objectiveai.agent.completions.message.assistant_tool_call_function_expression import AgentCompletionsMessageAssistantToolCallFunctionExpression
    from objectiveai.agent.completions.message.message_expression import AgentCompletionsMessageMessageExpression
    from objectiveai.agent.completions.message.rich_content_expression import AgentCompletionsMessageRichContentExpression
    from objectiveai.agent.completions.message.rich_content_part_expression import AgentCompletionsMessageRichContentPartExpression
    from objectiveai.agent.completions.message.simple_content_expression import AgentCompletionsMessageSimpleContentExpression
    from objectiveai.agent.completions.message.simple_content_part_expression import AgentCompletionsMessageSimpleContentPartExpression
    from objectiveai.functions.expression.input_value_expression import FunctionsExpressionInputValueExpression


class FunctionsExpressionWithExpressionAgentCompletionsMessageAssistantToolCallExpressionVariant1(RootModel):
    """An expression (JMESPath or Starlark) to evaluate."""
    root: FunctionsExpressionExpression


class FunctionsExpressionWithExpressionAgentCompletionsMessageAssistantToolCallExpressionVariant2(RootModel):
    """A literal value."""
    root: AgentCompletionsMessageAssistantToolCallExpression


class FunctionsExpressionWithExpressionAgentCompletionsMessageAssistantToolCallExpression(RootModel):
    """A value that can be either a literal or an expression.

This allows Function definitions to mix static values with dynamic
expressions. During compilation, expressions are evaluated while
literal values pass through unchanged.

# Example

Literal value:
```json
"hello world"
```

JMESPath expression:
```json
{"$jmespath": "input.greeting"}
```

Starlark expression:
```json
{"$starlark": "input['greeting']"}
```"""
    model_config = ConfigDict(title='functions.expression.WithExpression.agent.completions.message.AssistantToolCallExpression')

    root: Union[FunctionsExpressionWithExpressionAgentCompletionsMessageAssistantToolCallExpressionVariant1, FunctionsExpressionWithExpressionAgentCompletionsMessageAssistantToolCallExpressionVariant2]


class FunctionsExpressionWithExpressionAgentCompletionsMessageAssistantToolCallFunctionExpressionVariant1(RootModel):
    """An expression (JMESPath or Starlark) to evaluate."""
    root: FunctionsExpressionExpression


class FunctionsExpressionWithExpressionAgentCompletionsMessageAssistantToolCallFunctionExpressionVariant2(RootModel):
    """A literal value."""
    root: AgentCompletionsMessageAssistantToolCallFunctionExpression


class FunctionsExpressionWithExpressionAgentCompletionsMessageAssistantToolCallFunctionExpression(RootModel):
    """A value that can be either a literal or an expression.

This allows Function definitions to mix static values with dynamic
expressions. During compilation, expressions are evaluated while
literal values pass through unchanged.

# Example

Literal value:
```json
"hello world"
```

JMESPath expression:
```json
{"$jmespath": "input.greeting"}
```

Starlark expression:
```json
{"$starlark": "input['greeting']"}
```"""
    model_config = ConfigDict(title='functions.expression.WithExpression.agent.completions.message.AssistantToolCallFunctionExpression')

    root: Union[FunctionsExpressionWithExpressionAgentCompletionsMessageAssistantToolCallFunctionExpressionVariant1, FunctionsExpressionWithExpressionAgentCompletionsMessageAssistantToolCallFunctionExpressionVariant2]


class FunctionsExpressionWithExpressionAgentCompletionsMessageFileVariant1(RootModel):
    """An expression (JMESPath or Starlark) to evaluate."""
    root: FunctionsExpressionExpression


class FunctionsExpressionWithExpressionAgentCompletionsMessageFileVariant2(RootModel):
    """A literal value."""
    root: AgentCompletionsMessageFile


class FunctionsExpressionWithExpressionAgentCompletionsMessageFile(RootModel):
    """A value that can be either a literal or an expression.

This allows Function definitions to mix static values with dynamic
expressions. During compilation, expressions are evaluated while
literal values pass through unchanged.

# Example

Literal value:
```json
"hello world"
```

JMESPath expression:
```json
{"$jmespath": "input.greeting"}
```

Starlark expression:
```json
{"$starlark": "input['greeting']"}
```"""
    model_config = ConfigDict(title='functions.expression.WithExpression.agent.completions.message.File')

    root: Union[FunctionsExpressionWithExpressionAgentCompletionsMessageFileVariant1, FunctionsExpressionWithExpressionAgentCompletionsMessageFileVariant2]


class FunctionsExpressionWithExpressionAgentCompletionsMessageImageUrlVariant1(RootModel):
    """An expression (JMESPath or Starlark) to evaluate."""
    root: FunctionsExpressionExpression


class FunctionsExpressionWithExpressionAgentCompletionsMessageImageUrlVariant2(RootModel):
    """A literal value."""
    root: AgentCompletionsMessageImageUrl


class FunctionsExpressionWithExpressionAgentCompletionsMessageImageUrl(RootModel):
    """A value that can be either a literal or an expression.

This allows Function definitions to mix static values with dynamic
expressions. During compilation, expressions are evaluated while
literal values pass through unchanged.

# Example

Literal value:
```json
"hello world"
```

JMESPath expression:
```json
{"$jmespath": "input.greeting"}
```

Starlark expression:
```json
{"$starlark": "input['greeting']"}
```"""
    model_config = ConfigDict(title='functions.expression.WithExpression.agent.completions.message.ImageUrl')

    root: Union[FunctionsExpressionWithExpressionAgentCompletionsMessageImageUrlVariant1, FunctionsExpressionWithExpressionAgentCompletionsMessageImageUrlVariant2]


class FunctionsExpressionWithExpressionAgentCompletionsMessageInputAudioVariant1(RootModel):
    """An expression (JMESPath or Starlark) to evaluate."""
    root: FunctionsExpressionExpression


class FunctionsExpressionWithExpressionAgentCompletionsMessageInputAudioVariant2(RootModel):
    """A literal value."""
    root: AgentCompletionsMessageInputAudio


class FunctionsExpressionWithExpressionAgentCompletionsMessageInputAudio(RootModel):
    """A value that can be either a literal or an expression.

This allows Function definitions to mix static values with dynamic
expressions. During compilation, expressions are evaluated while
literal values pass through unchanged.

# Example

Literal value:
```json
"hello world"
```

JMESPath expression:
```json
{"$jmespath": "input.greeting"}
```

Starlark expression:
```json
{"$starlark": "input['greeting']"}
```"""
    model_config = ConfigDict(title='functions.expression.WithExpression.agent.completions.message.InputAudio')

    root: Union[FunctionsExpressionWithExpressionAgentCompletionsMessageInputAudioVariant1, FunctionsExpressionWithExpressionAgentCompletionsMessageInputAudioVariant2]


class FunctionsExpressionWithExpressionAgentCompletionsMessageMessageExpressionVariant1(RootModel):
    """An expression (JMESPath or Starlark) to evaluate."""
    root: FunctionsExpressionExpression


class FunctionsExpressionWithExpressionAgentCompletionsMessageMessageExpressionVariant2(RootModel):
    """A literal value."""
    root: AgentCompletionsMessageMessageExpression


class FunctionsExpressionWithExpressionAgentCompletionsMessageMessageExpression(RootModel):
    """A value that can be either a literal or an expression.

This allows Function definitions to mix static values with dynamic
expressions. During compilation, expressions are evaluated while
literal values pass through unchanged.

# Example

Literal value:
```json
"hello world"
```

JMESPath expression:
```json
{"$jmespath": "input.greeting"}
```

Starlark expression:
```json
{"$starlark": "input['greeting']"}
```"""
    model_config = ConfigDict(title='functions.expression.WithExpression.agent.completions.message.MessageExpression')

    root: Union[FunctionsExpressionWithExpressionAgentCompletionsMessageMessageExpressionVariant1, FunctionsExpressionWithExpressionAgentCompletionsMessageMessageExpressionVariant2]


class FunctionsExpressionWithExpressionAgentCompletionsMessageRichContentExpressionVariant1(RootModel):
    """An expression (JMESPath or Starlark) to evaluate."""
    root: FunctionsExpressionExpression


class FunctionsExpressionWithExpressionAgentCompletionsMessageRichContentExpressionVariant2(RootModel):
    """A literal value."""
    root: AgentCompletionsMessageRichContentExpression


class FunctionsExpressionWithExpressionAgentCompletionsMessageRichContentExpression(RootModel):
    """A value that can be either a literal or an expression.

This allows Function definitions to mix static values with dynamic
expressions. During compilation, expressions are evaluated while
literal values pass through unchanged.

# Example

Literal value:
```json
"hello world"
```

JMESPath expression:
```json
{"$jmespath": "input.greeting"}
```

Starlark expression:
```json
{"$starlark": "input['greeting']"}
```"""
    model_config = ConfigDict(title='functions.expression.WithExpression.agent.completions.message.RichContentExpression')

    root: Union[FunctionsExpressionWithExpressionAgentCompletionsMessageRichContentExpressionVariant1, FunctionsExpressionWithExpressionAgentCompletionsMessageRichContentExpressionVariant2]


class FunctionsExpressionWithExpressionAgentCompletionsMessageRichContentPartExpressionVariant1(RootModel):
    """An expression (JMESPath or Starlark) to evaluate."""
    root: FunctionsExpressionExpression


class FunctionsExpressionWithExpressionAgentCompletionsMessageRichContentPartExpressionVariant2(RootModel):
    """A literal value."""
    root: AgentCompletionsMessageRichContentPartExpression


class FunctionsExpressionWithExpressionAgentCompletionsMessageRichContentPartExpression(RootModel):
    """A value that can be either a literal or an expression.

This allows Function definitions to mix static values with dynamic
expressions. During compilation, expressions are evaluated while
literal values pass through unchanged.

# Example

Literal value:
```json
"hello world"
```

JMESPath expression:
```json
{"$jmespath": "input.greeting"}
```

Starlark expression:
```json
{"$starlark": "input['greeting']"}
```"""
    model_config = ConfigDict(title='functions.expression.WithExpression.agent.completions.message.RichContentPartExpression')

    root: Union[FunctionsExpressionWithExpressionAgentCompletionsMessageRichContentPartExpressionVariant1, FunctionsExpressionWithExpressionAgentCompletionsMessageRichContentPartExpressionVariant2]


class FunctionsExpressionWithExpressionAgentCompletionsMessageSimpleContentExpressionVariant1(RootModel):
    """An expression (JMESPath or Starlark) to evaluate."""
    root: FunctionsExpressionExpression


class FunctionsExpressionWithExpressionAgentCompletionsMessageSimpleContentExpressionVariant2(RootModel):
    """A literal value."""
    root: AgentCompletionsMessageSimpleContentExpression


class FunctionsExpressionWithExpressionAgentCompletionsMessageSimpleContentExpression(RootModel):
    """A value that can be either a literal or an expression.

This allows Function definitions to mix static values with dynamic
expressions. During compilation, expressions are evaluated while
literal values pass through unchanged.

# Example

Literal value:
```json
"hello world"
```

JMESPath expression:
```json
{"$jmespath": "input.greeting"}
```

Starlark expression:
```json
{"$starlark": "input['greeting']"}
```"""
    model_config = ConfigDict(title='functions.expression.WithExpression.agent.completions.message.SimpleContentExpression')

    root: Union[FunctionsExpressionWithExpressionAgentCompletionsMessageSimpleContentExpressionVariant1, FunctionsExpressionWithExpressionAgentCompletionsMessageSimpleContentExpressionVariant2]


class FunctionsExpressionWithExpressionAgentCompletionsMessageSimpleContentPartExpressionVariant1(RootModel):
    """An expression (JMESPath or Starlark) to evaluate."""
    root: FunctionsExpressionExpression


class FunctionsExpressionWithExpressionAgentCompletionsMessageSimpleContentPartExpressionVariant2(RootModel):
    """A literal value."""
    root: AgentCompletionsMessageSimpleContentPartExpression


class FunctionsExpressionWithExpressionAgentCompletionsMessageSimpleContentPartExpression(RootModel):
    """A value that can be either a literal or an expression.

This allows Function definitions to mix static values with dynamic
expressions. During compilation, expressions are evaluated while
literal values pass through unchanged.

# Example

Literal value:
```json
"hello world"
```

JMESPath expression:
```json
{"$jmespath": "input.greeting"}
```

Starlark expression:
```json
{"$starlark": "input['greeting']"}
```"""
    model_config = ConfigDict(title='functions.expression.WithExpression.agent.completions.message.SimpleContentPartExpression')

    root: Union[FunctionsExpressionWithExpressionAgentCompletionsMessageSimpleContentPartExpressionVariant1, FunctionsExpressionWithExpressionAgentCompletionsMessageSimpleContentPartExpressionVariant2]


class FunctionsExpressionWithExpressionAgentCompletionsMessageVideoUrlVariant1(RootModel):
    """An expression (JMESPath or Starlark) to evaluate."""
    root: FunctionsExpressionExpression


class FunctionsExpressionWithExpressionAgentCompletionsMessageVideoUrlVariant2(RootModel):
    """A literal value."""
    root: AgentCompletionsMessageVideoUrl


class FunctionsExpressionWithExpressionAgentCompletionsMessageVideoUrl(RootModel):
    """A value that can be either a literal or an expression.

This allows Function definitions to mix static values with dynamic
expressions. During compilation, expressions are evaluated while
literal values pass through unchanged.

# Example

Literal value:
```json
"hello world"
```

JMESPath expression:
```json
{"$jmespath": "input.greeting"}
```

Starlark expression:
```json
{"$starlark": "input['greeting']"}
```"""
    model_config = ConfigDict(title='functions.expression.WithExpression.agent.completions.message.VideoUrl')

    root: Union[FunctionsExpressionWithExpressionAgentCompletionsMessageVideoUrlVariant1, FunctionsExpressionWithExpressionAgentCompletionsMessageVideoUrlVariant2]


class FunctionsExpressionWithExpressionArrayOfFunctionsExpressionWithExpressionAgentCompletionsMessageMessageExpressionVariant1(RootModel):
    """An expression (JMESPath or Starlark) to evaluate."""
    root: FunctionsExpressionExpression


class FunctionsExpressionWithExpressionArrayOfFunctionsExpressionWithExpressionAgentCompletionsMessageMessageExpressionVariant2(RootModel):
    """A literal value."""
    root: list[FunctionsExpressionWithExpressionAgentCompletionsMessageMessageExpression]


class FunctionsExpressionWithExpressionArrayOfFunctionsExpressionWithExpressionAgentCompletionsMessageMessageExpression(RootModel):
    """A value that can be either a literal or an expression.

This allows Function definitions to mix static values with dynamic
expressions. During compilation, expressions are evaluated while
literal values pass through unchanged.

# Example

Literal value:
```json
"hello world"
```

JMESPath expression:
```json
{"$jmespath": "input.greeting"}
```

Starlark expression:
```json
{"$starlark": "input['greeting']"}
```"""
    model_config = ConfigDict(title='functions.expression.WithExpression.Array_of_functions.expression.WithExpression.agent.completions.message.MessageExpression')

    root: Union[FunctionsExpressionWithExpressionArrayOfFunctionsExpressionWithExpressionAgentCompletionsMessageMessageExpressionVariant1, FunctionsExpressionWithExpressionArrayOfFunctionsExpressionWithExpressionAgentCompletionsMessageMessageExpressionVariant2]


class FunctionsExpressionWithExpressionArrayOfFunctionsExpressionWithExpressionAgentCompletionsMessageRichContentExpressionVariant1(RootModel):
    """An expression (JMESPath or Starlark) to evaluate."""
    root: FunctionsExpressionExpression


class FunctionsExpressionWithExpressionArrayOfFunctionsExpressionWithExpressionAgentCompletionsMessageRichContentExpressionVariant2(RootModel):
    """A literal value."""
    root: list[FunctionsExpressionWithExpressionAgentCompletionsMessageRichContentExpression]


class FunctionsExpressionWithExpressionArrayOfFunctionsExpressionWithExpressionAgentCompletionsMessageRichContentExpression(RootModel):
    """A value that can be either a literal or an expression.

This allows Function definitions to mix static values with dynamic
expressions. During compilation, expressions are evaluated while
literal values pass through unchanged.

# Example

Literal value:
```json
"hello world"
```

JMESPath expression:
```json
{"$jmespath": "input.greeting"}
```

Starlark expression:
```json
{"$starlark": "input['greeting']"}
```"""
    model_config = ConfigDict(title='functions.expression.WithExpression.Array_of_functions.expression.WithExpression.agent.completions.message.RichContentExpression')

    root: Union[FunctionsExpressionWithExpressionArrayOfFunctionsExpressionWithExpressionAgentCompletionsMessageRichContentExpressionVariant1, FunctionsExpressionWithExpressionArrayOfFunctionsExpressionWithExpressionAgentCompletionsMessageRichContentExpressionVariant2]


class FunctionsExpressionWithExpressionFunctionsExpressionInputValueExpressionVariant1(RootModel):
    """An expression (JMESPath or Starlark) to evaluate."""
    root: FunctionsExpressionExpression


class FunctionsExpressionWithExpressionFunctionsExpressionInputValueExpressionVariant2(RootModel):
    """A literal value."""
    root: FunctionsExpressionInputValueExpression


class FunctionsExpressionWithExpressionFunctionsExpressionInputValueExpression(RootModel):
    """A value that can be either a literal or an expression.

This allows Function definitions to mix static values with dynamic
expressions. During compilation, expressions are evaluated while
literal values pass through unchanged.

# Example

Literal value:
```json
"hello world"
```

JMESPath expression:
```json
{"$jmespath": "input.greeting"}
```

Starlark expression:
```json
{"$starlark": "input['greeting']"}
```"""
    model_config = ConfigDict(title='functions.expression.WithExpression.functions.expression.InputValueExpression')

    root: Union[FunctionsExpressionWithExpressionFunctionsExpressionInputValueExpressionVariant1, FunctionsExpressionWithExpressionFunctionsExpressionInputValueExpressionVariant2]


class FunctionsExpressionWithExpressionNullableAgentCompletionsMessageRichContentExpressionVariant1(RootModel):
    """An expression (JMESPath or Starlark) to evaluate."""
    root: FunctionsExpressionExpression


class FunctionsExpressionWithExpressionNullableAgentCompletionsMessageRichContentExpressionVariant2(RootModel):
    """A literal value."""
    root: Optional[AgentCompletionsMessageRichContentExpression]


class FunctionsExpressionWithExpressionNullableAgentCompletionsMessageRichContentExpression(RootModel):
    """A value that can be either a literal or an expression.

This allows Function definitions to mix static values with dynamic
expressions. During compilation, expressions are evaluated while
literal values pass through unchanged.

# Example

Literal value:
```json
"hello world"
```

JMESPath expression:
```json
{"$jmespath": "input.greeting"}
```

Starlark expression:
```json
{"$starlark": "input['greeting']"}
```"""
    model_config = ConfigDict(title='functions.expression.WithExpression.Nullable_agent.completions.message.RichContentExpression')

    root: Union[FunctionsExpressionWithExpressionNullableAgentCompletionsMessageRichContentExpressionVariant1, FunctionsExpressionWithExpressionNullableAgentCompletionsMessageRichContentExpressionVariant2]


class FunctionsExpressionWithExpressionNullableArrayOfFunctionsExpressionWithExpressionAgentCompletionsMessageAssistantToolCallExpressionVariant1(RootModel):
    """An expression (JMESPath or Starlark) to evaluate."""
    root: FunctionsExpressionExpression


class FunctionsExpressionWithExpressionNullableArrayOfFunctionsExpressionWithExpressionAgentCompletionsMessageAssistantToolCallExpressionVariant2(RootModel):
    """A literal value."""
    root: Optional[list[FunctionsExpressionWithExpressionAgentCompletionsMessageAssistantToolCallExpression]]


class FunctionsExpressionWithExpressionNullableArrayOfFunctionsExpressionWithExpressionAgentCompletionsMessageAssistantToolCallExpression(RootModel):
    """A value that can be either a literal or an expression.

This allows Function definitions to mix static values with dynamic
expressions. During compilation, expressions are evaluated while
literal values pass through unchanged.

# Example

Literal value:
```json
"hello world"
```

JMESPath expression:
```json
{"$jmespath": "input.greeting"}
```

Starlark expression:
```json
{"$starlark": "input['greeting']"}
```"""
    model_config = ConfigDict(title='functions.expression.WithExpression.Nullable_Array_of_functions.expression.WithExpression.agent.completions.message.AssistantToolCallExpression')

    root: Union[FunctionsExpressionWithExpressionNullableArrayOfFunctionsExpressionWithExpressionAgentCompletionsMessageAssistantToolCallExpressionVariant1, FunctionsExpressionWithExpressionNullableArrayOfFunctionsExpressionWithExpressionAgentCompletionsMessageAssistantToolCallExpressionVariant2]


class FunctionsExpressionWithExpressionNullableStringVariant1(RootModel):
    """An expression (JMESPath or Starlark) to evaluate."""
    root: FunctionsExpressionExpression


class FunctionsExpressionWithExpressionNullableStringVariant2(RootModel):
    """A literal value."""
    root: Optional[str]


class FunctionsExpressionWithExpressionNullableString(RootModel):
    """A value that can be either a literal or an expression.

This allows Function definitions to mix static values with dynamic
expressions. During compilation, expressions are evaluated while
literal values pass through unchanged.

# Example

Literal value:
```json
"hello world"
```

JMESPath expression:
```json
{"$jmespath": "input.greeting"}
```

Starlark expression:
```json
{"$starlark": "input['greeting']"}
```"""
    model_config = ConfigDict(title='functions.expression.WithExpression.Nullable_string')

    root: Union[FunctionsExpressionWithExpressionNullableStringVariant1, FunctionsExpressionWithExpressionNullableStringVariant2]


class FunctionsExpressionWithExpressionStringVariant1(RootModel):
    """An expression (JMESPath or Starlark) to evaluate."""
    root: FunctionsExpressionExpression


class FunctionsExpressionWithExpressionStringVariant2(RootModel):
    """A literal value."""
    root: str


class FunctionsExpressionWithExpressionString(RootModel):
    """A value that can be either a literal or an expression.

This allows Function definitions to mix static values with dynamic
expressions. During compilation, expressions are evaluated while
literal values pass through unchanged.

# Example

Literal value:
```json
"hello world"
```

JMESPath expression:
```json
{"$jmespath": "input.greeting"}
```

Starlark expression:
```json
{"$starlark": "input['greeting']"}
```"""
    model_config = ConfigDict(title='functions.expression.WithExpression.string')

    root: Union[FunctionsExpressionWithExpressionStringVariant1, FunctionsExpressionWithExpressionStringVariant2]

