# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_vector_input_schema_object():
    from objectiveai.functions.inventions import VectorInputSchemaObject
    schema = VectorInputSchemaObject.model_json_schema()
