# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional, Union
from pydantic import BaseModel
from objectiveai.agent.completions.request.agent import AgentCompletionsRequestAgent
from objectiveai.agent.completions.request.provider import AgentCompletionsRequestProvider
from objectiveai.functions.inventions.state.params_state import FunctionsInventionsStateParamsState
from objectiveai.functions.remote import FunctionsRemote


class FunctionsInventionsRequestFunctionInventionCreateParams(BaseModel):
    remote: Optional[FunctionsRemote] = None
    overwrite: Optional[Union[bool, None]] = None
    state: FunctionsInventionsStateParamsState
    provider: Optional[AgentCompletionsRequestProvider] = None
    agent: AgentCompletionsRequestAgent
    agents: Optional[Union[list[AgentCompletionsRequestAgent], None]] = None
    seed: Optional[Union[int, None]] = None
    stream: Optional[Union[bool, None]] = None
    max_step_retries: Optional[Union[int, None]] = None
    mcp_server_authorization: Optional[Union[dict[str, str], None]] = None

