// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const FunctionsInventionsIndexObjectSchema = z.object({
  index: z.number().int().min(0).meta({ format: "uint64" }),
}).meta({ title: "functions.inventions.IndexObject" });
export type FunctionsInventionsIndexObject = z.infer<typeof FunctionsInventionsIndexObjectSchema>;
