# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from objectiveai.agent.completions.response import UpstreamUsage

schema = UpstreamUsage.model_json_schema()
