//! Mock upstream client for agent completions.

use std::collections::HashMap;
use std::pin::Pin;
use std::time::Duration;
use futures::Stream;
use objectiveai::agent::completions::response::{Logprob, Logprobs};
use rand::{Rng, SeedableRng};
use super::super::{ContinuationItem, StreamItem, UpstreamClient, ResolvedTool};
use super::State;

/// Mock upstream client that generates random responses with configurable delay.
#[derive(Debug, Clone)]
pub struct Client {
    /// Delay before yielding each chunk.
    pub delay: Duration,
}

/// Resolves the response format for this agent from the request params.
fn resolve_response_format(
    agent_id: &str,
    params: &objectiveai::agent::completions::request::AgentCompletionCreateParams,
) -> Option<objectiveai::agent::completions::request::ResponseFormat> {
    use objectiveai::agent::completions::request::ResponseFormatParam;
    match params.response_format.as_ref()? {
        ResponseFormatParam::Single(rf) => Some(rf.clone()),
        ResponseFormatParam::PerAgent(map) => map.get(agent_id).cloned(),
    }
}

/// A single tool call generated by the mock.
struct MockToolCall {
    tool_name: String,
    call_id: String,
    arguments: String,
    n_deltas: usize,
}

/// The outcome of the tool-vs-content dice roll.
enum MockResponse {
    /// Respond with text content, chunked by logprob token boundaries.
    Content {
        text: String,
        logprobs: Option<Vec<Logprob>>,
    },
    /// Respond with one or more parallel tool calls.
    ToolCalls(Vec<MockToolCall>),
}

impl UpstreamClient<objectiveai::agent::mock::Agent> for Client {
    type State = State;
    type Stream = Pin<
        Box<dyn Stream<Item = StreamItem<Self::State>> + Send + 'static>,
    >;
    type Error = super::Error;

    fn create(
        &self,
        id: &str,
        created: u64,
        agent: &objectiveai::agent::mock::Agent,
        params: &objectiveai::agent::completions::request::AgentCompletionCreateParams,
        _messages: &[objectiveai::agent::completions::message::Message],
        _mcp_connections: &[std::sync::Arc<crate::mcp::Connection>],
        _invention_tools: Option<
            &[objectiveai::functions::inventions::InventionTool],
        >,
        tool_names: &[String],
        tool_map: &HashMap<String, ResolvedTool>,
        _continuation: Option<&[ContinuationItem<Self::State>]>,
        byok: Option<&str>,
        _cost_multiplier: rust_decimal::Decimal,
        _tools_enabled: bool,
    ) -> impl Future<
        Output = Result<
            (Self::Stream, Self::State),
            Self::Error,
        >,
    > + Send
    + 'static {
        let id = id.to_string();
        let agent_id = agent.id.clone();
        let error = agent.base.error == Some(true);
        let top_logprobs = agent.base.top_logprobs;
        let response_format = resolve_response_format(&agent.id, params);
        let tool_names = tool_names.to_vec();
        let tool_map = tool_map.clone();
        let delay = self.delay;
        let cont_len = _continuation.map_or(0u64, |c| c.len() as u64);
        let seed = params.seed.map(|s| {
            use std::hash::Hasher;
            let mut hasher = twox_hash::XxHash3_64::with_seed(s as u64);
            hasher.write(&cont_len.to_le_bytes());
            // Hash messages (prompt_id-style) for differentiation across tasks
            {
                let mut prompt = _messages.to_vec();
                objectiveai::agent::completions::message::prompt::prepare(&mut prompt);
                let pid = objectiveai::agent::completions::message::prompt::id(&prompt);
                hasher.write(pid.as_bytes());
            }
            // Hash tool names for differentiation across tool configurations
            for tn in &tool_names {
                hasher.write(tn.as_bytes());
            }
            hasher.finish()
        });
        let prior_tool_call_count = _continuation
            .and_then(|items| {
                items.iter().rev().find_map(|item| match item {
                    ContinuationItem::State(s) => Some(s.tool_call_count),
                    _ => None,
                })
            })
            .unwrap_or(0);
        let is_byok = byok.is_some();

        async move {
            use objectiveai::agent::completions::request::ResponseFormat;

            if error {
                return Err(super::Error::ExpectedError);
            }

            // Reject Grammar and Python response formats.
            if let Some(ref rf) = response_format {
                match rf {
                    ResponseFormat::Grammar { .. } => {
                        return Err(super::Error::UnsupportedResponseFormat(
                            "grammar".into(),
                        ));
                    }
                    ResponseFormat::Python => {
                        return Err(super::Error::UnsupportedResponseFormat(
                            "python".into(),
                        ));
                    }
                    _ => {}
                }
            }

            let mut rng = match seed {
                Some(s) => rand::rngs::StdRng::seed_from_u64(s),
                None => rand::rngs::StdRng::from_os_rng(),
            };

            // --- Reasoning: roll 0-5 chunks ---
            let n_reasoning = rng.random_range(0u32..=5);
            let reasoning_chunks: Vec<String> = (0..n_reasoning)
                .map(|_| random_string(&mut rng, 20, 200))
                .collect();

            // --- Tool call vs content ---
            let mock_response = resolve_mock_response(
                &response_format,
                &tool_names,
                &tool_map,
                top_logprobs,
                &mut rng,
            );
            let tool_call_count = prior_tool_call_count + match &mock_response {
                MockResponse::ToolCalls(calls) => calls.len() as u32,
                _ => 0,
            };

            let state = State { tool_call_count };

            let stream = async_stream::stream! {
                use objectiveai::agent::completions::message::{
                    AssistantToolCallDelta, AssistantToolCallFunctionDelta,
                    AssistantToolCallType, RichContent,
                };
                use objectiveai::agent::completions::response::streaming::{
                    AgentCompletionChunk, AssistantResponseChunk, MessageChunk,
                };
                use objectiveai::agent::completions::response::FinishReason;

                // --- Yield reasoning chunks ---
                for reasoning_text in &reasoning_chunks {
                    if !delay.is_zero() {
                        tokio::time::sleep(delay).await;
                    }
                    yield StreamItem::Chunk(AgentCompletionChunk {
                        id: id.clone(),
                        created,
                        messages: vec![MessageChunk::Assistant(AssistantResponseChunk {
                            index: cont_len,
                            created,
                            agent: agent_id.clone(),
                            model: "mock".into(),
                            upstream_id: id.clone(),
                            reasoning: Some(reasoning_text.clone()),
                            ..Default::default()
                        })],
                        object: Default::default(),
                        usage: None,
                        upstream: objectiveai::agent::Upstream::Mock,
                        error: None,
                    });
                }

                // --- Yield content or tool call chunks ---
                match &mock_response {
                    MockResponse::Content { text, logprobs } => {
                        let chunks = chunk_by_logprobs(text, logprobs.as_deref(), &mut rng);

                        for (i, (chunk_text, chunk_logprobs)) in chunks.iter().enumerate() {
                            let is_last = i == chunks.len() - 1;
                            if !delay.is_zero() {
                                tokio::time::sleep(delay).await;
                            }
                            yield StreamItem::Chunk(AgentCompletionChunk {
                                id: id.clone(),
                                created,
                                messages: vec![MessageChunk::Assistant(AssistantResponseChunk {
                                    index: cont_len,
                                    created,
                                    agent: agent_id.clone(),
                                    model: "mock".into(),
                                    upstream_id: id.clone(),
                                    content: Some(RichContent::Text(chunk_text.clone())),
                                    logprobs: chunk_logprobs.as_ref().map(|lps| Logprobs {
                                        content: Some(lps.clone()),
                                        refusal: None,
                                    }),
                                    finish_reason: if is_last {
                                        Some(FinishReason::Stop)
                                    } else {
                                        None
                                    },
                                    ..Default::default()
                                })],
                                object: Default::default(),
                                usage: None,
                                upstream: objectiveai::agent::Upstream::Mock,
                                error: None,
                            });
                        }
                    }
                    MockResponse::ToolCalls(calls) => {
                        for (tc_idx, tc) in calls.iter().enumerate() {
                            let chunk_size = (tc.arguments.len() + tc.n_deltas - 1) / tc.n_deltas;
                            let parts: Vec<&str> = if tc.arguments.is_empty() {
                                vec![""]
                            } else {
                                tc.arguments.as_bytes()
                                    .chunks(chunk_size.max(1))
                                    .map(|b| std::str::from_utf8(b).unwrap_or(""))
                                    .collect()
                            };

                            for (i, part) in parts.iter().enumerate() {
                                let is_first = i == 0;
                                let is_last = i == parts.len() - 1;
                                if !delay.is_zero() {
                                    tokio::time::sleep(delay).await;
                                }
                                yield StreamItem::Chunk(AgentCompletionChunk {
                                    id: id.clone(),
                                    created,
                                    messages: vec![MessageChunk::Assistant(AssistantResponseChunk {
                                        index: cont_len,
                                        created,
                                        agent: agent_id.clone(),
                                        model: "mock".into(),
                                        upstream_id: id.clone(),
                                        tool_calls: Some(vec![AssistantToolCallDelta {
                                            index: tc_idx as u64,
                                            r#type: if is_first {
                                                Some(AssistantToolCallType::Function)
                                            } else {
                                                None
                                            },
                                            id: if is_first {
                                                Some(tc.call_id.clone())
                                            } else {
                                                None
                                            },
                                            function: Some(AssistantToolCallFunctionDelta {
                                                name: if is_first {
                                                    Some(tc.tool_name.clone())
                                                } else {
                                                    None
                                                },
                                                arguments: Some(part.to_string()),
                                            }),
                                        }]),
                                        finish_reason: if is_last && tc_idx == calls.len() - 1 {
                                            Some(FinishReason::ToolCalls)
                                        } else {
                                            None
                                        },
                                        ..Default::default()
                                    })],
                                    object: Default::default(),
                                    usage: None,
                                    upstream: objectiveai::agent::Upstream::Mock,
                                    error: None,
                                });
                            }
                        }
                    }
                }

                // --- Yield final state ---
                yield StreamItem::State(state);
            };

            let boxed: Pin<Box<dyn Stream<Item = StreamItem<Self::State>> + Send>> =
                Box::pin(stream);
            Ok((boxed, State { tool_call_count }))
        }
    }
}

/// Splits content into chunks aligned to logprob token boundaries.
/// Each chunk consumes 1-5 logprob tokens. When logprobs is None,
/// falls back to simple byte-based chunking.
fn chunk_by_logprobs(
    text: &str,
    logprobs: Option<&[Logprob]>,
    rng: &mut impl Rng,
) -> Vec<(String, Option<Vec<Logprob>>)> {
    let logprobs = match logprobs {
        Some(lps) if !lps.is_empty() => lps,
        _ => {
            // No logprobs: simple chunking like before.
            let n_chunks = rng.random_range(1u32..=5) as usize;
            let chunk_size = (text.len() + n_chunks - 1) / n_chunks.max(1);
            let parts: Vec<&str> = if text.is_empty() {
                vec![""]
            } else {
                text.as_bytes()
                    .chunks(chunk_size.max(1))
                    .map(|b| std::str::from_utf8(b).unwrap_or(""))
                    .collect()
            };
            return parts.into_iter().map(|p| (p.to_string(), None)).collect();
        }
    };

    let mut chunks = Vec::new();
    let mut pos = 0;

    while pos < logprobs.len() {
        let n_tokens = rng.random_range(1u32..=5) as usize;
        let end = (pos + n_tokens).min(logprobs.len());
        let chunk_lps = &logprobs[pos..end];
        let chunk_text: String = chunk_lps.iter().map(|lp| lp.token.as_str()).collect();
        chunks.push((chunk_text, Some(chunk_lps.to_vec())));
        pos = end;
    }

    if chunks.is_empty() {
        chunks.push((String::new(), Some(Vec::new())));
    }

    chunks
}

/// Decides whether to call a tool or respond with content, and generates the data.
fn resolve_mock_response(
    response_format: &Option<objectiveai::agent::completions::request::ResponseFormat>,
    tool_names: &[String],
    tool_map: &HashMap<String, ResolvedTool>,
    top_logprobs: Option<u64>,
    rng: &mut impl Rng,
) -> MockResponse {
    use objectiveai::agent::completions::request::ResponseFormat;

    // Check for required tool call from response format.
    if let Some(ResponseFormat::ToolCall {
        name, required: Some(true), ..
    }) = response_format
    {
        if tool_map.contains_key(name) {
            let arguments = generate_tool_arguments(tool_map, name, rng);
            return MockResponse::ToolCalls(vec![MockToolCall {
                tool_name: name.clone(),
                call_id: format!("call_mock_{}", rng.random_range(0u64..u64::MAX)),
                arguments,
                n_deltas: rng.random_range(1u32..=5) as usize,
            }]);
        }
    }

    if !tool_names.is_empty() {
        // Roll the dice: equal probability for each tool or respond as-is,
        // with respond-as-is having a minimum 25% chance.
        let n_tools = tool_names.len();
        let respond_as_is_weight = if n_tools >= 3 {
            25u32
        } else {
            (100 / (n_tools as u32 + 1)).max(25)
        };
        let tool_weight = (100 - respond_as_is_weight) / n_tools as u32;
        let roll = rng.random_range(0u32..100);

        if roll >= respond_as_is_weight {
            let tool_index = ((roll - respond_as_is_weight) / tool_weight.max(1))
                .min(n_tools as u32 - 1) as usize;
            let tool_name = &tool_names[tool_index];
            let arguments = generate_tool_arguments(tool_map, tool_name, rng);
            let mut calls = vec![MockToolCall {
                tool_name: tool_name.clone(),
                call_id: format!("call_mock_{}", rng.random_range(0u64..u64::MAX)),
                arguments,
                n_deltas: rng.random_range(1u32..=5) as usize,
            }];
            // 50/50 coin flip for each additional parallel tool call.
            while rng.random_range(0u32..2) == 1 {
                let extra_index = rng.random_range(0..n_tools);
                let extra_name = &tool_names[extra_index];
                let extra_args = generate_tool_arguments(tool_map, extra_name, rng);
                calls.push(MockToolCall {
                    tool_name: extra_name.clone(),
                    call_id: format!("call_mock_{}", rng.random_range(0u64..u64::MAX)),
                    arguments: extra_args,
                    n_deltas: rng.random_range(1u32..=5) as usize,
                });
            }
            return MockResponse::ToolCalls(calls);
        }
    }

    // Respond as-is with content.
    let (text, logprobs) = generate_content(response_format, top_logprobs, rng);
    MockResponse::Content { text, logprobs }
}

/// Generates content and optional logprobs based on response format and top_logprobs setting.
fn generate_content(
    response_format: &Option<objectiveai::agent::completions::request::ResponseFormat>,
    top_logprobs: Option<u64>,
    rng: &mut impl Rng,
) -> (String, Option<Vec<Logprob>>) {
    use objectiveai::agent::completions::request::ResponseFormat;

    let permutations = match top_logprobs {
        None | Some(0) => 1,
        Some(n) => n as usize,
    };
    let yield_logprobs = top_logprobs.is_some_and(|n| n >= 1);

    match response_format {
        Some(ResponseFormat::JsonObject) => {
            if yield_logprobs {
                let serialized = vec!["{}".to_string(); permutations];
                let (text, logprobs) = super::json_schema::generate_logprobs_from_serialized(&serialized, rng);
                (text, Some(logprobs))
            } else {
                ("{}".into(), None)
            }
        }
        Some(ResponseFormat::JsonSchema { schema }) | Some(ResponseFormat::ToolCall { schema, .. }) => {
            generate_from_schema(schema, permutations, yield_logprobs, rng)
        }
        _ => {
            // Plain text content.
            let text = random_string(rng, 10, 100);
            if yield_logprobs {
                let serialized: Vec<String> = std::iter::once(text)
                    .chain((1..permutations).map(|_| random_string(rng, 10, 100)))
                    .collect();
                let (text, logprobs) = super::json_schema::generate_logprobs_from_serialized(&serialized, rng);
                (text, Some(logprobs))
            } else {
                (text, None)
            }
        }
    }
}

/// Generates content from an IndexMap schema, with optional logprobs.
fn generate_from_schema(
    schema: &indexmap::IndexMap<String, serde_json::Value>,
    permutations: usize,
    yield_logprobs: bool,
    rng: &mut impl Rng,
) -> (String, Option<Vec<Logprob>>) {
    match serde_json::from_value::<super::json_schema::JsonSchema>(
        serde_json::Value::Object(
            schema.iter().map(|(k, v)| (k.clone(), v.clone())).collect(),
        ),
    ) {
        Ok(js) => {
            let (text, logprobs) = js.generate_content_from_rng(rng, permutations);
            (text, if yield_logprobs { Some(logprobs) } else { None })
        }
        Err(_) => ("{}".into(), None),
    }
}

/// Generates a random alphanumeric string (with spaces) of length between `min` and `max`.
fn random_string(rng: &mut impl Rng, min: usize, max: usize) -> String {
    let len = rng.random_range(min..=max);
    (0..len)
        .map(|_| {
            const CHARS: &[u8] =
                b"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 ";
            CHARS[rng.random_range(0..CHARS.len())] as char
        })
        .collect()
}

/// Generates tool call arguments by parsing the tool's parameter schema as JsonSchema.
/// Tool calls never include logprobs.
fn generate_tool_arguments(
    tool_map: &HashMap<String, ResolvedTool>,
    tool_name: &str,
    rng: &mut impl Rng,
) -> String {
    let schema_value = match tool_map.get(tool_name) {
        Some(ResolvedTool::Mcp { tool, .. }) => {
            let mut map = serde_json::Map::new();
            map.insert("type".into(), serde_json::json!("object"));
            if let Some(props) = &tool.input_schema.properties {
                map.insert(
                    "properties".into(),
                    serde_json::Value::Object(
                        props.iter().map(|(k, v)| (k.clone(), v.clone())).collect(),
                    ),
                );
            }
            Some(serde_json::Value::Object(map))
        }
        Some(ResolvedTool::InventionTool(inv)) => {
            Some(serde_json::Value::Object(
                inv.parameters.iter().map(|(k, v)| (k.clone(), v.clone())).collect(),
            ))
        }
        Some(ResolvedTool::ResponseFormat { schema, .. }) => {
            Some(serde_json::Value::Object(
                schema.iter().map(|(k, v)| (k.clone(), v.clone())).collect(),
            ))
        }
        None => None,
    };

    match schema_value {
        Some(sv) => {
            match serde_json::from_value::<super::json_schema::JsonSchema>(sv) {
                Ok(js) => js.generate_content_from_rng(rng, 1).0,
                Err(_) => "{}".into(),
            }
        }
        None => "{}".into(),
    }
}
