# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_reasoning_effort_variant1():
    from objectiveai.agent.openrouter import ReasoningEffortVariant1
    schema = ReasoningEffortVariant1.model_json_schema()
