# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_reasoning_summary_verbosity_variant2():
    from objectiveai.agent.openrouter import ReasoningSummaryVerbosityVariant2
    schema = ReasoningSummaryVerbosityVariant2.model_json_schema()
