# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_provider_quantization_variant3():
    from objectiveai.agent.openrouter import ProviderQuantizationVariant3
    schema = ProviderQuantizationVariant3.model_json_schema()
