# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_reasoning_effort_variant4():
    from objectiveai.agent.openrouter import ReasoningEffortVariant4
    schema = ReasoningEffortVariant4.model_json_schema()
