# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_provider_quantization():
    from objectiveai.agent.openrouter import ProviderQuantization
    schema = ProviderQuantization.model_json_schema()
