# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_reasoning_summary_verbosity_variant1():
    from objectiveai.agent.openrouter import ReasoningSummaryVerbosityVariant1
    schema = ReasoningSummaryVerbosityVariant1.model_json_schema()
