use crate::tests::stream_push::stream_push_test;
use super::*;

stream_push_test!(
    single_chunk_unchanged,
    vec![FunctionExecutionChunk {
        id: "fec-1".into(),
        tasks: vec![],
        tasks_errors: None,
        reasoning: None,
        output: None,
        error: None,
        retry_token: None,
        created: 100,
        function: None,
        profile: None,
        object: Object::ScalarFunctionExecutionChunk,
        usage: None,
    }],
    FunctionExecutionChunk {
        id: "fec-1".into(),
        tasks: vec![],
        tasks_errors: None,
        reasoning: None,
        output: None,
        error: None,
        retry_token: None,
        created: 100,
        function: None,
        profile: None,
        object: Object::ScalarFunctionExecutionChunk,
        usage: None,
    }
);

stream_push_test!(
    output_set_from_later_chunk,
    vec![
        FunctionExecutionChunk {
            id: "fec-2".into(),
            tasks: vec![],
            tasks_errors: None,
            reasoning: None,
            output: None,
            error: None,
            retry_token: None,
            created: 100,
            function: None,
            profile: None,
            object: Object::ScalarFunctionExecutionChunk,
            usage: None,
        },
        FunctionExecutionChunk {
            id: "fec-2".into(),
            tasks: vec![],
            tasks_errors: None,
            reasoning: None,
            output: Some(super::super::Output { output: crate::functions::expression::TaskOutputOwned::Scalar(
                rust_decimal::Decimal::new(75, 2),
            ) }),
            error: None,
            retry_token: None,
            created: 100,
            function: None,
            profile: None,
            object: Object::ScalarFunctionExecutionChunk,
            usage: None,
        },
    ],
    FunctionExecutionChunk {
        id: "fec-2".into(),
        tasks: vec![],
        tasks_errors: None,
        reasoning: None,
        output: Some(super::super::Output { output: crate::functions::expression::TaskOutputOwned::Scalar(
            rust_decimal::Decimal::new(75, 2),
        ) }),
        error: None,
        retry_token: None,
        created: 100,
        function: None,
        profile: None,
        object: Object::ScalarFunctionExecutionChunk,
        usage: None,
    }
);

stream_push_test!(
    output_replaced_by_later_chunk,
    vec![
        FunctionExecutionChunk {
            id: "fec-3".into(),
            tasks: vec![],
            tasks_errors: None,
            reasoning: None,
            output: Some(super::super::Output { output: crate::functions::expression::TaskOutputOwned::Scalar(
                rust_decimal::Decimal::new(25, 2),
            ) }),
            error: None,
            retry_token: None,
            created: 100,
            function: None,
            profile: None,
            object: Object::ScalarFunctionExecutionChunk,
            usage: None,
        },
        FunctionExecutionChunk {
            id: "fec-3".into(),
            tasks: vec![],
            tasks_errors: None,
            reasoning: None,
            output: Some(super::super::Output { output: crate::functions::expression::TaskOutputOwned::Scalar(
                rust_decimal::Decimal::new(75, 2),
            ) }),
            error: None,
            retry_token: None,
            created: 100,
            function: None,
            profile: None,
            object: Object::ScalarFunctionExecutionChunk,
            usage: None,
        },
    ],
    FunctionExecutionChunk {
        id: "fec-3".into(),
        tasks: vec![],
        tasks_errors: None,
        reasoning: None,
        output: Some(super::super::Output { output: crate::functions::expression::TaskOutputOwned::Scalar(
            rust_decimal::Decimal::new(75, 2),
        ) }),
        error: None,
        retry_token: None,
        created: 100,
        function: None,
        profile: None,
        object: Object::ScalarFunctionExecutionChunk,
        usage: None,
    }
);

stream_push_test!(
    usage_set_from_later_chunk,
    vec![
        FunctionExecutionChunk {
            id: "fec-4".into(),
            tasks: vec![],
            tasks_errors: None,
            reasoning: None,
            output: None,
            error: None,
            retry_token: None,
            created: 100,
            function: None,
            profile: None,
            object: Object::ScalarFunctionExecutionChunk,
            usage: None,
        },
        FunctionExecutionChunk {
            id: "fec-4".into(),
            tasks: vec![],
            tasks_errors: None,
            reasoning: None,
            output: None,
            error: None,
            retry_token: None,
            created: 100,
            function: None,
            profile: None,
            object: Object::ScalarFunctionExecutionChunk,
            usage: Some(crate::agent::completions::response::Usage {
                prompt_tokens: 10,
                completion_tokens: 5,
                total_tokens: 15,
                completion_tokens_details: None,
                prompt_tokens_details: None,
                cost: rust_decimal::Decimal::ZERO,
                cost_details: None,
                total_cost: rust_decimal::Decimal::ZERO,
            }),
        },
    ],
    FunctionExecutionChunk {
        id: "fec-4".into(),
        tasks: vec![],
        tasks_errors: None,
        reasoning: None,
        output: None,
        error: None,
        retry_token: None,
        created: 100,
        function: None,
        profile: None,
        object: Object::ScalarFunctionExecutionChunk,
        usage: Some(crate::agent::completions::response::Usage {
            prompt_tokens: 10,
            completion_tokens: 5,
            total_tokens: 15,
            completion_tokens_details: None,
            prompt_tokens_details: None,
            cost: rust_decimal::Decimal::ZERO,
            cost_details: None,
            total_cost: rust_decimal::Decimal::ZERO,
        }),
    }
);

stream_push_test!(
    error_replaced_by_later_chunk,
    vec![
        FunctionExecutionChunk {
            id: "fec-5".into(),
            tasks: vec![],
            tasks_errors: None,
            reasoning: None,
            output: None,
            error: Some(crate::error::ResponseError {
                code: 500,
                message: serde_json::json!("first"),
            }),
            retry_token: None,
            created: 100,
            function: None,
            profile: None,
            object: Object::ScalarFunctionExecutionChunk,
            usage: None,
        },
        FunctionExecutionChunk {
            id: "fec-5".into(),
            tasks: vec![],
            tasks_errors: None,
            reasoning: None,
            output: None,
            error: Some(crate::error::ResponseError {
                code: 502,
                message: serde_json::json!("second"),
            }),
            retry_token: None,
            created: 100,
            function: None,
            profile: None,
            object: Object::ScalarFunctionExecutionChunk,
            usage: None,
        },
    ],
    FunctionExecutionChunk {
        id: "fec-5".into(),
        tasks: vec![],
        tasks_errors: None,
        reasoning: None,
        output: None,
        error: Some(crate::error::ResponseError {
            code: 502,
            message: serde_json::json!("second"),
        }),
        retry_token: None,
        created: 100,
        function: None,
        profile: None,
        object: Object::ScalarFunctionExecutionChunk,
        usage: None,
    }
);
