// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package profiles

type ListProfile struct {
	Data []any `json:"data" items_ref:"functions.profiles.ListProfileItem"`
}

func (ListProfile) SchemaTitle() string { return "functions.profiles.ListProfile" }
func (ListProfile) SchemaDescription() string { return "Response from listing profiles." }
func (ListProfile) FieldDescriptions() map[string]string {
	return map[string]string{
		"data": "List of available profiles.",
	}
}
