// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package profiles

type ListProfile struct {
	Data []any `json:"data"`
}

func (ListProfile) JSONSchema() map[string]any {
	return map[string]any{
		"title": "functions.profiles.ListProfile",
		"description": "Response from listing profiles.",
		"type": "object",
		"properties": map[string]any{
			"data": map[string]any{
			"description": "List of available profiles.",
			"type": "array",
			"items": map[string]any{"$ref": "functions.profiles.ListProfileItem"},
		},
		},
	}
}
