# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_create_open_router_byok_api_key_request():
    from objectiveai.auth import CreateOpenRouterByokApiKeyRequest
    schema = CreateOpenRouterByokApiKeyRequest.model_json_schema()
