// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package unary

type AgentCompletion struct {
	Created uint64 `json:"created" min:"0" max:"18446744073709551615"`
	Error any `json:"error,omitempty" nullable:"true" ref:"ResponseError"`
	ID string `json:"id"`
	Index uint64 `json:"index" min:"0" max:"18446744073709551615"`
	Messages []any `json:"messages" items_ref:"agent.completions.response.unary.Message"`
	Object any `json:"object" ref:"agent.completions.response.unary.Object"`
	Upstream any `json:"upstream" ref:"agent.Upstream"`
	Usage any `json:"usage" ref:"agent.completions.response.Usage"`
}

func (AgentCompletion) SchemaTitle() string { return "vector.completions.response.unary.AgentCompletion" }
func (AgentCompletion) SchemaDescription() string { return "A agent completion from a single agent within a vector completion.\n\nWraps the standard agent completion response with an index to identify\nwhich agent in the ensemble produced it." }
func (AgentCompletion) FieldDescriptions() map[string]string {
	return map[string]string{
		"error": "Error details if this completion failed.",
		"index": "Index of this completion within the vector completion.",
		"object": "The object type (always \"agent.completion\").",
		"upstream": "Upstream provider",
	}
}
