// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const AgentCompletionsResponseFinishReasonSchema = z.union([z.literal("stop").describe("The model reached a natural stop point or stop sequence."), z.literal("length").describe("The model reached the maximum token limit."), z.literal("tool_calls").describe("The model decided to call one or more tools."), z.literal("content_filter").describe("The response was filtered due to content policy."), z.literal("error").describe("An error occurred during generation.")]).describe("The reason the model stopped generating.").meta({ title: "agent.completions.response.FinishReason" });
export type AgentCompletionsResponseFinishReason = z.infer<typeof AgentCompletionsResponseFinishReasonSchema>;
