// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package expression

type ArrayInputSchemaType = string

type ArrayInputSchemaTypeSchema struct{}

func (ArrayInputSchemaTypeSchema) JSONSchema() map[string]any {
	return map[string]any{
		"title": "functions.expression.ArrayInputSchemaType",
		"type": "string",
		"enum": []any{"array"},
	}
}
