// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package expression

type AudioInputSchema struct {
	Description *string `json:"description,omitempty"`
	Type any `json:"type"`
}

func (AudioInputSchema) JSONSchema() map[string]any {
	return map[string]any{
		"title": "functions.expression.AudioInputSchema",
		"description": "Schema for an audio input.",
		"type": "object",
		"properties": map[string]any{
			"description": map[string]any{
			"description": "Human-readable description of the expected audio.",
			"anyOf": []any{map[string]any{"type": "string"}, map[string]any{"type": "null"}},
		},
			"type": map[string]any{
			"$ref": "functions.expression.AudioInputSchemaType",
		},
		},
	}
}
