// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package expression

type ParamsOwned struct {
	Input any `json:"input" ref:"functions.expression.InputValue"`
	Map *uint64 `json:"map,omitempty" nullable:"true" min:"0" max:"18446744073709551615"`
	Output any `json:"output,omitempty" nullable:"true" ref:"functions.expression.TaskOutputOwned"`
}

func (ParamsOwned) SchemaTitle() string { return "functions.expression.ParamsOwned" }
func (ParamsOwned) SchemaDescription() string { return "Owned version of expression parameters." }
func (ParamsOwned) FieldDescriptions() map[string]string {
	return map[string]string{
		"input": "The function's input data.",
		"map": "Current map index. Only populated for mapped task expressions.",
		"output": "Results from executed tasks. Only populated for task output expressions.",
	}
}
