// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package expression

type Special interface {
	isSpecial()
}

type SpecialVariant1 struct{}

func (SpecialVariant1) isSpecial() {}

type SpecialVariant2 struct{}

func (SpecialVariant2) isSpecial() {}

type SpecialVariant3 struct{}

func (SpecialVariant3) isSpecial() {}

type SpecialVariant4 struct{}

func (SpecialVariant4) isSpecial() {}

type SpecialVariant5 struct{}

func (SpecialVariant5) isSpecial() {}

type SpecialVariant6 struct{}

func (SpecialVariant6) isSpecial() {}

type SpecialVariant7 struct{}

func (SpecialVariant7) isSpecial() {}

type SpecialSchema struct{}

func (SpecialSchema) SchemaTitle() string { return "functions.expression.Special" }
func (SpecialSchema) SchemaDescription() string { return "Predefined expression behaviors that require no user-authored code." }
func (SpecialSchema) Body() map[string]any {
	return map[string]any{
		"anyOf": []any{
			map[string]any{
			"description": "Returns the params input as-is.",
			"type": "string",
			"enum": []any{"input"},
		},
			map[string]any{
			"description": "Returns the params output as-is.",
			"type": "string",
			"enum": []any{"output"},
		},
			map[string]any{
			"description": "L1-normalizes the output. Scalar/Err pass through.\nVector: L1 normalize. Vectors: L1 normalize each.",
			"type": "string",
			"enum": []any{"task_output_l1_normalized"},
		},
			map[string]any{
			"description": "Weighted sum of the output. Vector → Scalar. Vectors → Vector.",
			"type": "string",
			"enum": []any{"task_output_weighted_sum"},
		},
			map[string]any{
			"description": "Returns the length of input['items'] as u64",
			"type": "string",
			"enum": []any{"input_items_output_length"},
		},
			map[string]any{
			"description": "Splits an input containing items and optionally context into multiple inputs",
			"type": "string",
			"enum": []any{"input_items_optional_context_split"},
		},
			map[string]any{
			"description": "Merges multiple inputs containing items and optionally context into a single input",
			"type": "string",
			"enum": []any{"input_items_optional_context_merge"},
		},
		},
	}
}
