// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package expression

type TaskOutput interface {
	isTaskOutput()
}

type TaskOutputVariant1 struct {
	Inner TaskOutputOwned
}

func (TaskOutputVariant1) isTaskOutput() {}

type TaskOutputVariant2 struct {
	Inner TaskOutputRef
}

func (TaskOutputVariant2) isTaskOutput() {}

type TaskOutputSchema struct{}

func (TaskOutputSchema) SchemaTitle() string { return "functions.expression.TaskOutput" }
func (TaskOutputSchema) SchemaDescription() string { return "Output from an executed task." }
func (TaskOutputSchema) Body() map[string]any {
	return map[string]any{
		"anyOf": []any{
			map[string]any{
			"description": "Owned version.",
			"$ref": "functions.expression.TaskOutputOwned",
		},
			map[string]any{
			"description": "Borrowed version.",
			"$ref": "functions.expression.TaskOutputRef",
		},
		},
	}
}
