// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package response

type ToolResponse struct {
	Content any `json:"content" ref:"agent.completions.message.RichContent"`
	Index uint64 `json:"index" min:"0" max:"18446744073709551615"`
	Role any `json:"role" ref:"agent.completions.response.ToolRole"`
	ToolCallID string `json:"tool_call_id"`
}

func (ToolResponse) SchemaTitle() string { return "agent.completions.response.ToolResponse" }
func (ToolResponse) SchemaDescription() string { return "A tool message containing the result of a tool call." }
func (ToolResponse) FieldDescriptions() map[string]string {
	return map[string]string{
		"content": "The content of the tool response.",
		"tool_call_id": "The ID of the tool call this message responds to.",
	}
}
