// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package response

import "encoding/json"

var _ json.Number // suppress unused import

type ToolResponse struct {
	Content any `json:"content"`
	Index uint64 `json:"index"`
	Role any `json:"role"`
	ToolCallID string `json:"tool_call_id"`
}

func (ToolResponse) JSONSchema() map[string]any {
	return map[string]any{
		"title": "agent.completions.response.ToolResponse",
		"description": "A tool message containing the result of a tool call.",
		"type": "object",
		"properties": map[string]any{
			"content": map[string]any{
			"description": "The content of the tool response.",
			"$ref": "agent.completions.message.RichContent",
		},
			"index": map[string]any{
			"type": "integer",
			"minimum": json.Number("0"),
			"maximum": json.Number("18446744073709551615"),
		},
			"role": map[string]any{
			"$ref": "agent.completions.response.ToolRole",
		},
			"tool_call_id": map[string]any{
			"description": "The ID of the tool call this message responds to.",
			"type": "string",
		},
		},
	}
}
