# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_ensemble_base_agents_item_variant3():
    from objectiveai.ensemble import EnsembleBaseAgentsItemVariant3
    schema = EnsembleBaseAgentsItemVariant3.model_json_schema()
