# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_ensemble_base():
    from objectiveai.ensemble import EnsembleBase
    schema = EnsembleBase.model_json_schema()
