# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional, Union
from pydantic import BaseModel
from objectiveai.agent.completions.message.assistant_tool_call import AgentCompletionsMessageAssistantToolCall
from objectiveai.agent.completions.message.rich_content import AgentCompletionsMessageRichContent
from objectiveai.agent.completions.response.assistant_role import AgentCompletionsResponseAssistantRole
from objectiveai.agent.completions.response.finish_reason import AgentCompletionsResponseFinishReason
from objectiveai.agent.completions.response.logprobs import AgentCompletionsResponseLogprobs
from objectiveai.agent.completions.response.upstream_usage import AgentCompletionsResponseUpstreamUsage


class AgentCompletionsResponseUnaryAssistantResponse(BaseModel):
    """An assistant response in a unary agent completion."""
    role: AgentCompletionsResponseAssistantRole
    index: int
    created: int
    agent: str
    model: str
    upstream_id: str
    reasoning: Optional[Union[str, None]] = None
    tool_calls: Optional[Union[list[AgentCompletionsMessageAssistantToolCall], None]] = None
    content: Optional[AgentCompletionsMessageRichContent] = None
    refusal: Optional[Union[str, None]] = None
    finish_reason: AgentCompletionsResponseFinishReason
    logprobs: Optional[AgentCompletionsResponseLogprobs] = None
    service_tier: Optional[Union[str, None]] = None
    system_fingerprint: Optional[Union[str, None]] = None
    provider: Optional[Union[str, None]] = None
    usage: AgentCompletionsResponseUpstreamUsage

