// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package openrouter

import "encoding/json"

var _ json.Number // suppress unused import

type AgentBase struct {
	FrequencyPenalty *float64 `json:"frequency_penalty,omitempty"`
	LogitBias map[string]int64 `json:"logit_bias,omitempty"`
	MaxCompletionTokens *uint64 `json:"max_completion_tokens,omitempty"`
	MaxTokens *uint64 `json:"max_tokens,omitempty"`
	MCPServers []any `json:"mcp_servers,omitempty"`
	MinP *float64 `json:"min_p,omitempty"`
	Model string `json:"model"`
	OutputMode any `json:"output_mode,omitempty"`
	PostSystemPrefixMessages []any `json:"post_system_prefix_messages,omitempty"`
	PrefixMessages []any `json:"prefix_messages,omitempty"`
	PresencePenalty *float64 `json:"presence_penalty,omitempty"`
	Provider any `json:"provider,omitempty"`
	Reasoning any `json:"reasoning,omitempty"`
	RepetitionPenalty *float64 `json:"repetition_penalty,omitempty"`
	Stop any `json:"stop,omitempty"`
	SuffixMessages []any `json:"suffix_messages,omitempty"`
	SyntheticReasoning *bool `json:"synthetic_reasoning,omitempty"`
	Temperature *float64 `json:"temperature,omitempty"`
	TopA *float64 `json:"top_a,omitempty"`
	TopK *uint64 `json:"top_k,omitempty"`
	TopLogprobs *uint64 `json:"top_logprobs,omitempty"`
	TopP *float64 `json:"top_p,omitempty"`
	Upstream any `json:"upstream"`
	Verbosity any `json:"verbosity,omitempty"`
}

func (AgentBase) JSONSchema() map[string]any {
	return map[string]any{
		"title": "agent.openrouter.AgentBase",
		"description": "The base configuration for an OpenRouter Agent (without computed ID).",
		"type": "object",
		"properties": map[string]any{
			"frequency_penalty": map[string]any{
			"description": "Penalizes tokens based on their frequency in the output so far (-2.0 to 2.0).",
			"anyOf": []any{map[string]any{"maximum": json.Number("3.4028234663852886e+38"), "minimum": json.Number("-3.4028234663852886e+38"), "type": "number"}, map[string]any{"type": "null"}},
		},
			"logit_bias": map[string]any{
			"description": "Token ID to bias mapping (-100 to 100). Positive values increase likelihood.",
			"anyOf": []any{map[string]any{"additionalProperties": map[string]any{"maximum": json.Number("9223372036854775807"), "minimum": json.Number("-9223372036854775808"), "type": "integer"}, "type": "object"}, map[string]any{"type": "null"}},
		},
			"max_completion_tokens": map[string]any{
			"description": "Maximum tokens in the completion.",
			"anyOf": []any{map[string]any{"maximum": json.Number("18446744073709551615"), "minimum": json.Number("0"), "type": "integer"}, map[string]any{"type": "null"}},
		},
			"max_tokens": map[string]any{
			"description": "Maximum tokens (OpenRouter variant of max_completion_tokens).",
			"anyOf": []any{map[string]any{"maximum": json.Number("18446744073709551615"), "minimum": json.Number("0"), "type": "integer"}, map[string]any{"type": "null"}},
		},
			"mcp_servers": map[string]any{
			"description": "MCP servers the agent can connect to.",
			"anyOf": []any{map[string]any{"items": map[string]any{"$ref": "agent.McpServer"}, "type": "array"}, map[string]any{"type": "null"}},
		},
			"min_p": map[string]any{
			"description": "Minimum probability threshold for sampling (0.0 to 1.0).",
			"anyOf": []any{map[string]any{"maximum": json.Number("3.4028234663852886e+38"), "minimum": json.Number("-3.4028234663852886e+38"), "type": "number"}, map[string]any{"type": "null"}},
		},
			"model": map[string]any{
			"description": "The upstream language model identifier (e.g., `\"gpt-4\"`, `\"claude-3-opus\"`).",
			"type": "string",
		},
			"output_mode": map[string]any{
			"description": "The output mode for vector completions. Ignored for agent completions.",
			"$ref": "agent.openrouter.OutputMode",
			"default": "instruction",
		},
			"post_system_prefix_messages": map[string]any{
			"description": "Messages inserted after the leading chain of system/developer messages.",
			"anyOf": []any{map[string]any{"items": map[string]any{"$ref": "agent.completions.message.Message"}, "type": "array"}, map[string]any{"type": "null"}},
		},
			"prefix_messages": map[string]any{
			"description": "Messages prepended to the user's prompt.",
			"anyOf": []any{map[string]any{"items": map[string]any{"$ref": "agent.completions.message.Message"}, "type": "array"}, map[string]any{"type": "null"}},
		},
			"presence_penalty": map[string]any{
			"description": "Penalizes tokens based on their presence in the output so far (-2.0 to 2.0).",
			"anyOf": []any{map[string]any{"maximum": json.Number("3.4028234663852886e+38"), "minimum": json.Number("-3.4028234663852886e+38"), "type": "number"}, map[string]any{"type": "null"}},
		},
			"provider": map[string]any{
			"description": "Provider routing preferences.",
			"anyOf": []any{map[string]any{"$ref": "agent.openrouter.Provider"}, map[string]any{"type": "null"}},
		},
			"reasoning": map[string]any{
			"description": "Reasoning/thinking configuration for supported models.",
			"anyOf": []any{map[string]any{"$ref": "agent.openrouter.Reasoning"}, map[string]any{"type": "null"}},
		},
			"repetition_penalty": map[string]any{
			"description": "Repetition penalty (0.0 to 2.0). Values > 1.0 penalize repetition.",
			"anyOf": []any{map[string]any{"maximum": json.Number("3.4028234663852886e+38"), "minimum": json.Number("-3.4028234663852886e+38"), "type": "number"}, map[string]any{"type": "null"}},
		},
			"stop": map[string]any{
			"description": "Stop sequences that halt generation.",
			"anyOf": []any{map[string]any{"$ref": "agent.openrouter.Stop"}, map[string]any{"type": "null"}},
		},
			"suffix_messages": map[string]any{
			"description": "Messages appended after the user's prompt.",
			"anyOf": []any{map[string]any{"items": map[string]any{"$ref": "agent.completions.message.Message"}, "type": "array"}, map[string]any{"type": "null"}},
		},
			"synthetic_reasoning": map[string]any{
			"description": "Enable synthetic reasoning for non-reasoning LLMs.\n\n**Vector completions only.** Ignored for agent completions.",
			"anyOf": []any{map[string]any{"type": "boolean"}, map[string]any{"type": "null"}},
		},
			"temperature": map[string]any{
			"description": "Sampling temperature (0.0 to 2.0). Higher = more random.",
			"anyOf": []any{map[string]any{"maximum": json.Number("3.4028234663852886e+38"), "minimum": json.Number("-3.4028234663852886e+38"), "type": "number"}, map[string]any{"type": "null"}},
		},
			"top_a": map[string]any{
			"description": "Top-a sampling parameter (0.0 to 1.0).",
			"anyOf": []any{map[string]any{"maximum": json.Number("3.4028234663852886e+38"), "minimum": json.Number("-3.4028234663852886e+38"), "type": "number"}, map[string]any{"type": "null"}},
		},
			"top_k": map[string]any{
			"description": "Top-k sampling: only consider the k most likely tokens.",
			"anyOf": []any{map[string]any{"maximum": json.Number("18446744073709551615"), "minimum": json.Number("0"), "type": "integer"}, map[string]any{"type": "null"}},
		},
			"top_logprobs": map[string]any{
			"description": "Number of top log probabilities to return (2-20).\n\n**Vector completions only.** Ignored for agent completions.",
			"anyOf": []any{map[string]any{"maximum": json.Number("18446744073709551615"), "minimum": json.Number("0"), "type": "integer"}, map[string]any{"type": "null"}},
		},
			"top_p": map[string]any{
			"description": "Nucleus sampling probability (0.0 to 1.0).",
			"anyOf": []any{map[string]any{"maximum": json.Number("3.4028234663852886e+38"), "minimum": json.Number("-3.4028234663852886e+38"), "type": "number"}, map[string]any{"type": "null"}},
		},
			"upstream": map[string]any{
			"description": "The upstream provider marker.",
			"$ref": "agent.openrouter.Upstream",
		},
			"verbosity": map[string]any{
			"description": "Output verbosity hint for supported models.",
			"anyOf": []any{map[string]any{"$ref": "agent.openrouter.Verbosity"}, map[string]any{"type": "null"}},
		},
		},
	}
}
