// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { FunctionsExpressionAnyOfInputSchemaSchema, type FunctionsExpressionAnyOfInputSchema } from "./anyOfInputSchema";
import { FunctionsExpressionArrayInputSchemaSchema, type FunctionsExpressionArrayInputSchema } from "./arrayInputSchema";
import { FunctionsExpressionAudioInputSchemaSchema, type FunctionsExpressionAudioInputSchema } from "./audioInputSchema";
import { FunctionsExpressionBooleanInputSchemaSchema, type FunctionsExpressionBooleanInputSchema } from "./booleanInputSchema";
import { FunctionsExpressionFileInputSchemaSchema, type FunctionsExpressionFileInputSchema } from "./fileInputSchema";
import { FunctionsExpressionImageInputSchemaSchema, type FunctionsExpressionImageInputSchema } from "./imageInputSchema";
import { FunctionsExpressionIntegerInputSchemaSchema, type FunctionsExpressionIntegerInputSchema } from "./integerInputSchema";
import { FunctionsExpressionNumberInputSchemaSchema, type FunctionsExpressionNumberInputSchema } from "./numberInputSchema";
import { FunctionsExpressionObjectInputSchemaSchema, type FunctionsExpressionObjectInputSchema } from "./objectInputSchema";
import { FunctionsExpressionStringInputSchemaSchema, type FunctionsExpressionStringInputSchema } from "./stringInputSchema";
import { FunctionsExpressionVideoInputSchemaSchema, type FunctionsExpressionVideoInputSchema } from "./videoInputSchema";

export type FunctionsExpressionInputSchema = {
  Object: FunctionsExpressionObjectInputSchema;
} | {
  Array: FunctionsExpressionArrayInputSchema;
} | {
  String: FunctionsExpressionStringInputSchema;
} | {
  Integer: FunctionsExpressionIntegerInputSchema;
} | {
  Number: FunctionsExpressionNumberInputSchema;
} | {
  Boolean: FunctionsExpressionBooleanInputSchema;
} | {
  Image: FunctionsExpressionImageInputSchema;
} | {
  Audio: FunctionsExpressionAudioInputSchema;
} | {
  Video: FunctionsExpressionVideoInputSchema;
} | {
  File: FunctionsExpressionFileInputSchema;
} | {
  AnyOf: FunctionsExpressionAnyOfInputSchema;
};
export const FunctionsExpressionInputSchemaSchema: z.ZodType<FunctionsExpressionInputSchema> = z.union([z.object({
  Object: z.lazy(() => FunctionsExpressionObjectInputSchemaSchema),
}).strict().describe("An object with named properties."), z.object({
  Array: FunctionsExpressionArrayInputSchemaSchema,
}).strict().describe("An array of items."), z.object({
  String: FunctionsExpressionStringInputSchemaSchema,
}).strict().describe("A string value."), z.object({
  Integer: FunctionsExpressionIntegerInputSchemaSchema,
}).strict().describe("An integer value."), z.object({
  Number: FunctionsExpressionNumberInputSchemaSchema,
}).strict().describe("A floating-point number."), z.object({
  Boolean: FunctionsExpressionBooleanInputSchemaSchema,
}).strict().describe("A boolean value."), z.object({
  Image: FunctionsExpressionImageInputSchemaSchema,
}).strict().describe("An image (URL or base64)."), z.object({
  Audio: FunctionsExpressionAudioInputSchemaSchema,
}).strict().describe("Audio content."), z.object({
  Video: FunctionsExpressionVideoInputSchemaSchema,
}).strict().describe("Video content."), z.object({
  File: FunctionsExpressionFileInputSchemaSchema,
}).strict().describe("A file."), z.object({
  AnyOf: FunctionsExpressionAnyOfInputSchemaSchema,
}).strict().describe("A union of schemas - input must match at least one.")]).describe("Schema for validating Function input.\n\nDefines the expected structure and constraints for input data.\nUsed by remote Functions to document and validate their inputs.").meta({ title: "functions.expression.InputSchema" });
