import { z } from "zod";
import { AgentCompletionsMessageAssistantToolCallExpressionSchema } from "../../agent/completions/message/assistantToolCallExpression";
import { AgentCompletionsMessageAssistantToolCallFunctionExpressionSchema } from "../../agent/completions/message/assistantToolCallFunctionExpression";
import { AgentCompletionsMessageFileSchema } from "../../agent/completions/message/file";
import { AgentCompletionsMessageImageUrlSchema } from "../../agent/completions/message/imageUrl";
import { AgentCompletionsMessageInputAudioSchema } from "../../agent/completions/message/inputAudio";
import { AgentCompletionsMessageMessageExpressionSchema } from "../../agent/completions/message/messageExpression";
import { AgentCompletionsMessageRichContentExpressionSchema } from "../../agent/completions/message/richContentExpression";
import { AgentCompletionsMessageRichContentPartExpressionSchema } from "../../agent/completions/message/richContentPartExpression";
import { AgentCompletionsMessageSimpleContentExpressionSchema } from "../../agent/completions/message/simpleContentExpression";
import { AgentCompletionsMessageSimpleContentPartExpressionSchema } from "../../agent/completions/message/simpleContentPartExpression";
import { AgentCompletionsMessageVideoUrlSchema } from "../../agent/completions/message/videoUrl";
import { FunctionsExpressionExpressionSchema } from "./expression";
import { FunctionsExpressionInputExpressionSchema } from "./inputExpression";

export const FunctionsExpressionWithExpressionAgentCompletionsMessageAssistantToolCallExpressionSchema = z.union([FunctionsExpressionExpressionSchema.describe("An expression (JMESPath or Starlark) to evaluate."), AgentCompletionsMessageAssistantToolCallExpressionSchema.describe("A literal value.")]).describe("A value that can be either a literal or an expression.\n\nThis allows Function definitions to mix static values with dynamic\nexpressions. During compilation, expressions are evaluated while\nliteral values pass through unchanged.\n\n# Example\n\nLiteral value:\n```json\n\"hello world\"\n```\n\nJMESPath expression:\n```json\n{\"$jmespath\": \"input.greeting\"}\n```\n\nStarlark expression:\n```json\n{\"$starlark\": \"input['greeting']\"}\n```").meta({ title: "functions.expression.WithExpression.agent.completions.message.AssistantToolCallExpression" });
export type FunctionsExpressionWithExpressionAgentCompletionsMessageAssistantToolCallExpression = z.infer<typeof FunctionsExpressionWithExpressionAgentCompletionsMessageAssistantToolCallExpressionSchema>;

export const FunctionsExpressionWithExpressionAgentCompletionsMessageAssistantToolCallFunctionExpressionSchema = z.union([FunctionsExpressionExpressionSchema.describe("An expression (JMESPath or Starlark) to evaluate."), AgentCompletionsMessageAssistantToolCallFunctionExpressionSchema.describe("A literal value.")]).describe("A value that can be either a literal or an expression.\n\nThis allows Function definitions to mix static values with dynamic\nexpressions. During compilation, expressions are evaluated while\nliteral values pass through unchanged.\n\n# Example\n\nLiteral value:\n```json\n\"hello world\"\n```\n\nJMESPath expression:\n```json\n{\"$jmespath\": \"input.greeting\"}\n```\n\nStarlark expression:\n```json\n{\"$starlark\": \"input['greeting']\"}\n```").meta({ title: "functions.expression.WithExpression.agent.completions.message.AssistantToolCallFunctionExpression" });
export type FunctionsExpressionWithExpressionAgentCompletionsMessageAssistantToolCallFunctionExpression = z.infer<typeof FunctionsExpressionWithExpressionAgentCompletionsMessageAssistantToolCallFunctionExpressionSchema>;

export const FunctionsExpressionWithExpressionAgentCompletionsMessageFileSchema = z.union([FunctionsExpressionExpressionSchema.describe("An expression (JMESPath or Starlark) to evaluate."), AgentCompletionsMessageFileSchema.describe("A literal value.")]).describe("A value that can be either a literal or an expression.\n\nThis allows Function definitions to mix static values with dynamic\nexpressions. During compilation, expressions are evaluated while\nliteral values pass through unchanged.\n\n# Example\n\nLiteral value:\n```json\n\"hello world\"\n```\n\nJMESPath expression:\n```json\n{\"$jmespath\": \"input.greeting\"}\n```\n\nStarlark expression:\n```json\n{\"$starlark\": \"input['greeting']\"}\n```").meta({ title: "functions.expression.WithExpression.agent.completions.message.File" });
export type FunctionsExpressionWithExpressionAgentCompletionsMessageFile = z.infer<typeof FunctionsExpressionWithExpressionAgentCompletionsMessageFileSchema>;

export const FunctionsExpressionWithExpressionAgentCompletionsMessageImageUrlSchema = z.union([FunctionsExpressionExpressionSchema.describe("An expression (JMESPath or Starlark) to evaluate."), AgentCompletionsMessageImageUrlSchema.describe("A literal value.")]).describe("A value that can be either a literal or an expression.\n\nThis allows Function definitions to mix static values with dynamic\nexpressions. During compilation, expressions are evaluated while\nliteral values pass through unchanged.\n\n# Example\n\nLiteral value:\n```json\n\"hello world\"\n```\n\nJMESPath expression:\n```json\n{\"$jmespath\": \"input.greeting\"}\n```\n\nStarlark expression:\n```json\n{\"$starlark\": \"input['greeting']\"}\n```").meta({ title: "functions.expression.WithExpression.agent.completions.message.ImageUrl" });
export type FunctionsExpressionWithExpressionAgentCompletionsMessageImageUrl = z.infer<typeof FunctionsExpressionWithExpressionAgentCompletionsMessageImageUrlSchema>;

export const FunctionsExpressionWithExpressionAgentCompletionsMessageInputAudioSchema = z.union([FunctionsExpressionExpressionSchema.describe("An expression (JMESPath or Starlark) to evaluate."), AgentCompletionsMessageInputAudioSchema.describe("A literal value.")]).describe("A value that can be either a literal or an expression.\n\nThis allows Function definitions to mix static values with dynamic\nexpressions. During compilation, expressions are evaluated while\nliteral values pass through unchanged.\n\n# Example\n\nLiteral value:\n```json\n\"hello world\"\n```\n\nJMESPath expression:\n```json\n{\"$jmespath\": \"input.greeting\"}\n```\n\nStarlark expression:\n```json\n{\"$starlark\": \"input['greeting']\"}\n```").meta({ title: "functions.expression.WithExpression.agent.completions.message.InputAudio" });
export type FunctionsExpressionWithExpressionAgentCompletionsMessageInputAudio = z.infer<typeof FunctionsExpressionWithExpressionAgentCompletionsMessageInputAudioSchema>;

export const FunctionsExpressionWithExpressionAgentCompletionsMessageMessageExpressionSchema = z.union([FunctionsExpressionExpressionSchema.describe("An expression (JMESPath or Starlark) to evaluate."), AgentCompletionsMessageMessageExpressionSchema.describe("A literal value.")]).describe("A value that can be either a literal or an expression.\n\nThis allows Function definitions to mix static values with dynamic\nexpressions. During compilation, expressions are evaluated while\nliteral values pass through unchanged.\n\n# Example\n\nLiteral value:\n```json\n\"hello world\"\n```\n\nJMESPath expression:\n```json\n{\"$jmespath\": \"input.greeting\"}\n```\n\nStarlark expression:\n```json\n{\"$starlark\": \"input['greeting']\"}\n```").meta({ title: "functions.expression.WithExpression.agent.completions.message.MessageExpression" });
export type FunctionsExpressionWithExpressionAgentCompletionsMessageMessageExpression = z.infer<typeof FunctionsExpressionWithExpressionAgentCompletionsMessageMessageExpressionSchema>;

export const FunctionsExpressionWithExpressionAgentCompletionsMessageRichContentExpressionSchema = z.union([FunctionsExpressionExpressionSchema.describe("An expression (JMESPath or Starlark) to evaluate."), AgentCompletionsMessageRichContentExpressionSchema.describe("A literal value.")]).describe("A value that can be either a literal or an expression.\n\nThis allows Function definitions to mix static values with dynamic\nexpressions. During compilation, expressions are evaluated while\nliteral values pass through unchanged.\n\n# Example\n\nLiteral value:\n```json\n\"hello world\"\n```\n\nJMESPath expression:\n```json\n{\"$jmespath\": \"input.greeting\"}\n```\n\nStarlark expression:\n```json\n{\"$starlark\": \"input['greeting']\"}\n```").meta({ title: "functions.expression.WithExpression.agent.completions.message.RichContentExpression" });
export type FunctionsExpressionWithExpressionAgentCompletionsMessageRichContentExpression = z.infer<typeof FunctionsExpressionWithExpressionAgentCompletionsMessageRichContentExpressionSchema>;

export const FunctionsExpressionWithExpressionAgentCompletionsMessageRichContentPartExpressionSchema = z.union([FunctionsExpressionExpressionSchema.describe("An expression (JMESPath or Starlark) to evaluate."), AgentCompletionsMessageRichContentPartExpressionSchema.describe("A literal value.")]).describe("A value that can be either a literal or an expression.\n\nThis allows Function definitions to mix static values with dynamic\nexpressions. During compilation, expressions are evaluated while\nliteral values pass through unchanged.\n\n# Example\n\nLiteral value:\n```json\n\"hello world\"\n```\n\nJMESPath expression:\n```json\n{\"$jmespath\": \"input.greeting\"}\n```\n\nStarlark expression:\n```json\n{\"$starlark\": \"input['greeting']\"}\n```").meta({ title: "functions.expression.WithExpression.agent.completions.message.RichContentPartExpression" });
export type FunctionsExpressionWithExpressionAgentCompletionsMessageRichContentPartExpression = z.infer<typeof FunctionsExpressionWithExpressionAgentCompletionsMessageRichContentPartExpressionSchema>;

export const FunctionsExpressionWithExpressionAgentCompletionsMessageSimpleContentExpressionSchema = z.union([FunctionsExpressionExpressionSchema.describe("An expression (JMESPath or Starlark) to evaluate."), AgentCompletionsMessageSimpleContentExpressionSchema.describe("A literal value.")]).describe("A value that can be either a literal or an expression.\n\nThis allows Function definitions to mix static values with dynamic\nexpressions. During compilation, expressions are evaluated while\nliteral values pass through unchanged.\n\n# Example\n\nLiteral value:\n```json\n\"hello world\"\n```\n\nJMESPath expression:\n```json\n{\"$jmespath\": \"input.greeting\"}\n```\n\nStarlark expression:\n```json\n{\"$starlark\": \"input['greeting']\"}\n```").meta({ title: "functions.expression.WithExpression.agent.completions.message.SimpleContentExpression" });
export type FunctionsExpressionWithExpressionAgentCompletionsMessageSimpleContentExpression = z.infer<typeof FunctionsExpressionWithExpressionAgentCompletionsMessageSimpleContentExpressionSchema>;

export const FunctionsExpressionWithExpressionAgentCompletionsMessageSimpleContentPartExpressionSchema = z.union([FunctionsExpressionExpressionSchema.describe("An expression (JMESPath or Starlark) to evaluate."), AgentCompletionsMessageSimpleContentPartExpressionSchema.describe("A literal value.")]).describe("A value that can be either a literal or an expression.\n\nThis allows Function definitions to mix static values with dynamic\nexpressions. During compilation, expressions are evaluated while\nliteral values pass through unchanged.\n\n# Example\n\nLiteral value:\n```json\n\"hello world\"\n```\n\nJMESPath expression:\n```json\n{\"$jmespath\": \"input.greeting\"}\n```\n\nStarlark expression:\n```json\n{\"$starlark\": \"input['greeting']\"}\n```").meta({ title: "functions.expression.WithExpression.agent.completions.message.SimpleContentPartExpression" });
export type FunctionsExpressionWithExpressionAgentCompletionsMessageSimpleContentPartExpression = z.infer<typeof FunctionsExpressionWithExpressionAgentCompletionsMessageSimpleContentPartExpressionSchema>;

export const FunctionsExpressionWithExpressionAgentCompletionsMessageVideoUrlSchema = z.union([FunctionsExpressionExpressionSchema.describe("An expression (JMESPath or Starlark) to evaluate."), AgentCompletionsMessageVideoUrlSchema.describe("A literal value.")]).describe("A value that can be either a literal or an expression.\n\nThis allows Function definitions to mix static values with dynamic\nexpressions. During compilation, expressions are evaluated while\nliteral values pass through unchanged.\n\n# Example\n\nLiteral value:\n```json\n\"hello world\"\n```\n\nJMESPath expression:\n```json\n{\"$jmespath\": \"input.greeting\"}\n```\n\nStarlark expression:\n```json\n{\"$starlark\": \"input['greeting']\"}\n```").meta({ title: "functions.expression.WithExpression.agent.completions.message.VideoUrl" });
export type FunctionsExpressionWithExpressionAgentCompletionsMessageVideoUrl = z.infer<typeof FunctionsExpressionWithExpressionAgentCompletionsMessageVideoUrlSchema>;

export const FunctionsExpressionWithExpressionArrayOfFunctionsExpressionWithExpressionAgentCompletionsMessageMessageExpressionSchema = z.union([FunctionsExpressionExpressionSchema.describe("An expression (JMESPath or Starlark) to evaluate."), z.array(FunctionsExpressionWithExpressionAgentCompletionsMessageMessageExpressionSchema).describe("A literal value.")]).describe("A value that can be either a literal or an expression.\n\nThis allows Function definitions to mix static values with dynamic\nexpressions. During compilation, expressions are evaluated while\nliteral values pass through unchanged.\n\n# Example\n\nLiteral value:\n```json\n\"hello world\"\n```\n\nJMESPath expression:\n```json\n{\"$jmespath\": \"input.greeting\"}\n```\n\nStarlark expression:\n```json\n{\"$starlark\": \"input['greeting']\"}\n```").meta({ title: "functions.expression.WithExpression.Array_of_functions.expression.WithExpression.agent.completions.message.MessageExpression" });
export type FunctionsExpressionWithExpressionArrayOfFunctionsExpressionWithExpressionAgentCompletionsMessageMessageExpression = z.infer<typeof FunctionsExpressionWithExpressionArrayOfFunctionsExpressionWithExpressionAgentCompletionsMessageMessageExpressionSchema>;

export const FunctionsExpressionWithExpressionArrayOfFunctionsExpressionWithExpressionAgentCompletionsMessageRichContentExpressionSchema = z.union([FunctionsExpressionExpressionSchema.describe("An expression (JMESPath or Starlark) to evaluate."), z.array(FunctionsExpressionWithExpressionAgentCompletionsMessageRichContentExpressionSchema).describe("A literal value.")]).describe("A value that can be either a literal or an expression.\n\nThis allows Function definitions to mix static values with dynamic\nexpressions. During compilation, expressions are evaluated while\nliteral values pass through unchanged.\n\n# Example\n\nLiteral value:\n```json\n\"hello world\"\n```\n\nJMESPath expression:\n```json\n{\"$jmespath\": \"input.greeting\"}\n```\n\nStarlark expression:\n```json\n{\"$starlark\": \"input['greeting']\"}\n```").meta({ title: "functions.expression.WithExpression.Array_of_functions.expression.WithExpression.agent.completions.message.RichContentExpression" });
export type FunctionsExpressionWithExpressionArrayOfFunctionsExpressionWithExpressionAgentCompletionsMessageRichContentExpression = z.infer<typeof FunctionsExpressionWithExpressionArrayOfFunctionsExpressionWithExpressionAgentCompletionsMessageRichContentExpressionSchema>;

export const FunctionsExpressionWithExpressionFunctionsExpressionInputExpressionSchema = z.union([FunctionsExpressionExpressionSchema.describe("An expression (JMESPath or Starlark) to evaluate."), FunctionsExpressionInputExpressionSchema.describe("A literal value.")]).describe("A value that can be either a literal or an expression.\n\nThis allows Function definitions to mix static values with dynamic\nexpressions. During compilation, expressions are evaluated while\nliteral values pass through unchanged.\n\n# Example\n\nLiteral value:\n```json\n\"hello world\"\n```\n\nJMESPath expression:\n```json\n{\"$jmespath\": \"input.greeting\"}\n```\n\nStarlark expression:\n```json\n{\"$starlark\": \"input['greeting']\"}\n```").meta({ title: "functions.expression.WithExpression.functions.expression.InputExpression" });
export type FunctionsExpressionWithExpressionFunctionsExpressionInputExpression = z.infer<typeof FunctionsExpressionWithExpressionFunctionsExpressionInputExpressionSchema>;

export const FunctionsExpressionWithExpressionNullableAgentCompletionsMessageRichContentExpressionSchema = z.union([FunctionsExpressionExpressionSchema.describe("An expression (JMESPath or Starlark) to evaluate."), AgentCompletionsMessageRichContentExpressionSchema.nullable().describe("A literal value.")]).describe("A value that can be either a literal or an expression.\n\nThis allows Function definitions to mix static values with dynamic\nexpressions. During compilation, expressions are evaluated while\nliteral values pass through unchanged.\n\n# Example\n\nLiteral value:\n```json\n\"hello world\"\n```\n\nJMESPath expression:\n```json\n{\"$jmespath\": \"input.greeting\"}\n```\n\nStarlark expression:\n```json\n{\"$starlark\": \"input['greeting']\"}\n```").meta({ title: "functions.expression.WithExpression.Nullable_agent.completions.message.RichContentExpression" });
export type FunctionsExpressionWithExpressionNullableAgentCompletionsMessageRichContentExpression = z.infer<typeof FunctionsExpressionWithExpressionNullableAgentCompletionsMessageRichContentExpressionSchema>;

export const FunctionsExpressionWithExpressionNullableArrayOfFunctionsExpressionWithExpressionAgentCompletionsMessageAssistantToolCallExpressionSchema = z.union([FunctionsExpressionExpressionSchema.describe("An expression (JMESPath or Starlark) to evaluate."), z.array(FunctionsExpressionWithExpressionAgentCompletionsMessageAssistantToolCallExpressionSchema).nullable().describe("A literal value.")]).describe("A value that can be either a literal or an expression.\n\nThis allows Function definitions to mix static values with dynamic\nexpressions. During compilation, expressions are evaluated while\nliteral values pass through unchanged.\n\n# Example\n\nLiteral value:\n```json\n\"hello world\"\n```\n\nJMESPath expression:\n```json\n{\"$jmespath\": \"input.greeting\"}\n```\n\nStarlark expression:\n```json\n{\"$starlark\": \"input['greeting']\"}\n```").meta({ title: "functions.expression.WithExpression.Nullable_Array_of_functions.expression.WithExpression.agent.completions.message.AssistantToolCallExpression" });
export type FunctionsExpressionWithExpressionNullableArrayOfFunctionsExpressionWithExpressionAgentCompletionsMessageAssistantToolCallExpression = z.infer<typeof FunctionsExpressionWithExpressionNullableArrayOfFunctionsExpressionWithExpressionAgentCompletionsMessageAssistantToolCallExpressionSchema>;

export const FunctionsExpressionWithExpressionNullableStringSchema = z.union([FunctionsExpressionExpressionSchema.describe("An expression (JMESPath or Starlark) to evaluate."), z.string().nullable().describe("A literal value.")]).describe("A value that can be either a literal or an expression.\n\nThis allows Function definitions to mix static values with dynamic\nexpressions. During compilation, expressions are evaluated while\nliteral values pass through unchanged.\n\n# Example\n\nLiteral value:\n```json\n\"hello world\"\n```\n\nJMESPath expression:\n```json\n{\"$jmespath\": \"input.greeting\"}\n```\n\nStarlark expression:\n```json\n{\"$starlark\": \"input['greeting']\"}\n```").meta({ title: "functions.expression.WithExpression.Nullable_string" });
export type FunctionsExpressionWithExpressionNullableString = z.infer<typeof FunctionsExpressionWithExpressionNullableStringSchema>;

export const FunctionsExpressionWithExpressionStringSchema = z.union([FunctionsExpressionExpressionSchema.describe("An expression (JMESPath or Starlark) to evaluate."), z.string().describe("A literal value.")]).describe("A value that can be either a literal or an expression.\n\nThis allows Function definitions to mix static values with dynamic\nexpressions. During compilation, expressions are evaluated while\nliteral values pass through unchanged.\n\n# Example\n\nLiteral value:\n```json\n\"hello world\"\n```\n\nJMESPath expression:\n```json\n{\"$jmespath\": \"input.greeting\"}\n```\n\nStarlark expression:\n```json\n{\"$starlark\": \"input['greeting']\"}\n```").meta({ title: "functions.expression.WithExpression.string" });
export type FunctionsExpressionWithExpressionString = z.infer<typeof FunctionsExpressionWithExpressionStringSchema>;
