// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package functions

type CompiledTask interface {
	isCompiledTask()
}

type CompiledTaskVariant1 struct {
	Inner Task
}

func (CompiledTaskVariant1) isCompiledTask() {}

type CompiledTaskVariant2 struct {
	Inner []any
}

func (CompiledTaskVariant2) isCompiledTask() {}

type CompiledTaskSchema struct{}

func (CompiledTaskSchema) SchemaTitle() string { return "functions.CompiledTask" }
func (CompiledTaskSchema) SchemaDescription() string { return "The result of compiling a task expression.\n\nTasks without a `map` field compile to a single task. Tasks with a `map`\nexpression are expanded into multiple tasks, one per integer index from\n0 to the evaluated count." }
func (CompiledTaskSchema) Body() map[string]any {
	return map[string]any{
		"anyOf": []any{
			map[string]any{
			"description": "A single task (no mapping).",
			"$ref": "functions.Task",
		},
			map[string]any{
			"description": "Multiple task instances from mapped execution.",
			"type": "array",
			"items": map[string]any{"$ref": "functions.Task"},
		},
		},
	}
}
