// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package functions

type FullInlineFunction interface {
	isFullInlineFunction()
}

type FullInlineFunctionVariant1 struct {
	Inner AlphaInlineFunction
}

func (FullInlineFunctionVariant1) isFullInlineFunction() {}

type FullInlineFunctionVariant2 struct {
	Inner InlineFunction
}

func (FullInlineFunctionVariant2) isFullInlineFunction() {}

type FullInlineFunctionSchema struct{}

func (FullInlineFunctionSchema) SchemaTitle() string { return "functions.FullInlineFunction" }
func (FullInlineFunctionSchema) SchemaDescription() string { return "" }
func (FullInlineFunctionSchema) Body() map[string]any {
	return map[string]any{
		"anyOf": []any{
			map[string]any{
			"$ref": "functions.AlphaInlineFunction",
		},
			map[string]any{
			"$ref": "functions.InlineFunction",
		},
		},
	}
}
