// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package functions

type FullRemoteFunction interface {
	isFullRemoteFunction()
}

type FullRemoteFunctionVariant1 struct {
	Inner AlphaRemoteFunction
}

func (FullRemoteFunctionVariant1) isFullRemoteFunction() {}

type FullRemoteFunctionVariant2 struct {
	Inner RemoteFunction
}

func (FullRemoteFunctionVariant2) isFullRemoteFunction() {}

type FullRemoteFunctionSchema struct{}

func (FullRemoteFunctionSchema) SchemaTitle() string { return "functions.FullRemoteFunction" }
func (FullRemoteFunctionSchema) SchemaDescription() string { return "" }
func (FullRemoteFunctionSchema) Body() map[string]any {
	return map[string]any{
		"anyOf": []any{
			map[string]any{
			"$ref": "functions.AlphaRemoteFunction",
		},
			map[string]any{
			"$ref": "functions.RemoteFunction",
		},
		},
	}
}
