// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package functions

type GetFunctionProfilePair struct {
	Function any `json:"function" ref:"functions.GetFunction"`
	Profile any `json:"profile" ref:"functions.profiles.GetProfile"`
}

func (GetFunctionProfilePair) SchemaTitle() string { return "functions.GetFunctionProfilePair" }
func (GetFunctionProfilePair) SchemaDescription() string { return "Response from getting a function-profile pair." }
func (GetFunctionProfilePair) FieldDescriptions() map[string]string {
	return map[string]string{
		"function": "The function.",
		"profile": "The profile.",
	}
}
