// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package functions

type ListFunctionProfilePairsQueryParameters struct {
	Source any `json:"source,omitempty"`
}

func (ListFunctionProfilePairsQueryParameters) JSONSchema() map[string]any {
	return map[string]any{
		"title": "functions.ListFunctionProfilePairsQueryParameters",
		"description": "Query parameters for the list function-profile pairs endpoint.",
		"type": "object",
		"properties": map[string]any{
			"source": map[string]any{
			"description": "Optional source filter for listing function-profile pairs.",
			"anyOf": []any{map[string]any{"$ref": "functions.ListFunctionProfilePairsSource"}, map[string]any{"type": "null"}},
		},
		},
	}
}
