// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package functions

type ListFunction struct {
	Data []any `json:"data"`
}

func (ListFunction) JSONSchema() map[string]any {
	return map[string]any{
		"title": "functions.ListFunction",
		"description": "Response from listing functions.",
		"type": "object",
		"properties": map[string]any{
			"data": map[string]any{
			"description": "List of available functions.",
			"type": "array",
			"items": map[string]any{"$ref": "functions.ListFunctionItem"},
		},
		},
	}
}
