// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package functions

type PlaceholderVectorFunctionTask struct {
	Input any `json:"input"`
	InputMerge any `json:"input_merge"`
	InputSchema any `json:"input_schema"`
	InputSplit any `json:"input_split"`
	Output any `json:"output"`
	OutputLength any `json:"output_length"`
}

func (PlaceholderVectorFunctionTask) JSONSchema() map[string]any {
	return map[string]any{
		"title": "functions.PlaceholderVectorFunctionTask",
		"description": "A compiled placeholder vector function task.\n\nAlways produces `Vector(vec![1/N; output_length])` before\nthe output expression is applied.",
		"type": "object",
		"properties": map[string]any{
			"input": map[string]any{
			"description": "The resolved input.",
			"$ref": "functions.expression.InputValue",
		},
			"input_merge": map[string]any{
			"description": "Expression merging sub-inputs back into one input.",
			"$ref": "functions.expression.Expression",
		},
			"input_schema": map[string]any{
			"description": "JSON Schema defining the expected input structure.",
			"$ref": "functions.expression.InputSchema",
		},
			"input_split": map[string]any{
			"description": "Expression transforming input into sub-inputs for swiss system.",
			"$ref": "functions.expression.Expression",
		},
			"output": map[string]any{
			"description": "Expression to transform the equalized vector output.",
			"$ref": "functions.expression.Expression",
		},
			"output_length": map[string]any{
			"description": "Expression computing the expected output vector length.",
			"$ref": "functions.expression.Expression",
		},
		},
	}
}
