// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package functions

type RemoteAutoProfile struct {
	Description string `json:"description"`
	Ensemble any `json:"ensemble" ref:"vector.completions.request.Ensemble"`
	Profile any `json:"profile" ref:"vector.completions.request.Profile"`
}

func (RemoteAutoProfile) SchemaTitle() string { return "functions.RemoteAutoProfile" }
func (RemoteAutoProfile) SchemaDescription() string { return "A remote auto profile with full metadata.\n\nApplies a single ensemble and weights to every vector completion task\nin the function, with equal task weights." }
func (RemoteAutoProfile) FieldDescriptions() map[string]string {
	return map[string]string{
		"description": "Human-readable description of the profile.",
		"ensemble": "The ensemble to use for all vector completion tasks.",
		"profile": "Weights for each agent in the ensemble.",
	}
}
