// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package functions

type Task interface {
	isTask()
}

type TaskVariant1 struct {
	Type string `json:"type"`
}

func (TaskVariant1) isTask() {}

type TaskVariant2 struct {
	Type string `json:"type"`
}

func (TaskVariant2) isTask() {}

type TaskVariant3 struct {
	Type string `json:"type"`
}

func (TaskVariant3) isTask() {}

type TaskVariant4 struct {
	Type string `json:"type"`
}

func (TaskVariant4) isTask() {}

type TaskVariant5 struct {
	Type string `json:"type"`
}

func (TaskVariant5) isTask() {}

type TaskSchema struct{}

func (TaskSchema) SchemaTitle() string { return "functions.Task" }
func (TaskSchema) SchemaDescription() string { return "A compiled task ready for execution.\n\nProduced by compiling a [`TaskExpression`] against input data. All\nexpressions have been resolved to concrete values." }
func (TaskSchema) Body() map[string]any {
	return map[string]any{
		"anyOf": []any{
			map[string]any{
			"description": "Calls a scalar function (produces a single score).",
			"type": "object",
			"$ref": "functions.ScalarFunctionTask",
			"properties": map[string]any{"type": map[string]any{"enum": []any{"scalar.function"}, "type": "string"}},
		},
			map[string]any{
			"description": "Calls a vector function (produces a vector of scores).",
			"type": "object",
			"$ref": "functions.VectorFunctionTask",
			"properties": map[string]any{"type": map[string]any{"enum": []any{"vector.function"}, "type": "string"}},
		},
			map[string]any{
			"description": "Runs a vector completion.",
			"type": "object",
			"$ref": "functions.VectorCompletionTask",
			"properties": map[string]any{"type": map[string]any{"enum": []any{"vector.completion"}, "type": "string"}},
		},
			map[string]any{
			"description": "Placeholder scalar function (always outputs 0.5).",
			"type": "object",
			"$ref": "functions.PlaceholderScalarFunctionTask",
			"properties": map[string]any{"type": map[string]any{"enum": []any{"placeholder.scalar.function"}, "type": "string"}},
		},
			map[string]any{
			"description": "Placeholder vector function (always outputs equalized vector).",
			"type": "object",
			"$ref": "functions.PlaceholderVectorFunctionTask",
			"properties": map[string]any{"type": map[string]any{"enum": []any{"placeholder.vector.function"}, "type": "string"}},
		},
		},
	}
}
