// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package functions

type VectorCompletionTask struct {
	Messages []any `json:"messages" items_ref:"agent.completions.message.Message"`
	Output any `json:"output" ref:"functions.expression.Expression"`
	Responses []any `json:"responses" items_ref:"agent.completions.message.RichContent"`
}

func (VectorCompletionTask) SchemaTitle() string { return "functions.VectorCompletionTask" }
func (VectorCompletionTask) SchemaDescription() string { return "A compiled vector completion task ready for execution." }
func (VectorCompletionTask) FieldDescriptions() map[string]string {
	return map[string]string{
		"messages": "The resolved conversation messages.",
		"output": "Expression to transform the task result into a valid function output.\n\nReceives `output` as the task's raw result (typically `Vector(scores)`).\nMust return a `TaskOutputOwned` valid for the parent function's type (scalar or vector).\nSee [`VectorCompletionTaskExpression::output`] for full documentation.",
		"responses": "The resolved response options the LLMs can vote for.",
	}
}
