// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package cache

type CacheVoteRequest = any

type CacheVoteRequestSchema struct{}

func (CacheVoteRequestSchema) JSONSchema() map[string]any {
	return map[string]any{
		"title": "vector.completions.cache.CacheVoteRequest",
		"anyOf": []any{
			map[string]any{
			"$ref": "vector.completions.cache.CacheVoteRequestRef",
		},
			map[string]any{
			"$ref": "vector.completions.cache.CacheVoteRequestOwned",
		},
		},
	}
}
