// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package cache

type CacheVote struct {
	Vote any `json:"vote,omitempty" nullable:"true" ref:"vector.completions.response.Vote"`
}

func (CacheVote) SchemaTitle() string { return "vector.completions.cache.CacheVote" }
func (CacheVote) SchemaDescription() string { return "" }
