# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional
from pydantic import BaseModel, ConfigDict, Field
from objectiveai.agent.completions.response.unary.message import Message
from objectiveai.agent.completions.response.unary.object import Object
from objectiveai.agent.completions.response.usage import Usage
from objectiveai.agent.upstream import Upstream
from objectiveai.error.response_error import ResponseError


class Builder(BaseModel):
    """A single builder agent completion within a laboratory execution (non-streaming)."""
    model_config = ConfigDict(title='laboratories.executions.response.unary.Builder')

    agent_index: int = Field(..., description='Agent index (0-based).', ge=0, le=18446744073709551615)
    continuation: Optional[str] = Field(None, description='Continuation state for multi-turn conversations.')
    created: int = Field(..., ge=0, le=18446744073709551615)
    error: Optional[ResponseError] = Field(None, description='Error details if this completion failed.')
    id: str
    index: int = Field(..., description='Builder index (0-based).', ge=0, le=18446744073709551615)
    messages: list[Message]
    object: Object = Field(..., description='The object type (always "agent.completion").')
    upstream: Upstream = Field(..., description='Upstream provider')
    usage: Usage

