// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package auth

type CreateOpenRouterByokApiKeyRequest struct {
	APIKey string `json:"api_key"`
}

func (CreateOpenRouterByokApiKeyRequest) JSONSchema() map[string]any {
	return map[string]any{
		"title": "auth.CreateOpenRouterByokApiKeyRequest",
		"description": "Request to create or update an OpenRouter BYOK (Bring Your Own Key) API key.\n\nThis allows users to provide their own OpenRouter API key for routing\nrequests through OpenRouter's model marketplace.",
		"type": "object",
		"properties": map[string]any{
			"api_key": map[string]any{
			"description": "The OpenRouter API key to associate with the user's account.",
			"type": "string",
		},
		},
	}
}
