// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package auth

type GetOpenRouterByokApiKeyResponse struct {
	APIKey *string `json:"api_key,omitempty" nullable:"true"`
}

func (GetOpenRouterByokApiKeyResponse) SchemaTitle() string { return "auth.GetOpenRouterByokApiKeyResponse" }
func (GetOpenRouterByokApiKeyResponse) SchemaDescription() string { return "Response containing the user's OpenRouter BYOK API key." }
func (GetOpenRouterByokApiKeyResponse) FieldDescriptions() map[string]string {
	return map[string]string{
		"api_key": "The OpenRouter API key, or `None` if not configured.",
	}
}
