# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_notification_value_plugins():
    from objectiveai_sdk.cli.output.notification import NotificationValuePlugins
    schema = NotificationValuePlugins.model_json_schema()
