# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_notification_value_ok():
    from objectiveai_sdk.cli.output.notification import NotificationValueOk
    schema = NotificationValueOk.model_json_schema()
