// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package request

import (
	"encoding/json"
)

var _ json.Number // suppress unused import

type Target interface {
	isTarget()
}

type TargetVariant1 struct {
	Type string `json:"type"`
	Value float64 `json:"value"`
}

func (TargetVariant1) isTarget() {}

type TargetVariant2 struct {
	Type string `json:"type"`
	Value []float64 `json:"value"`
}

func (TargetVariant2) isTarget() {}

type TargetVariant3 struct {
	Type string `json:"type"`
	Value uint32 `json:"value"`
}

func (TargetVariant3) isTarget() {}

type TargetSchema struct{}

func (TargetSchema) SchemaTitle() string { return "functions.profiles.computations.request.Target" }
func (TargetSchema) SchemaDescription() string { return "" }
func (TargetSchema) Body() map[string]any {
	return map[string]any{
		"anyOf": []any{
			map[string]any{
			"type": "object",
			"properties": map[string]any{"type": map[string]any{"enum": []any{"scalar"}, "type": "string"}, "value": map[string]any{"maximum": json.Number("3.4028234663852886e+38"), "minimum": json.Number("-3.4028234663852886e+38"), "type": "number"}},
		},
			map[string]any{
			"type": "object",
			"properties": map[string]any{"type": map[string]any{"enum": []any{"vector"}, "type": "string"}, "value": map[string]any{"items": map[string]any{"maximum": json.Number("3.4028234663852886e+38"), "minimum": json.Number("-3.4028234663852886e+38"), "type": "number"}, "type": "array"}},
		},
			map[string]any{
			"type": "object",
			"properties": map[string]any{"type": map[string]any{"enum": []any{"vector_winner"}, "type": "string"}, "value": map[string]any{"maximum": json.Number("4294967295"), "minimum": json.Number("0"), "type": "integer"}},
		},
		},
	}
}
