# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional
from pydantic import BaseModel, ConfigDict, Field
from objectiveai.agent.completions.response.usage import AgentCompletionsResponseUsage
from objectiveai.functions.full_remote_function import FunctionsFullRemoteFunction
from objectiveai.functions.inventions.response.streaming.agent_completion_chunk import FunctionsInventionsResponseStreamingAgentCompletionChunk
from objectiveai.functions.inventions.response.streaming.object import FunctionsInventionsResponseStreamingObject
from objectiveai.functions.inventions.state.state import FunctionsInventionsStateState
from objectiveai.functions.remote_function_path import FunctionsRemoteFunctionPath
from objectiveai.response_error import ResponseError


class FunctionsInventionsRecursiveResponseStreamingFunctionInventionChunk(BaseModel):
    model_config = ConfigDict(title='functions.inventions.recursive.response.streaming.FunctionInventionChunk')

    completions: list[FunctionsInventionsResponseStreamingAgentCompletionChunk]
    created: int = Field(..., ge=0, le=18446744073709551615)
    error: Optional[ResponseError] = None
    function: Optional[FunctionsFullRemoteFunction] = None
    id: str
    index: int = Field(..., ge=0, le=18446744073709551615)
    object: FunctionsInventionsResponseStreamingObject
    path: Optional[FunctionsRemoteFunctionPath] = None
    state: Optional[FunctionsInventionsStateState] = None
    usage: Optional[AgentCompletionsResponseUsage] = None

