# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional
from pydantic import BaseModel, Field
from objectiveai.agent.completions.response.usage import AgentCompletionsResponseUsage
from objectiveai.functions.full_remote_function import FunctionsFullRemoteFunction
from objectiveai.functions.inventions.response.unary.agent_completion import FunctionsInventionsResponseUnaryAgentCompletion
from objectiveai.functions.inventions.response.unary.object import FunctionsInventionsResponseUnaryObject
from objectiveai.functions.inventions.state.state import FunctionsInventionsStateState
from objectiveai.functions.remote_function_path import FunctionsRemoteFunctionPath
from objectiveai.response_error import ResponseError


class FunctionsInventionsRecursiveResponseUnaryFunctionInvention(BaseModel):
    index: int = Field(..., ge=0, json_schema_extra={'format': 'uint64'})
    id: str
    completions: list[FunctionsInventionsResponseUnaryAgentCompletion]
    state: FunctionsInventionsStateState
    path: Optional[FunctionsRemoteFunctionPath] = None
    function: Optional[FunctionsFullRemoteFunction] = None
    created: int = Field(..., ge=0, json_schema_extra={'format': 'uint64'})
    object: FunctionsInventionsResponseUnaryObject
    usage: AgentCompletionsResponseUsage
    error: Optional[ResponseError] = None

