# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from pydantic import BaseModel
from objectiveai.agent.completions.response.usage import AgentCompletionsResponseUsage
from objectiveai.functions.inventions.recursive.response.unary.function_invention import FunctionsInventionsRecursiveResponseUnaryFunctionInvention
from objectiveai.functions.inventions.recursive.response.unary.object import FunctionsInventionsRecursiveResponseUnaryObject


class FunctionsInventionsRecursiveResponseUnaryFunctionInventionRecursive(BaseModel):
    id: str
    inventions: list[FunctionsInventionsRecursiveResponseUnaryFunctionInvention]
    inventions_errors: bool
    created: int
    object: FunctionsInventionsRecursiveResponseUnaryObject
    usage: AgentCompletionsResponseUsage

