// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package mock

import "encoding/json"

var _ json.Number // suppress unused import

type Agent struct {
	Error *bool `json:"error,omitempty"`
	ID string `json:"id"`
	Invention *bool `json:"invention,omitempty"`
	OutputMode any `json:"output_mode"`
	TopLogprobs *uint64 `json:"top_logprobs,omitempty"`
	Upstream any `json:"upstream"`
}

func (Agent) JSONSchema() map[string]any {
	return map[string]any{
		"title": "agent.mock.Agent",
		"description": "A validated Mock Agent with its computed content-addressed ID.",
		"type": "object",
		"properties": map[string]any{
			"error": map[string]any{
			"description": "If true, the mock client will return an error instead of a response.",
			"anyOf": []any{map[string]any{"type": "boolean"}, map[string]any{"type": "null"}},
		},
			"id": map[string]any{
			"description": "The deterministic content-addressed ID (22-character base62 string).",
			"type": "string",
		},
			"invention": map[string]any{
			"description": "If true, this mock agent supports invention tool calling.\nIncompatible with output modes other than `instruction`.",
			"anyOf": []any{map[string]any{"type": "boolean"}, map[string]any{"type": "null"}},
		},
			"output_mode": map[string]any{
			"description": "The output mode for vector completions. Ignored for agent completions.",
			"$ref": "agent.mock.OutputMode",
		},
			"top_logprobs": map[string]any{
			"description": "Number of top log probabilities to return (2-20).\n\n**Vector completions only.** Ignored for agent completions.",
			"anyOf": []any{map[string]any{"maximum": json.Number("18446744073709551615"), "minimum": json.Number("0"), "type": "integer"}, map[string]any{"type": "null"}},
		},
			"upstream": map[string]any{
			"description": "The upstream provider marker.",
			"$ref": "agent.mock.Upstream",
		},
		},
	}
}
