// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package ensemble

type ListEnsemble struct {
	Data []any `json:"data"`
}

func (ListEnsemble) JSONSchema() map[string]any {
	return map[string]any{
		"title": "ensemble.ListEnsemble",
		"description": "Response containing a list of Ensembles.",
		"type": "object",
		"properties": map[string]any{
			"data": map[string]any{
			"description": "The list of Ensemble summaries.",
			"type": "array",
			"items": map[string]any{"$ref": "ensemble.ListEnsembleItem"},
		},
		},
	}
}
