# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional, Union
from pydantic import BaseModel, Field
from objectiveai.agent.completions.request.agent import AgentCompletionsRequestAgent
from objectiveai.agent.completions.request.provider import AgentCompletionsRequestProvider
from objectiveai.functions.inventions.state.params_state import FunctionsInventionsStateParamsState
from objectiveai.functions.remote import FunctionsRemote


class FunctionsInventionsRecursiveRequestFunctionInventionRecursiveCreateParams(BaseModel):
    remote: FunctionsRemote
    name: str
    state: FunctionsInventionsStateParamsState
    provider: Optional[AgentCompletionsRequestProvider] = None
    agent: AgentCompletionsRequestAgent
    agents: Optional[Union[list[AgentCompletionsRequestAgent], None]] = None
    seed: Optional[Union[int, None]] = Field(None, json_schema_extra={'format': 'int64'})
    stream: Optional[Union[bool, None]] = None
    max_step_retries: Optional[Union[int, None]] = Field(None, description="Maximum number of retries per invention step.\nEach step is one agent completion (which itself may loop internally\nvia tool calls). If the step's validation still fails after the\nagent loop ends, the step is retried up to this many times.\nDefaults to 3 if not specified.", ge=0, json_schema_extra={'format': 'uint32'})
    mcp_server_authorization: Optional[Union[dict[str, str], None]] = Field(None, description='Map from MCP server URL to authorization header value.')

