// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by objectiveai-cli-builder from objectiveai-json-schema/.

use clap::Subcommand;

#[derive(Subcommand)]
#[command(rename_all = "verbatim")]
pub enum GetCommand {
    #[command(name = "get")]
    Get,
}

#[derive(Subcommand)]
#[command(rename_all = "verbatim")]
pub enum Commands {
    #[command(name = "list")]
    List,
    FunctionExecutionChunk {
        #[command(subcommand)]
        command: GetCommand,
    },
    FunctionProfileComputationChunk {
        #[command(subcommand)]
        command: GetCommand,
    },
    Object {
        #[command(subcommand)]
        command: GetCommand,
    },
}

impl Commands {
    pub fn handle(self) -> Result<crate::Output, crate::error::Error> {
        match self {
            Commands::List => Ok(crate::Output::Schema("[\"FunctionExecutionChunk\",\"FunctionProfileComputationChunk\",\"Object\"]")),
            Commands::FunctionExecutionChunk { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../../../../objectiveai-json-schema/functions.profiles.computations.response.streaming.FunctionExecutionChunk.json"),
            )),
            Commands::FunctionProfileComputationChunk { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../../../../objectiveai-json-schema/functions.profiles.computations.response.streaming.FunctionProfileComputationChunk.json"),
            )),
            Commands::Object { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../../../../objectiveai-json-schema/functions.profiles.computations.response.streaming.Object.json"),
            )),
        }
    }
}
