// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { FunctionsExpressionWithExpressionAgentCompletionsMessageSimpleContentExpressionSchema, FunctionsExpressionWithExpressionNullableStringSchema, type FunctionsExpressionWithExpressionAgentCompletionsMessageSimpleContentExpression, type FunctionsExpressionWithExpressionNullableString } from "../../../functions/expression/withExpression";

export interface AgentCompletionsMessageDeveloperMessageExpression {
  content: FunctionsExpressionWithExpressionAgentCompletionsMessageSimpleContentExpression;
  name?: (FunctionsExpressionWithExpressionNullableString) | null;
}
export const AgentCompletionsMessageDeveloperMessageExpressionSchema: z.ZodType<AgentCompletionsMessageDeveloperMessageExpression> = z.object({
  content: z.lazy(() => FunctionsExpressionWithExpressionAgentCompletionsMessageSimpleContentExpressionSchema).describe("The message content expression."),
  name: z.lazy(() => FunctionsExpressionWithExpressionNullableStringSchema).nullable().describe("Optional name expression.").optional(),
}).describe("Expression variant of [`DeveloperMessage`] for dynamic content.").meta({ title: "agent.completions.message.DeveloperMessageExpression" });
