// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { FunctionsExpressionWithExpressionAgentCompletionsMessageFileSchema, FunctionsExpressionWithExpressionAgentCompletionsMessageImageUrlSchema, FunctionsExpressionWithExpressionAgentCompletionsMessageInputAudioSchema, FunctionsExpressionWithExpressionAgentCompletionsMessageVideoUrlSchema, FunctionsExpressionWithExpressionStringSchema, type FunctionsExpressionWithExpressionAgentCompletionsMessageFile, type FunctionsExpressionWithExpressionAgentCompletionsMessageImageUrl, type FunctionsExpressionWithExpressionAgentCompletionsMessageInputAudio, type FunctionsExpressionWithExpressionAgentCompletionsMessageVideoUrl, type FunctionsExpressionWithExpressionString } from "../../../functions/expression/withExpression";

export type AgentCompletionsMessageRichContentPartExpression = {
  text: FunctionsExpressionWithExpressionString;
  type: "text";
} | {
  image_url: FunctionsExpressionWithExpressionAgentCompletionsMessageImageUrl;
  type: "image_url";
} | {
  input_audio: FunctionsExpressionWithExpressionAgentCompletionsMessageInputAudio;
  type: "input_audio";
} | {
  video_url: FunctionsExpressionWithExpressionAgentCompletionsMessageVideoUrl;
  type: "input_video";
} | {
  video_url: FunctionsExpressionWithExpressionAgentCompletionsMessageVideoUrl;
  type: "video_url";
} | {
  file: FunctionsExpressionWithExpressionAgentCompletionsMessageFile;
  type: "file";
};
export const AgentCompletionsMessageRichContentPartExpressionSchema: z.ZodType<AgentCompletionsMessageRichContentPartExpression> = z.union([z.object({
  text: z.lazy(() => FunctionsExpressionWithExpressionStringSchema),
  type: z.literal("text"),
}), z.object({
  image_url: z.lazy(() => FunctionsExpressionWithExpressionAgentCompletionsMessageImageUrlSchema),
  type: z.literal("image_url"),
}), z.object({
  input_audio: z.lazy(() => FunctionsExpressionWithExpressionAgentCompletionsMessageInputAudioSchema),
  type: z.literal("input_audio"),
}), z.object({
  video_url: z.lazy(() => FunctionsExpressionWithExpressionAgentCompletionsMessageVideoUrlSchema),
  type: z.literal("input_video"),
}), z.object({
  video_url: z.lazy(() => FunctionsExpressionWithExpressionAgentCompletionsMessageVideoUrlSchema),
  type: z.literal("video_url"),
}), z.object({
  file: z.lazy(() => FunctionsExpressionWithExpressionAgentCompletionsMessageFileSchema),
  type: z.literal("file"),
})]).describe("Expression variant of [`RichContentPart`] for dynamic content.").meta({ title: "agent.completions.message.RichContentPartExpression" });
