// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package unary

import "encoding/json"

var _ json.Number // suppress unused import

type FunctionInventionRecursive struct {
	Created uint64 `json:"created"`
	ID string `json:"id"`
	Inventions []any `json:"inventions"`
	InventionsErrors bool `json:"inventions_errors"`
	Object any `json:"object"`
	Usage any `json:"usage"`
}

func (FunctionInventionRecursive) JSONSchema() map[string]any {
	return map[string]any{
		"title": "functions.inventions.recursive.response.unary.FunctionInventionRecursive",
		"type": "object",
		"properties": map[string]any{
			"created": map[string]any{
			"type": "integer",
			"minimum": json.Number("0"),
			"maximum": json.Number("18446744073709551615"),
		},
			"id": map[string]any{
			"type": "string",
		},
			"inventions": map[string]any{
			"type": "array",
			"items": map[string]any{"$ref": "functions.inventions.recursive.response.unary.FunctionInvention"},
		},
			"inventions_errors": map[string]any{
			"type": "boolean",
		},
			"object": map[string]any{
			"$ref": "functions.inventions.recursive.response.unary.Object",
		},
			"usage": map[string]any{
			"$ref": "agent.completions.response.Usage",
		},
		},
	}
}
