# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional, Union
from pydantic import BaseModel, Field
from objectiveai.prefixed_uuid import PrefixedUuid


class AuthListApiKeyItem(BaseModel):
    """An API key with metadata and accumulated cost information.

This extends [`ApiKeyWithMetadata`](super::ApiKeyWithMetadata) with
the total cost incurred by requests using this key."""
    api_key: PrefixedUuid = Field(..., description='The API key itself.')
    created: str = Field(..., description='The timestamp when the API key was created (RFC 3339 format).', json_schema_extra={'format': 'date-time'})
    expires: Optional[Union[str, None]] = Field(None, description='The timestamp when the API key expires, or `None` if it does not expire.', json_schema_extra={'format': 'date-time'})
    disabled: Optional[Union[str, None]] = Field(None, description='The timestamp when the API key was disabled, or `None` if it is active.', json_schema_extra={'format': 'date-time'})
    name: str = Field(..., description='The user-provided name of the API key.')
    description: Optional[Union[str, None]] = Field(None, description='The user-provided description of the API key, or `None` if not provided.')
    cost: float = Field(..., description='The total cost incurred by this API key.', json_schema_extra={'format': 'double'})

