// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { AgentCompletionsResponseUsageSchema } from "../../../../../agent/completions/response/usage";
import { ErrorResponseErrorSchema } from "../../../../../error/responseError";
import { FunctionsFullRemoteFunctionSchema } from "../../../../fullRemoteFunction";
import { FunctionsInventionsResponseStreamingAgentCompletionChunkSchema } from "../../../response/streaming/agentCompletionChunk";
import { FunctionsInventionsResponseStreamingObjectSchema } from "../../../response/streaming/object";
import { FunctionsInventionsStateStateSchema } from "../../../state/state";
import { RemotePathSchema } from "../../../../../remotePath";

export const FunctionsInventionsRecursiveResponseStreamingFunctionInventionChunkSchema = z.object({
  completions: z.array(FunctionsInventionsResponseStreamingAgentCompletionChunkSchema),
  created: z.number().int().min(0).max(18446744073709552000),
  error: ErrorResponseErrorSchema.nullable().optional(),
  function: FunctionsFullRemoteFunctionSchema.nullable().optional(),
  id: z.string(),
  index: z.number().int().min(0).max(18446744073709552000),
  object: FunctionsInventionsResponseStreamingObjectSchema,
  path: RemotePathSchema.nullable().optional(),
  state: FunctionsInventionsStateStateSchema.nullable().optional(),
  usage: AgentCompletionsResponseUsageSchema.nullable().optional(),
}).meta({ title: "functions.inventions.recursive.response.streaming.FunctionInventionChunk" });
export type FunctionsInventionsRecursiveResponseStreamingFunctionInventionChunk = z.infer<typeof FunctionsInventionsRecursiveResponseStreamingFunctionInventionChunkSchema>;
