# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Literal, Union
from pydantic import ConfigDict, RootModel


class AgentCompletionsRequestProviderSortVariant1(RootModel):
    """Prioritize by price (cheapest first)."""
    root: Literal['price']


class AgentCompletionsRequestProviderSortVariant2(RootModel):
    """Prioritize by throughput (fastest first)."""
    root: Literal['throughput']


class AgentCompletionsRequestProviderSortVariant3(RootModel):
    """Prioritize by latency (lowest first)."""
    root: Literal['latency']


class AgentCompletionsRequestProviderSort(RootModel):
    """How to sort/prioritize providers."""
    model_config = ConfigDict(title='agent.completions.request.ProviderSort')

    root: Union[AgentCompletionsRequestProviderSortVariant1, AgentCompletionsRequestProviderSortVariant2, AgentCompletionsRequestProviderSortVariant3]

