# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Union
from objectiveai.agent.completions.request.response_format import AgentCompletionsRequestResponseFormat


AgentCompletionsRequestResponseFormatParam = Union[AgentCompletionsRequestResponseFormat, dict[str, AgentCompletionsRequestResponseFormat]]
"""Either a single response format or a per-agent map."""

