# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional, Union
from pydantic import BaseModel
from objectiveai.agent.completions.response.usage import AgentCompletionsResponseUsage
from objectiveai.functions.executions.response.unary.object import FunctionsExecutionsResponseUnaryObject
from objectiveai.functions.executions.response.unary.reasoning_summary import FunctionsExecutionsResponseUnaryReasoningSummary
from objectiveai.functions.executions.response.unary.task import FunctionsExecutionsResponseUnaryTask
from objectiveai.functions.expression.task_output_owned import FunctionsExpressionTaskOutputOwned
from objectiveai.response_error import ResponseError


class FunctionsExecutionsResponseUnaryFunctionExecution(BaseModel):
    """A complete function execution response (non-streaming)."""
    id: str
    tasks: list[FunctionsExecutionsResponseUnaryTask]
    tasks_errors: bool
    reasoning: Optional[FunctionsExecutionsResponseUnaryReasoningSummary] = None
    output: FunctionsExpressionTaskOutputOwned
    error: Optional[ResponseError] = None
    retry_token: Optional[Union[str, None]] = None
    created: int
    function: Optional[Union[str, None]] = None
    profile: Optional[Union[str, None]] = None
    object: FunctionsExecutionsResponseUnaryObject
    usage: AgentCompletionsResponseUsage

