# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import TYPE_CHECKING, Union
from pydantic import RootModel
from objectiveai.functions.executions.response.unary.vector_completion_task import FunctionsExecutionsResponseUnaryVectorCompletionTask

if TYPE_CHECKING:
    from objectiveai.functions.executions.response.unary.function_execution_task import FunctionsExecutionsResponseUnaryFunctionExecutionTask


class FunctionsExecutionsResponseUnaryTask(RootModel):
    root: Union[FunctionsExecutionsResponseUnaryFunctionExecutionTask, FunctionsExecutionsResponseUnaryVectorCompletionTask]

