# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_profile():
    from objectiveai.vector.completions.request import Profile
    schema = Profile.model_json_schema()
