# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_remote_function_variant2():
    from objectiveai.functions.alpha_scalar import RemoteFunctionVariant2
    schema = RemoteFunctionVariant2.model_json_schema()
