# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_branch_task_expression_variant1_variant1():
    from objectiveai.functions.alpha_scalar import BranchTaskExpressionVariant1Variant1
    schema = BranchTaskExpressionVariant1Variant1.model_json_schema()
