# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from objectiveai.functions.alpha_scalar import LeafTaskExpressionVariant1

schema = LeafTaskExpressionVariant1.model_json_schema()
