# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_platform():
    from objectiveai.filesystem.plugins import Platform
    schema = Platform.model_json_schema()
