// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { FunctionsRemoteSchema } from "../../../remote";

export const FunctionsProfilesComputationsRequestFunctionRemoteRequestPathSchema = z.object({
  fcommit: z.string().nullable().optional(),
  fowner: z.string(),
  fremote: FunctionsRemoteSchema,
  frepository: z.string(),
}).meta({ title: "functions.profiles.computations.request.FunctionRemoteRequestPath" });
export type FunctionsProfilesComputationsRequestFunctionRemoteRequestPath = z.infer<typeof FunctionsProfilesComputationsRequestFunctionRemoteRequestPathSchema>;
