// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { FunctionsAlphaVectorExpressionVectorFunctionInputValueExpressionSchema } from "./expression/vectorFunctionInputValueExpression";
import { FunctionsExpressionExpressionSchema } from "../expression/expression";
import { FunctionsRemoteSchema } from "../remote";

export const FunctionsAlphaVectorVectorFunctionTaskExpressionSchema = z.object({
  commit: z.string(),
  input: FunctionsAlphaVectorExpressionVectorFunctionInputValueExpressionSchema,
  owner: z.string(),
  remote: FunctionsRemoteSchema,
  repository: z.string(),
  skip: FunctionsExpressionExpressionSchema.nullable().optional(),
}).meta({ title: "functions.alpha_vector.VectorFunctionTaskExpression" });
export type FunctionsAlphaVectorVectorFunctionTaskExpression = z.infer<typeof FunctionsAlphaVectorVectorFunctionTaskExpressionSchema>;
