# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional, Union
from pydantic import BaseModel, Field
from objectiveai.agent.completions.request.provider import AgentCompletionsRequestProvider
from objectiveai.functions.executions.request.reasoning import FunctionsExecutionsRequestReasoning
from objectiveai.functions.executions.request.strategy import FunctionsExecutionsRequestStrategy
from objectiveai.functions.expression.input_value import FunctionsExpressionInputValue
from objectiveai.functions.inline_function import FunctionsInlineFunction
from objectiveai.functions.inline_profile import FunctionsInlineProfile


class FunctionsExecutionsRequestFunctionInlineProfileInlineRequestBody(BaseModel):
    """Request body for inline Function with inline Profile."""
    function: FunctionsInlineFunction = Field(..., description='The inline Function definition.')
    profile: FunctionsInlineProfile = Field(..., description='The inline Profile definition.')
    retry_token: Optional[Union[str, None]] = Field(None, description='If present, reuses votes from a previous execution with this token.')
    from_cache: Optional[Union[bool, None]] = Field(None, description='If true, uses cached votes when available.')
    reasoning: Optional[FunctionsExecutionsRequestReasoning] = Field(None, description='Reasoning summary configuration.')
    strategy: Optional[FunctionsExecutionsRequestStrategy] = Field(None, description='Execution strategy.\nDefaults to `Default` strategy if not specified.')
    input: FunctionsExpressionInputValue = Field(..., description='The input data to pass to the Function.')
    provider: Optional[AgentCompletionsRequestProvider] = Field(None, description='Provider routing preferences.')
    seed: Optional[Union[int, None]] = Field(None, description='Random seed for deterministic results.', json_schema_extra={'format': 'int64'})
    stream: Optional[Union[bool, None]] = Field(None, description='Whether to stream the response.')
    mcp_server_authorization: Optional[Union[dict[str, str], None]] = Field(None, description='Map from MCP server URL to authorization header value.')

