# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional, Union
from pydantic import BaseModel
from objectiveai.functions.remote import FunctionsRemote


class FunctionsExecutionsRequestFunctionRemoteProfileInlineRequestPath(BaseModel):
    """Path parameters for remote Function with inline Profile."""
    fremote: FunctionsRemote
    fowner: str
    frepository: str
    fcommit: Optional[Union[str, None]] = None

