# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Literal


AgentCompletionsResponseStreamingObject = Literal['agent.completion.chunk']
"""The object type for streaming agent completion chunks."""

