# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_special_variant4():
    from objectiveai.functions.expression import SpecialVariant4
    schema = SpecialVariant4.model_json_schema()
