# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_with_expression_agent_completions_message_image_url():
    from objectiveai.functions.expression import WithExpression_AgentCompletionsMessageImageUrl
    schema = WithExpression_AgentCompletionsMessageImageUrl.model_json_schema()
