# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_input_value_variant6():
    from objectiveai.functions.expression import InputValueVariant6
    schema = InputValueVariant6.model_json_schema()
