# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from objectiveai.functions.expression import WithExpression_AgentCompletionsMessageMessageExpressionVariant2

schema = WithExpression_AgentCompletionsMessageMessageExpressionVariant2.model_json_schema()
