# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_with_expression_array_of_functions_expression_with_expression_agent_completions_message_rich_content_expression():
    from objectiveai.functions.expression import WithExpression_ArrayOfFunctionsExpressionWithExpressionAgentCompletionsMessageRichContentExpression
    schema = WithExpression_ArrayOfFunctionsExpressionWithExpressionAgentCompletionsMessageRichContentExpression.model_json_schema()
