# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from objectiveai.functions.expression import WithExpression_stringVariant1

schema = WithExpression_stringVariant1.model_json_schema()
