# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from objectiveai.functions.expression import InputValueVariant7

schema = InputValueVariant7.model_json_schema()
