# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_with_expression_agent_completions_message_simple_content_expression_variant2():
    from objectiveai.functions.expression import WithExpression_AgentCompletionsMessageSimpleContentExpressionVariant2
    schema = WithExpression_AgentCompletionsMessageSimpleContentExpressionVariant2.model_json_schema()
