# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_with_expression_array_of_functions_expression_with_expression_agent_completions_message_message_expression():
    from objectiveai.functions.expression import WithExpression_ArrayOfFunctionsExpressionWithExpressionAgentCompletionsMessageMessageExpression
    schema = WithExpression_ArrayOfFunctionsExpressionWithExpressionAgentCompletionsMessageMessageExpression.model_json_schema()
