# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_item_variant2():
    from objectiveai.functions.expression import ItemVariant2
    schema = ItemVariant2.model_json_schema()
