# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_task_output_ref():
    from objectiveai.functions.expression import TaskOutputRef
    schema = TaskOutputRef.model_json_schema()
