# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_input_schema_variant7():
    from objectiveai.functions.expression import InputSchemaVariant7
    schema = InputSchemaVariant7.model_json_schema()
