# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_special_variant3():
    from objectiveai.functions.expression import SpecialVariant3
    schema = SpecialVariant3.model_json_schema()
