# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_params_ref():
    from objectiveai.functions.expression import ParamsRef
    schema = ParamsRef.model_json_schema()
