// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

// Wrapper that nests the notification payload one level deeper under a
// `value` field. Required because [`super::super::Output`] uses
// `#[serde(tag = "type")]` — keeping `NotificationValue` under `value`
// instead of flattening preserves the historical `.value.<field>`
// access path for downstream consumers.
//
// `agent_id` is stamped at emit time by [`super::super::Handle`] when
// its `agent_id` field is set; producers building a `Notification`
// inline almost always leave the field `None` and let the handle
// fill it. Serde-skipped when `None`.
//
// Wire (in combination with `Output::Notification`):
// `{"type":"notification","value":{"kind":"<variant>",…},"agent_id":"<id>"?}`.
type CliOutputNotificationNotification struct {
	AgentID *string `json:"agent_id,omitempty"`
	Value CliOutputNotificationNotificationValue `json:"value"`
}

func (CliOutputNotificationNotification) SchemaTitle() string { return "cli.output.notification.Notification" }
func (v CliOutputNotificationNotification) Validate() error {
	return variantValidator.Struct(v)
}

func (v *CliOutputNotificationNotification) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"value"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("CliOutputNotificationNotification: missing required field %q", key)
		}
	}
	type Alias CliOutputNotificationNotification
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = CliOutputNotificationNotification(alias)
	return nil
}
