// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

// Envelope: correlation `id` + tagged [`super::Result`]. Wire shape:
//
// ```json
// {"id":"…","type":"ok"}                         // empty success
// {"id":"…","type":"error","code":404,"message":…}  // failure
// ```
type ClientObjectiveaiMcpClientResponseResponse struct {
	// Matches the `id` of the
	// [`super::super::client_request::Request`] this response is for.
	ID string `json:"id"`
}

func (ClientObjectiveaiMcpClientResponseResponse) SchemaTitle() string { return "client_objectiveai_mcp.client_response.Response" }
func (v ClientObjectiveaiMcpClientResponseResponse) Validate() error {
	return variantValidator.Struct(v)
}

func (v *ClientObjectiveaiMcpClientResponseResponse) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"id"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("ClientObjectiveaiMcpClientResponseResponse: missing required field %q", key)
		}
	}
	type Alias ClientObjectiveaiMcpClientResponseResponse
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = ClientObjectiveaiMcpClientResponseResponse(alias)
	return nil
}
