# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from pydantic import BaseModel
from objectiveai.functions.expression.expression import FunctionsExpressionExpression
from objectiveai.functions.expression.input_schema import FunctionsExpressionInputSchema


class FunctionsCheckVectorFieldsValidation(BaseModel):
    """The 4 fields needed to validate a vector function's split/merge behavior."""
    input_schema: FunctionsExpressionInputSchema
    output_length: FunctionsExpressionExpression
    input_split: FunctionsExpressionExpression
    input_merge: FunctionsExpressionExpression

