# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Literal, Union
from pydantic import BaseModel, ConfigDict, RootModel
from objectiveai.remote_path import RemotePath


class GetProfileResponseVariant1(BaseModel):
    commit: str
    owner: str
    remote: Literal['github']
    repository: str


class GetProfileResponseVariant2(BaseModel):
    commit: str
    owner: str
    remote: Literal['filesystem']
    repository: str


class GetProfileResponseVariant3(BaseModel):
    name: str
    remote: Literal['mock']


class GetProfileResponse(RootModel):
    model_config = ConfigDict(title='functions.profiles.GetProfileResponse', json_schema_extra={'_expanded_ref': 'RemotePath'})

    root: Union[GetProfileResponseVariant1, GetProfileResponseVariant2, GetProfileResponseVariant3]

