# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field
from objectiveai.functions.profiles.list_profile_item import FunctionsProfilesListProfileItem


class FunctionsProfilesListProfile(BaseModel):
    """Response from listing profiles."""
    model_config = ConfigDict(title='functions.profiles.ListProfile')

    data: list[FunctionsProfilesListProfileItem] = Field(..., description='List of available profiles.')

