# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional
from pydantic import BaseModel, ConfigDict, Field
from objectiveai.agent.completions.response.streaming.message_chunk import AgentCompletionsResponseStreamingMessageChunk
from objectiveai.agent.completions.response.streaming.object import AgentCompletionsResponseStreamingObject
from objectiveai.agent.completions.response.usage import AgentCompletionsResponseUsage
from objectiveai.agent.upstream import AgentUpstream
from objectiveai.response_error import ResponseError


class FunctionsInventionsResponseStreamingAgentCompletionChunk(BaseModel):
    """A chunk of a streaming agent completion response.

Multiple chunks are received via Server-Sent Events and can be
accumulated into a complete [`AgentCompletion`](response::unary::AgentCompletion)
using the [`push`](Self::push) method."""
    model_config = ConfigDict(title='functions.inventions.response.streaming.AgentCompletionChunk')

    created: int = Field(..., ge=0, le=18446744073709551615)
    error: Optional[ResponseError] = Field(None, description='Error details if this completion failed.')
    id: str
    index: int = Field(..., ge=0, le=18446744073709551615)
    messages: list[AgentCompletionsResponseStreamingMessageChunk]
    object: AgentCompletionsResponseStreamingObject = Field(..., description='The object type (always "agent.completion.chunk").')
    upstream: AgentUpstream = Field(..., description='Upstream provider')
    usage: Optional[AgentCompletionsResponseUsage] = Field(None, description='Token usage (only present in the final chunk).')

