// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type AgentCompletionsMessageRichContent = any

type AgentCompletionsMessageRichContentSchema struct{}

func (AgentCompletionsMessageRichContentSchema) JSONSchema() map[string]any {
	return map[string]any{
		"title": "agent.completions.message.RichContent",
		"description": "Rich content for user/assistant messages (supports multimodal input).",
		"anyOf": []any{
			map[string]any{
			"description": "Plain text content.",
			"type": "string",
		},
			map[string]any{
			"description": "Multi-part content (text, images, audio, video, files).",
			"type": "array",
			"items": map[string]any{"$ref": "agent.completions.message.RichContentPart"},
		},
		},
	}
}
