// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type AgentOpenrouterReasoningSummaryVerbosity = any

type AgentOpenrouterReasoningSummaryVerbositySchema struct{}

func (AgentOpenrouterReasoningSummaryVerbositySchema) JSONSchema() map[string]any {
	return map[string]any{
		"title": "agent.openrouter.ReasoningSummaryVerbosity",
		"description": "Verbosity of the reasoning summary included in responses.\n\nOnly supported by some models.",
		"anyOf": []any{
			map[string]any{
			"description": "Let the model decide (default, normalized away).",
			"type": "string",
			"enum": []any{"auto"},
		},
			map[string]any{
			"description": "Brief summary of reasoning.",
			"type": "string",
			"enum": []any{"concise"},
		},
			map[string]any{
			"description": "Thorough summary of reasoning.",
			"type": "string",
			"enum": []any{"detailed"},
		},
		},
	}
}
