// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type AgentCompletionsMessageVideoUrl struct {
	URL string `json:"url"`
}

func (AgentCompletionsMessageVideoUrl) JSONSchema() map[string]any {
	return map[string]any{
		"title": "agent.completions.message.VideoUrl",
		"description": "A video URL for multimodal input.",
		"type": "object",
		"properties": map[string]any{
			"url": map[string]any{
			"description": "The URL of the video.",
			"type": "string",
		},
		},
	}
}
