// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type AgentCompletionsResponseToolRole = string

type AgentCompletionsResponseToolRoleSchema struct{}

func (AgentCompletionsResponseToolRoleSchema) JSONSchema() map[string]any {
	return map[string]any{
		"title": "agent.completions.response.ToolRole",
		"type": "string",
		"enum": []any{"tool"},
	}
}
