// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type AgentCompletionsMessageSystemMessage struct {
	Content AgentCompletionsMessageSimpleContent `json:"content"`
	Name *string `json:"name,omitempty"`
}

func (AgentCompletionsMessageSystemMessage) JSONSchema() map[string]any {
	return map[string]any{
		"title": "agent.completions.message.SystemMessage",
		"description": "A system message setting context or instructions.",
		"type": "object",
		"properties": map[string]any{
			"content": map[string]any{
			"description": "The message content.",
			"$ref": "agent.completions.message.SimpleContent",
		},
			"name": map[string]any{
			"description": "Optional name for the message author.",
			"anyOf": []any{map[string]any{"type": "string"}, map[string]any{"type": "null"}},
		},
		},
	}
}
