// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type AgentCompletionsResponseStreamingObject = string

type AgentCompletionsResponseStreamingObjectSchema struct{}

func (AgentCompletionsResponseStreamingObjectSchema) JSONSchema() map[string]any {
	return map[string]any{
		"title": "agent.completions.response.streaming.Object",
		"description": "A agent completion chunk object.",
		"type": "string",
		"enum": []any{"agent.completion.chunk"},
	}
}
