// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type AgentCompletionsMessageImageUrlDetail = any

type AgentCompletionsMessageImageUrlDetailSchema struct{}

func (AgentCompletionsMessageImageUrlDetailSchema) JSONSchema() map[string]any {
	return map[string]any{
		"title": "agent.completions.message.ImageUrlDetail",
		"description": "Detail level for image processing.",
		"anyOf": []any{
			map[string]any{
			"description": "Let the model decide the detail level.",
			"type": "string",
			"enum": []any{"auto"},
		},
			map[string]any{
			"description": "Low detail mode (faster, less tokens).",
			"type": "string",
			"enum": []any{"low"},
		},
			map[string]any{
			"description": "High detail mode (more accurate, more tokens).",
			"type": "string",
			"enum": []any{"high"},
		},
		},
	}
}
