// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type AgentCompletionsMessageRichContentPartExpression = any

type AgentCompletionsMessageRichContentPartExpressionSchema struct{}

func (AgentCompletionsMessageRichContentPartExpressionSchema) JSONSchema() map[string]any {
	return map[string]any{
		"title": "agent.completions.message.RichContentPartExpression",
		"description": "Expression variant of [`RichContentPart`] for dynamic content.",
		"anyOf": []any{
			map[string]any{
			"type": "object",
			"properties": map[string]any{"text": map[string]any{"$ref": "functions.expression.WithExpression.string"}, "type": map[string]any{"enum": []any{"text"}, "type": "string"}},
		},
			map[string]any{
			"type": "object",
			"properties": map[string]any{"image_url": map[string]any{"$ref": "functions.expression.WithExpression.agent.completions.message.ImageUrl"}, "type": map[string]any{"enum": []any{"image_url"}, "type": "string"}},
		},
			map[string]any{
			"type": "object",
			"properties": map[string]any{"input_audio": map[string]any{"$ref": "functions.expression.WithExpression.agent.completions.message.InputAudio"}, "type": map[string]any{"enum": []any{"input_audio"}, "type": "string"}},
		},
			map[string]any{
			"type": "object",
			"properties": map[string]any{"type": map[string]any{"enum": []any{"input_video"}, "type": "string"}, "video_url": map[string]any{"$ref": "functions.expression.WithExpression.agent.completions.message.VideoUrl"}},
		},
			map[string]any{
			"type": "object",
			"properties": map[string]any{"type": map[string]any{"enum": []any{"video_url"}, "type": "string"}, "video_url": map[string]any{"$ref": "functions.expression.WithExpression.agent.completions.message.VideoUrl"}},
		},
			map[string]any{
			"type": "object",
			"properties": map[string]any{"file": map[string]any{"$ref": "functions.expression.WithExpression.agent.completions.message.File"}, "type": map[string]any{"enum": []any{"file"}, "type": "string"}},
		},
		},
	}
}
