// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type AgentClaudeAgentSdkEffort = any

type AgentClaudeAgentSdkEffortSchema struct{}

func (AgentClaudeAgentSdkEffortSchema) JSONSchema() map[string]any {
	return map[string]any{
		"title": "agent.claude_agent_sdk.Effort",
		"description": "The effort level for model output.\n\nThis setting hints to the model how detailed its responses should be.",
		"anyOf": []any{
			map[string]any{
			"description": "Minimal output, concise responses.",
			"type": "string",
			"enum": []any{"low"},
		},
			map[string]any{
			"description": "Balanced output (default, normalized away during preparation).",
			"type": "string",
			"enum": []any{"medium"},
		},
			map[string]any{
			"description": "Detailed output with thorough explanations.",
			"type": "string",
			"enum": []any{"high"},
		},
			map[string]any{
			"description": "Maximum effort, most detailed output possible.",
			"type": "string",
			"enum": []any{"max"},
		},
		},
	}
}
