// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type FunctionsAlphaVectorVectorCompletionTaskExpression struct {
	Messages FunctionsExpressionExpression `json:"messages"`
	Responses FunctionsExpressionExpression `json:"responses"`
	Skip *FunctionsExpressionExpression `json:"skip,omitempty"`
}

func (FunctionsAlphaVectorVectorCompletionTaskExpression) JSONSchema() map[string]any {
	return map[string]any{
		"title": "functions.alpha_vector.VectorCompletionTaskExpression",
		"type": "object",
		"properties": map[string]any{
			"messages": map[string]any{
			"$ref": "functions.expression.Expression",
		},
			"responses": map[string]any{
			"$ref": "functions.expression.Expression",
		},
			"skip": map[string]any{
			"anyOf": []any{map[string]any{"$ref": "functions.expression.Expression"}, map[string]any{"type": "null"}},
		},
		},
	}
}
