// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type FunctionsAlphaVectorPartialPlaceholderVectorFunctionTaskExpression struct {
	Input FunctionsAlphaVectorExpressionVectorFunctionInputValueExpression `json:"input"`
	InputSchema FunctionsAlphaVectorExpressionVectorFunctionInputSchema `json:"input_schema"`
	Skip *FunctionsExpressionExpression `json:"skip,omitempty"`
	Spec string `json:"spec"`
}

func (FunctionsAlphaVectorPartialPlaceholderVectorFunctionTaskExpression) JSONSchema() map[string]any {
	return map[string]any{
		"title": "functions.alpha_vector.PartialPlaceholderVectorFunctionTaskExpression",
		"type": "object",
		"properties": map[string]any{
			"input": map[string]any{
			"$ref": "functions.alpha_vector.expression.VectorFunctionInputValueExpression",
		},
			"input_schema": map[string]any{
			"$ref": "functions.alpha_vector.expression.VectorFunctionInputSchema",
		},
			"skip": map[string]any{
			"anyOf": []any{map[string]any{"$ref": "functions.expression.Expression"}, map[string]any{"type": "null"}},
		},
			"spec": map[string]any{
			"type": "string",
		},
		},
	}
}
