// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type FunctionsAlphaVectorPartialPlaceholderScalarFunctionTaskExpression struct {
	Input FunctionsExpressionExpression `json:"input"`
	InputSchema FunctionsExpressionObjectInputSchema `json:"input_schema"`
	Skip *FunctionsExpressionExpression `json:"skip,omitempty"`
	Spec string `json:"spec"`
}

func (FunctionsAlphaVectorPartialPlaceholderScalarFunctionTaskExpression) SchemaTitle() string { return "functions.alpha_vector.PartialPlaceholderScalarFunctionTaskExpression" }
func (FunctionsAlphaVectorPartialPlaceholderScalarFunctionTaskExpression) SchemaDescription() string { return "" }
func (v FunctionsAlphaVectorPartialPlaceholderScalarFunctionTaskExpression) Validate() error {
	return variantValidator.Struct(v)
}
