// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type FunctionsExpressionStringInputSchema struct {
	Description *string `json:"description,omitempty"`
	Enum []string `json:"enum,omitempty"`
	Type FunctionsExpressionStringInputSchemaType `json:"type"`
}

func (FunctionsExpressionStringInputSchema) JSONSchema() map[string]any {
	return map[string]any{
		"title": "functions.expression.StringInputSchema",
		"description": "Schema for a string input.",
		"type": "object",
		"properties": map[string]any{
			"description": map[string]any{
			"description": "Human-readable description of the string.",
			"anyOf": []any{map[string]any{"type": "string"}, map[string]any{"type": "null"}},
		},
			"enum": map[string]any{
			"description": "If provided, the string must be one of these values.",
			"anyOf": []any{map[string]any{"items": map[string]any{"type": "string"}, "type": "array"}, map[string]any{"type": "null"}},
		},
			"type": map[string]any{
			"$ref": "functions.expression.StringInputSchemaType",
		},
		},
	}
}
