// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type FunctionsProfilesComputationsRequestFunctionRemoteRequestPath struct {
	Fcommit *string `json:"fcommit,omitempty"`
	Fowner string `json:"fowner"`
	Fremote FunctionsRemote `json:"fremote"`
	Frepository string `json:"frepository"`
}

func (FunctionsProfilesComputationsRequestFunctionRemoteRequestPath) JSONSchema() map[string]any {
	return map[string]any{
		"title": "functions.profiles.computations.request.FunctionRemoteRequestPath",
		"type": "object",
		"properties": map[string]any{
			"fcommit": map[string]any{
			"anyOf": []any{map[string]any{"type": "string"}, map[string]any{"type": "null"}},
		},
			"fowner": map[string]any{
			"type": "string",
		},
			"fremote": map[string]any{
			"$ref": "functions.Remote",
		},
			"frepository": map[string]any{
			"type": "string",
		},
		},
	}
}
