// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type FunctionsExecutionsResponseStreamingTaskChunk = any

type FunctionsExecutionsResponseStreamingTaskChunkSchema struct{}

func (FunctionsExecutionsResponseStreamingTaskChunkSchema) JSONSchema() map[string]any {
	return map[string]any{
		"title": "functions.executions.response.streaming.TaskChunk",
		"anyOf": []any{
			map[string]any{
			"$ref": "functions.executions.response.streaming.FunctionExecutionTaskChunk",
		},
			map[string]any{
			"$ref": "functions.executions.response.streaming.VectorCompletionTaskChunk",
		},
		},
	}
}
