// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

type FunctionsExpressionStringInputSchemaType struct {
	Variant1 string `validate:"oneof=string"`
}

func (v FunctionsExpressionStringInputSchemaType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.Variant1)
}

func (v *FunctionsExpressionStringInputSchemaType) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.Variant1); err != nil {
		return err
	}
	return v.Validate()
}

func (v FunctionsExpressionStringInputSchemaType) Validate() error {
	return variantValidator.Struct(v)
}

type FunctionsExpressionStringInputSchemaTypeSchema struct{}

func (FunctionsExpressionStringInputSchemaTypeSchema) SchemaTitle() string { return "functions.expression.StringInputSchemaType" }
func (FunctionsExpressionStringInputSchemaTypeSchema) SchemaDescription() string { return "" }
func (FunctionsExpressionStringInputSchemaTypeSchema) Body() map[string]any {
	return map[string]any{
		"type": "string",
		"enum": []any{"string"},
	}
}
