// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

type FunctionsInventionsResponseStreamingObject struct {
	Variant1 string `validate:"oneof=alpha.scalar.function.invention.chunk alpha.vector.function.invention.chunk"`
}

func (v FunctionsInventionsResponseStreamingObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.Variant1)
}

func (v *FunctionsInventionsResponseStreamingObject) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.Variant1); err != nil {
		return err
	}
	return v.Validate()
}

func (v FunctionsInventionsResponseStreamingObject) Validate() error {
	return variantValidator.Struct(v)
}

type FunctionsInventionsResponseStreamingObjectSchema struct{}

func (FunctionsInventionsResponseStreamingObjectSchema) SchemaTitle() string { return "functions.inventions.response.streaming.Object" }
func (FunctionsInventionsResponseStreamingObjectSchema) SchemaDescription() string { return "" }
func (FunctionsInventionsResponseStreamingObjectSchema) Body() map[string]any {
	return map[string]any{
		"type": "string",
		"enum": []any{"alpha.scalar.function.invention.chunk", "alpha.vector.function.invention.chunk"},
	}
}
