// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type FunctionsInventionsRecursiveResponseStreamingObject = string

type FunctionsInventionsRecursiveResponseStreamingObjectSchema struct{}

func (FunctionsInventionsRecursiveResponseStreamingObjectSchema) JSONSchema() map[string]any {
	return map[string]any{
		"title": "functions.inventions.recursive.response.streaming.Object",
		"type": "string",
		"enum": []any{"alpha.scalar.function.invention.recursive.chunk", "alpha.vector.function.invention.recursive.chunk"},
	}
}
