// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import "encoding/json"

var _ json.Number // suppress unused import

type FunctionsInventionsRecursiveResponseUnaryFunctionInvention struct {
	Completions []FunctionsInventionsResponseUnaryAgentCompletion `json:"completions"`
	Created uint64 `json:"created"`
	Error *ResponseError `json:"error,omitempty"`
	Function *FunctionsFullRemoteFunction `json:"function,omitempty"`
	ID string `json:"id"`
	Index uint64 `json:"index"`
	Object FunctionsInventionsResponseUnaryObject `json:"object"`
	Path *FunctionsRemoteFunctionPath `json:"path,omitempty"`
	State FunctionsInventionsStateState `json:"state"`
	Usage AgentCompletionsResponseUsage `json:"usage"`
}

func (FunctionsInventionsRecursiveResponseUnaryFunctionInvention) JSONSchema() map[string]any {
	return map[string]any{
		"title": "functions.inventions.recursive.response.unary.FunctionInvention",
		"type": "object",
		"properties": map[string]any{
			"completions": map[string]any{
			"type": "array",
			"items": map[string]any{"$ref": "functions.inventions.response.unary.AgentCompletion"},
		},
			"created": map[string]any{
			"type": "integer",
			"minimum": json.Number("0"),
			"maximum": json.Number("18446744073709551615"),
		},
			"error": map[string]any{
			"anyOf": []any{map[string]any{"$ref": "ResponseError"}, map[string]any{"type": "null"}},
		},
			"function": map[string]any{
			"anyOf": []any{map[string]any{"$ref": "functions.FullRemoteFunction"}, map[string]any{"type": "null"}},
		},
			"id": map[string]any{
			"type": "string",
		},
			"index": map[string]any{
			"type": "integer",
			"minimum": json.Number("0"),
			"maximum": json.Number("18446744073709551615"),
		},
			"object": map[string]any{
			"$ref": "functions.inventions.response.unary.Object",
		},
			"path": map[string]any{
			"anyOf": []any{map[string]any{"$ref": "functions.RemoteFunctionPath"}, map[string]any{"type": "null"}},
		},
			"state": map[string]any{
			"$ref": "functions.inventions.state.State",
		},
			"usage": map[string]any{
			"$ref": "agent.completions.response.Usage",
		},
		},
	}
}
