// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

// A remote auto profile with full metadata.
//
// Applies a single ensemble and weights to every vector completion task
// in the function, with equal task weights.
type FunctionsRemoteAutoProfile struct {
	// Human-readable description of the profile.
	Description string `json:"description"`
	// The ensemble to use for all vector completion tasks.
	Ensemble VectorCompletionsRequestEnsemble `json:"ensemble"`
	// Weights for each agent in the ensemble.
	Profile VectorCompletionsRequestProfile `json:"profile"`
}

func (FunctionsRemoteAutoProfile) SchemaTitle() string { return "functions.RemoteAutoProfile" }
func (FunctionsRemoteAutoProfile) SchemaDescription() string { return "A remote auto profile with full metadata.\n\nApplies a single ensemble and weights to every vector completion task\nin the function, with equal task weights." }
func (FunctionsRemoteAutoProfile) FieldDescriptions() map[string]string {
	return map[string]string{
		"description": "Human-readable description of the profile.",
		"ensemble": "The ensemble to use for all vector completion tasks.",
		"profile": "Weights for each agent in the ensemble.",
	}
}
func (v FunctionsRemoteAutoProfile) Validate() error {
	return variantValidator.Struct(v)
}
