// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

// Request body for remote Function with inline Profile.
type FunctionsExecutionsRequestFunctionRemoteProfileInlineRequestBody struct {
	// If true, uses cached votes when available.
	FromCache *bool `json:"from_cache,omitempty"`
	// The input data to pass to the Function.
	Input FunctionsExpressionInputValue `json:"input"`
	// Map from MCP server URL to authorization header value.
	MCPServerAuthorization map[string]string `json:"mcp_server_authorization,omitempty"`
	// The inline Profile definition.
	Profile FunctionsInlineProfile `json:"profile"`
	// Provider routing preferences.
	Provider *AgentCompletionsRequestProvider `json:"provider,omitempty"`
	// Reasoning summary configuration.
	Reasoning *FunctionsExecutionsRequestReasoning `json:"reasoning,omitempty"`
	// If present, reuses votes from a previous execution with this token.
	RetryToken *string `json:"retry_token,omitempty"`
	// Random seed for deterministic results.
	Seed *int64 `json:"seed,omitempty" validate:"min=-9223372036854775808,max=9223372036854775807"`
	// Execution strategy.
	// Defaults to `Default` strategy if not specified.
	Strategy *FunctionsExecutionsRequestStrategy `json:"strategy,omitempty"`
	// Whether to stream the response.
	Stream *bool `json:"stream,omitempty"`
}

func (FunctionsExecutionsRequestFunctionRemoteProfileInlineRequestBody) SchemaTitle() string { return "functions.executions.request.FunctionRemoteProfileInlineRequestBody" }
func (FunctionsExecutionsRequestFunctionRemoteProfileInlineRequestBody) SchemaDescription() string { return "Request body for remote Function with inline Profile." }
func (FunctionsExecutionsRequestFunctionRemoteProfileInlineRequestBody) FieldDescriptions() map[string]string {
	return map[string]string{
		"from_cache": "If true, uses cached votes when available.",
		"input": "The input data to pass to the Function.",
		"mcp_server_authorization": "Map from MCP server URL to authorization header value.",
		"profile": "The inline Profile definition.",
		"provider": "Provider routing preferences.",
		"reasoning": "Reasoning summary configuration.",
		"retry_token": "If present, reuses votes from a previous execution with this token.",
		"seed": "Random seed for deterministic results.",
		"strategy": "Execution strategy.\nDefaults to `Default` strategy if not specified.",
		"stream": "Whether to stream the response.",
	}
}
func (v FunctionsExecutionsRequestFunctionRemoteProfileInlineRequestBody) Validate() error {
	return variantValidator.Struct(v)
}
