// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type FunctionsProfilesListProfileItem struct {
	Commit string `json:"commit"`
	Owner string `json:"owner"`
	Remote FunctionsRemote `json:"remote"`
	Repository string `json:"repository"`
}

func (FunctionsProfilesListProfileItem) JSONSchema() map[string]any {
	return map[string]any{
		"title": "functions.profiles.ListProfileItem",
		"description": "A profile in a list response.",
		"type": "object",
		"properties": map[string]any{
			"commit": map[string]any{
			"description": "Git commit SHA.",
			"type": "string",
		},
			"owner": map[string]any{
			"description": "Repository owner.",
			"type": "string",
		},
			"remote": map[string]any{
			"description": "The remote source where the profile is hosted.",
			"$ref": "functions.Remote",
		},
			"repository": map[string]any{
			"description": "Repository name.",
			"type": "string",
		},
		},
	}
}
