// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type FunctionsRemoteFunctionPath struct {
	Commit string `json:"commit"`
	Owner string `json:"owner"`
	Remote FunctionsRemote `json:"remote"`
	Repository string `json:"repository"`
}

func (FunctionsRemoteFunctionPath) JSONSchema() map[string]any {
	return map[string]any{
		"title": "functions.RemoteFunctionPath",
		"type": "object",
		"properties": map[string]any{
			"commit": map[string]any{
			"type": "string",
		},
			"owner": map[string]any{
			"type": "string",
		},
			"remote": map[string]any{
			"$ref": "functions.Remote",
		},
			"repository": map[string]any{
			"type": "string",
		},
		},
	}
}
