// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type FunctionsAlphaVectorLeafTaskExpression struct {
	Type string `json:"type"`
}

func (FunctionsAlphaVectorLeafTaskExpression) JSONSchema() map[string]any {
	return map[string]any{
		"title": "functions.alpha_vector.LeafTaskExpression",
		"type": "object",
		"$ref": "functions.alpha_vector.VectorCompletionTaskExpression",
		"properties": map[string]any{
			"type": map[string]any{
			"type": "string",
			"enum": []any{"vector.completion"},
		},
		},
	}
}
