// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type FunctionsInventionsStateAlphaScalarLeafState struct {
	Depth uint64 `json:"depth" validate:"min=0,max=18446744073709551615"`
	Description *string `json:"description,omitempty"`
	Essay *string `json:"essay,omitempty"`
	EssayTasks *string `json:"essay_tasks,omitempty"`
	InputSchema *FunctionsExpressionObjectInputSchema `json:"input_schema,omitempty"`
	MaxBranchWidth uint64 `json:"max_branch_width" validate:"min=0,max=18446744073709551615"`
	MaxLeafWidth uint64 `json:"max_leaf_width" validate:"min=0,max=18446744073709551615"`
	MinBranchWidth uint64 `json:"min_branch_width" validate:"min=0,max=18446744073709551615"`
	MinLeafWidth uint64 `json:"min_leaf_width" validate:"min=0,max=18446744073709551615"`
	Name string `json:"name"`
	Readme *string `json:"readme,omitempty"`
	Spec string `json:"spec"`
	Tasks []FunctionsAlphaScalarLeafTaskExpression `json:"tasks,omitempty"`
	TasksLength *uint64 `json:"tasks_length,omitempty" validate:"min=0,max=18446744073709551615"`
}

func (FunctionsInventionsStateAlphaScalarLeafState) SchemaTitle() string { return "functions.inventions.state.AlphaScalarLeafState" }
func (FunctionsInventionsStateAlphaScalarLeafState) SchemaDescription() string { return "" }
func (v FunctionsInventionsStateAlphaScalarLeafState) Validate() error {
	return variantValidator.Struct(v)
}
