// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type FunctionsTaskExpression = any

type FunctionsTaskExpressionSchema struct{}

func (FunctionsTaskExpressionSchema) JSONSchema() map[string]any {
	return map[string]any{
		"title": "functions.TaskExpression",
		"description": "A task definition with expressions (pre-compilation).\n\nTask expressions contain dynamic fields (JMESPath or Starlark) that are\nresolved against input data during compilation. Use [`compile`](Self::compile)\nto produce a concrete [`Task`].",
		"anyOf": []any{
			map[string]any{
			"type": "object",
			"$ref": "functions.ScalarFunctionTaskExpression",
			"properties": map[string]any{"type": map[string]any{"enum": []any{"scalar.function"}, "type": "string"}},
		},
			map[string]any{
			"type": "object",
			"$ref": "functions.VectorFunctionTaskExpression",
			"properties": map[string]any{"type": map[string]any{"enum": []any{"vector.function"}, "type": "string"}},
		},
			map[string]any{
			"type": "object",
			"$ref": "functions.VectorCompletionTaskExpression",
			"properties": map[string]any{"type": map[string]any{"enum": []any{"vector.completion"}, "type": "string"}},
		},
			map[string]any{
			"type": "object",
			"$ref": "functions.PlaceholderScalarFunctionTaskExpression",
			"properties": map[string]any{"type": map[string]any{"enum": []any{"placeholder.scalar.function"}, "type": "string"}},
		},
			map[string]any{
			"type": "object",
			"$ref": "functions.PlaceholderVectorFunctionTaskExpression",
			"properties": map[string]any{"type": map[string]any{"enum": []any{"placeholder.vector.function"}, "type": "string"}},
		},
		},
	}
}
