// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

// A complete function execution response (non-streaming).
type FunctionsExecutionsResponseUnaryFunctionExecutionTask struct {
	// Unix timestamp when the execution was created.
	Created uint64 `json:"created" validate:"min=0,max=18446744073709551615"`
	// Error details if the execution failed.
	Error *ResponseError `json:"error,omitempty"`
	// ID of the function used (if remote).
	Function *string `json:"function,omitempty"`
	// Unique identifier for this execution.
	ID string `json:"id"`
	Index uint64 `json:"index" validate:"min=0,max=18446744073709551615"`
	// Object type identifier.
	Object FunctionsExecutionsResponseUnaryObject `json:"object"`
	// The final output (scalar or vector score).
	Output FunctionsExpressionTaskOutputOwned `json:"output"`
	// ID of the profile used (if remote).
	Profile *string `json:"profile,omitempty"`
	// Reasoning summary if reasoning was enabled.
	Reasoning *FunctionsExecutionsResponseUnaryReasoningSummary `json:"reasoning,omitempty"`
	// Token for retrying this execution with cached votes.
	RetryToken *string `json:"retry_token,omitempty"`
	SwissPoolIndex *uint64 `json:"swiss_pool_index,omitempty" validate:"min=0,max=18446744073709551615"`
	SwissRound *uint64 `json:"swiss_round,omitempty" validate:"min=0,max=18446744073709551615"`
	TaskIndex uint64 `json:"task_index" validate:"min=0,max=18446744073709551615"`
	TaskPath []uint64 `json:"task_path"`
	// Results from each task in the function.
	Tasks []FunctionsExecutionsResponseUnaryTask `json:"tasks"`
	// Whether any tasks encountered errors.
	TasksErrors bool `json:"tasks_errors"`
	// Aggregated token and cost usage.
	Usage AgentCompletionsResponseUsage `json:"usage"`
}

func (FunctionsExecutionsResponseUnaryFunctionExecutionTask) SchemaTitle() string { return "functions.executions.response.unary.FunctionExecutionTask" }
func (FunctionsExecutionsResponseUnaryFunctionExecutionTask) SchemaDescription() string { return "A complete function execution response (non-streaming)." }
func (FunctionsExecutionsResponseUnaryFunctionExecutionTask) FieldDescriptions() map[string]string {
	return map[string]string{
		"created": "Unix timestamp when the execution was created.",
		"error": "Error details if the execution failed.",
		"function": "ID of the function used (if remote).",
		"id": "Unique identifier for this execution.",
		"object": "Object type identifier.",
		"output": "The final output (scalar or vector score).",
		"profile": "ID of the profile used (if remote).",
		"reasoning": "Reasoning summary if reasoning was enabled.",
		"retry_token": "Token for retrying this execution with cached votes.",
		"tasks": "Results from each task in the function.",
		"tasks_errors": "Whether any tasks encountered errors.",
		"usage": "Aggregated token and cost usage.",
	}
}
func (v FunctionsExecutionsResponseUnaryFunctionExecutionTask) Validate() error {
	return variantValidator.Struct(v)
}
