// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

// A chunk of a streaming agent completion response.
//
// Multiple chunks are received via Server-Sent Events and can be
// accumulated into a complete [`AgentCompletion`](response::unary::AgentCompletion)
// using the [`push`](Self::push) method.
type FunctionsInventionsResponseStreamingAgentCompletionChunk struct {
	Created uint64 `json:"created" validate:"min=0,max=18446744073709551615"`
	// Error details if this completion failed.
	Error *ResponseError `json:"error,omitempty"`
	ID string `json:"id"`
	Index uint64 `json:"index" validate:"min=0,max=18446744073709551615"`
	Messages []AgentCompletionsResponseStreamingMessageChunk `json:"messages"`
	// The object type (always "agent.completion.chunk").
	Object AgentCompletionsResponseStreamingObject `json:"object"`
	// Upstream provider
	Upstream AgentUpstream `json:"upstream"`
	// Token usage (only present in the final chunk).
	Usage *AgentCompletionsResponseUsage `json:"usage,omitempty"`
}

func (FunctionsInventionsResponseStreamingAgentCompletionChunk) SchemaTitle() string { return "functions.inventions.response.streaming.AgentCompletionChunk" }
func (FunctionsInventionsResponseStreamingAgentCompletionChunk) SchemaDescription() string { return "A chunk of a streaming agent completion response.\n\nMultiple chunks are received via Server-Sent Events and can be\naccumulated into a complete [`AgentCompletion`](response::unary::AgentCompletion)\nusing the [`push`](Self::push) method." }
func (FunctionsInventionsResponseStreamingAgentCompletionChunk) FieldDescriptions() map[string]string {
	return map[string]string{
		"error": "Error details if this completion failed.",
		"object": "The object type (always \"agent.completion.chunk\").",
		"upstream": "Upstream provider",
		"usage": "Token usage (only present in the final chunk).",
	}
}
func (v FunctionsInventionsResponseStreamingAgentCompletionChunk) Validate() error {
	return variantValidator.Struct(v)
}
