// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

// An inline auto profile definition without metadata.
//
// Applies a single ensemble and weights to every vector completion task
// in the function, with equal task weights.
type FunctionsInlineAutoProfile struct {
	// The ensemble to use for all vector completion tasks.
	Ensemble VectorCompletionsRequestEnsemble `json:"ensemble"`
	// Weights for each agent in the ensemble.
	Profile VectorCompletionsRequestProfile `json:"profile"`
}

func (FunctionsInlineAutoProfile) SchemaTitle() string { return "functions.InlineAutoProfile" }
func (FunctionsInlineAutoProfile) SchemaDescription() string { return "An inline auto profile definition without metadata.\n\nApplies a single ensemble and weights to every vector completion task\nin the function, with equal task weights." }
func (FunctionsInlineAutoProfile) FieldDescriptions() map[string]string {
	return map[string]string{
		"ensemble": "The ensemble to use for all vector completion tasks.",
		"profile": "Weights for each agent in the ensemble.",
	}
}
func (v FunctionsInlineAutoProfile) Validate() error {
	return variantValidator.Struct(v)
}
