// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type FunctionsExpressionArrayInputSchemaType = string

type FunctionsExpressionArrayInputSchemaTypeSchema struct{}

func (FunctionsExpressionArrayInputSchemaTypeSchema) JSONSchema() map[string]any {
	return map[string]any{
		"title": "functions.expression.ArrayInputSchemaType",
		"type": "string",
		"enum": []any{"array"},
	}
}
