// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type FunctionsExecutionsRequestFunctionInlineProfileRemoteRequestPath struct {
	Pcommit *string `json:"pcommit,omitempty"`
	Powner string `json:"powner"`
	Premote FunctionsRemote `json:"premote"`
	Prepository string `json:"prepository"`
}

func (FunctionsExecutionsRequestFunctionInlineProfileRemoteRequestPath) JSONSchema() map[string]any {
	return map[string]any{
		"title": "functions.executions.request.FunctionInlineProfileRemoteRequestPath",
		"description": "Path parameters for inline Function with remote Profile.",
		"type": "object",
		"properties": map[string]any{
			"pcommit": map[string]any{
			"description": "Profile Git commit SHA (optional).",
			"anyOf": []any{map[string]any{"type": "string"}, map[string]any{"type": "null"}},
		},
			"powner": map[string]any{
			"description": "Profile repository owner.",
			"type": "string",
		},
			"premote": map[string]any{
			"description": "Profile remote source.",
			"$ref": "functions.Remote",
		},
			"prepository": map[string]any{
			"description": "Profile repository name.",
			"type": "string",
		},
		},
	}
}
