// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type FunctionsProfilesComputationsRequestFunctionInlineRequestBody struct {
	Dataset []FunctionsProfilesComputationsRequestDatasetItem `json:"dataset"`
	Ensemble VectorCompletionsRequestEnsemble `json:"ensemble"`
	FromCache *bool `json:"from_cache,omitempty"`
	Function FunctionsInlineFunction `json:"function"`
	MaxRetries *uint64 `json:"max_retries,omitempty" validate:"min=0,max=18446744073709551615"`
	// Map from MCP server URL to authorization header value.
	MCPServerAuthorization map[string]string `json:"mcp_server_authorization,omitempty"`
	N uint64 `json:"n" validate:"min=0,max=18446744073709551615"`
	Provider *AgentCompletionsRequestProvider `json:"provider,omitempty"`
	RetryToken *string `json:"retry_token,omitempty"`
	Seed *int64 `json:"seed,omitempty" validate:"min=-9223372036854775808,max=9223372036854775807"`
	Stream *bool `json:"stream,omitempty"`
}

func (FunctionsProfilesComputationsRequestFunctionInlineRequestBody) SchemaTitle() string { return "functions.profiles.computations.request.FunctionInlineRequestBody" }
func (FunctionsProfilesComputationsRequestFunctionInlineRequestBody) SchemaDescription() string { return "" }
func (FunctionsProfilesComputationsRequestFunctionInlineRequestBody) FieldDescriptions() map[string]string {
	return map[string]string{
		"mcp_server_authorization": "Map from MCP server URL to authorization header value.",
	}
}
func (v FunctionsProfilesComputationsRequestFunctionInlineRequestBody) Validate() error {
	return variantValidator.Struct(v)
}
