// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import "encoding/json"

var _ json.Number // suppress unused import

type FunctionsInventionsRecursiveResponseStreamingFunctionInventionRecursiveChunk struct {
	Created uint64 `json:"created"`
	ID string `json:"id"`
	Inventions []FunctionsInventionsRecursiveResponseStreamingFunctionInventionChunk `json:"inventions"`
	InventionsErrors *bool `json:"inventions_errors,omitempty"`
	Object FunctionsInventionsRecursiveResponseStreamingObject `json:"object"`
	Usage *AgentCompletionsResponseUsage `json:"usage,omitempty"`
}

func (FunctionsInventionsRecursiveResponseStreamingFunctionInventionRecursiveChunk) JSONSchema() map[string]any {
	return map[string]any{
		"title": "functions.inventions.recursive.response.streaming.FunctionInventionRecursiveChunk",
		"type": "object",
		"properties": map[string]any{
			"created": map[string]any{
			"type": "integer",
			"minimum": json.Number("0"),
			"maximum": json.Number("18446744073709551615"),
		},
			"id": map[string]any{
			"type": "string",
		},
			"inventions": map[string]any{
			"type": "array",
			"items": map[string]any{"$ref": "functions.inventions.recursive.response.streaming.FunctionInventionChunk"},
		},
			"inventions_errors": map[string]any{
			"anyOf": []any{map[string]any{"type": "boolean"}, map[string]any{"type": "null"}},
		},
			"object": map[string]any{
			"$ref": "functions.inventions.recursive.response.streaming.Object",
		},
			"usage": map[string]any{
			"anyOf": []any{map[string]any{"$ref": "agent.completions.response.Usage"}, map[string]any{"type": "null"}},
		},
		},
	}
}
