// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type FunctionsAlphaRemoteFunction = any

type FunctionsAlphaRemoteFunctionSchema struct{}

func (FunctionsAlphaRemoteFunctionSchema) JSONSchema() map[string]any {
	return map[string]any{
		"title": "functions.AlphaRemoteFunction",
		"anyOf": []any{
			map[string]any{
			"$ref": "functions.alpha_scalar.RemoteFunction",
		},
			map[string]any{
			"$ref": "functions.alpha_vector.RemoteFunction",
		},
		},
	}
}
