// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

// Capabilities for task creation and management.
type McpTasksCapability struct {
	// Present if the server supports cancelling tasks.
	Cancel *McpTasksCancelCapability `json:"cancel"`
	// Present if the server supports listing tasks.
	List *McpTasksListCapability `json:"list"`
	// Task creation capabilities for specific request types.
	Requests *McpTasksRequestsCapability `json:"requests"`
}

func (McpTasksCapability) SchemaTitle() string { return "mcp.TasksCapability" }
func (v McpTasksCapability) Validate() error {
	return variantValidator.Struct(v)
}
