// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type VectorCompletionsCacheCacheVote struct {
	Vote *VectorCompletionsResponseVote `json:"vote,omitempty"`
}

func (VectorCompletionsCacheCacheVote) JSONSchema() map[string]any {
	return map[string]any{
		"title": "vector.completions.cache.CacheVote",
		"type": "object",
		"properties": map[string]any{
			"vote": map[string]any{
			"anyOf": []any{map[string]any{"$ref": "vector.completions.response.Vote"}, map[string]any{"type": "null"}},
		},
		},
	}
}
