// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type VectorCompletionsResponseUnaryObject = string

type VectorCompletionsResponseUnaryObjectSchema struct{}

func (VectorCompletionsResponseUnaryObjectSchema) JSONSchema() map[string]any {
	return map[string]any{
		"title": "vector.completions.response.unary.Object",
		"description": "A complete vector completion response.",
		"type": "string",
		"enum": []any{"vector.completion"},
	}
}
