// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const FunctionsFunctionTypeSchema = z.enum(["scalar.function","vector.function"]).meta({ title: "functions.FunctionType" });
export type FunctionsFunctionType = z.infer<typeof FunctionsFunctionTypeSchema>;
