// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { FunctionsInlineAutoProfileSchema, type FunctionsInlineAutoProfile } from "./inlineAutoProfile";
import { FunctionsInlineTasksProfileSchema, type FunctionsInlineTasksProfile } from "./inlineTasksProfile";

export type FunctionsInlineProfile = FunctionsInlineTasksProfile | FunctionsInlineAutoProfile;
export const FunctionsInlineProfileSchema: z.ZodType<FunctionsInlineProfile> = z.union([FunctionsInlineTasksProfileSchema.describe("Tasks-based profile with per-task configuration."), FunctionsInlineAutoProfileSchema.describe("Auto profile that applies a single ensemble+weights to all vector completion tasks.")]).describe("An inline profile, either tasks-based or auto.").meta({ title: "functions.InlineProfile" });
