// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { VectorCompletionsRequestProfileSchema } from "../vector/completions/request/profile";
import { VectorCompletionsRequestSwarmSchema } from "../vector/completions/request/swarm";

export const FunctionsRemoteAutoProfileSchema = z.object({
  description: z.string().describe("Human-readable description of the profile."),
  profile: VectorCompletionsRequestProfileSchema.describe("Weights for each agent in the swarm."),
  swarm: VectorCompletionsRequestSwarmSchema.describe("The swarm to use for all vector completion tasks."),
}).describe("A remote auto profile with full metadata.\n\nApplies a single swarm and weights to every vector completion task\nin the function, with equal task weights.").meta({ title: "functions.RemoteAutoProfile" });
export type FunctionsRemoteAutoProfile = z.infer<typeof FunctionsRemoteAutoProfileSchema>;
