# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_task_profile_variant1():
    from objectiveai.functions import TaskProfileVariant1
    schema = TaskProfileVariant1.model_json_schema()
