# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_vector_function_task_variant2():
    from objectiveai.functions import VectorFunctionTaskVariant2
    schema = VectorFunctionTaskVariant2.model_json_schema()
