# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_scalar_function_task_expression_variant1_input():
    from objectiveai.functions import ScalarFunctionTaskExpressionVariant1Input
    schema = ScalarFunctionTaskExpressionVariant1Input.model_json_schema()
