# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_task_variant2_variant2():
    from objectiveai.functions import TaskVariant2Variant2
    schema = TaskVariant2Variant2.model_json_schema()
