# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_task_expression_variant3():
    from objectiveai.functions import TaskExpressionVariant3
    schema = TaskExpressionVariant3.model_json_schema()
