# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_alpha_remote_function_variant1():
    from objectiveai.functions import AlphaRemoteFunctionVariant1
    schema = AlphaRemoteFunctionVariant1.model_json_schema()
