# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_alpha_inline_function_variant1():
    from objectiveai.functions import AlphaInlineFunctionVariant1
    schema = AlphaInlineFunctionVariant1.model_json_schema()
