# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from objectiveai.functions import InlineFunctionVariant2

schema = InlineFunctionVariant2.model_json_schema()
