# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from objectiveai.functions import TaskExpressionVariant5Variant1

schema = TaskExpressionVariant5Variant1.model_json_schema()
