# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_task_expression_variant1_variant2():
    from objectiveai.functions import TaskExpressionVariant1Variant2
    schema = TaskExpressionVariant1Variant2.model_json_schema()
