# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_list_functions_source():
    from objectiveai.functions import ListFunctionsSource
    schema = ListFunctionsSource.model_json_schema()
