# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_scalar_function_task_expression_variant3_input_variant2():
    from objectiveai.functions import ScalarFunctionTaskExpressionVariant3InputVariant2
    schema = ScalarFunctionTaskExpressionVariant3InputVariant2.model_json_schema()
