# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_remote_profile_variant1():
    from objectiveai.functions import RemoteProfileVariant1
    schema = RemoteProfileVariant1.model_json_schema()
