# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from objectiveai.functions import TaskExpressionVariant1

schema = TaskExpressionVariant1.model_json_schema()
