# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Union
from pydantic import ConfigDict, RootModel
from objectiveai.agent.claude_agent_sdk.agent_base import AgentClaudeAgentSdkAgentBase
from objectiveai.agent.mock.agent_base import AgentMockAgentBase
from objectiveai.agent.openrouter.agent_base import AgentOpenrouterAgentBase


class AgentAgentBaseVariant1(RootModel):
    root: AgentOpenrouterAgentBase


class AgentAgentBaseVariant2(RootModel):
    root: AgentClaudeAgentSdkAgentBase


class AgentAgentBaseVariant3(RootModel):
    root: AgentMockAgentBase


class AgentAgentBase(RootModel):
    """The base configuration for an Agent (without computed ID).

This is an untagged enum that dispatches to the per-upstream AgentBase.
Deserialization tries each variant in order until one matches."""
    model_config = ConfigDict(title='agent.AgentBase')

    root: Union[AgentAgentBaseVariant1, AgentAgentBaseVariant2, AgentAgentBaseVariant3]

