# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional, Union
from pydantic import ConfigDict, Field, RootModel
from objectiveai.agent.claude_agent_sdk.agent_base import AgentBase as AgentClaudeAgentSdkAgentBase
from objectiveai.agent.inline_agent_base import InlineAgentBase
from objectiveai.agent.mock.agent_base import AgentBase as AgentMockAgentBase
from objectiveai.agent.openrouter.agent_base import AgentBase as AgentOpenrouterAgentBase


class InlineAgentBaseWithFallbacksVariant1(AgentOpenrouterAgentBase):
    fallbacks: Optional[list[InlineAgentBase]] = Field(None, description='Fallback agents to try if the primary fails.')


class InlineAgentBaseWithFallbacksVariant2(AgentClaudeAgentSdkAgentBase):
    fallbacks: Optional[list[InlineAgentBase]] = Field(None, description='Fallback agents to try if the primary fails.')


class InlineAgentBaseWithFallbacksVariant3(AgentMockAgentBase):
    fallbacks: Optional[list[InlineAgentBase]] = Field(None, description='Fallback agents to try if the primary fails.')


class InlineAgentBaseWithFallbacks(RootModel):
    """An [`InlineAgentBase`] with optional fallbacks (no description)."""
    model_config = ConfigDict(title='agent.InlineAgentBaseWithFallbacks', json_schema_extra={'_expanded_ref': 'agent.InlineAgentBase', '_expanded_ref_props': ['fallbacks']})

    root: Union[InlineAgentBaseWithFallbacksVariant1, InlineAgentBaseWithFallbacksVariant2, InlineAgentBaseWithFallbacksVariant3]

