# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from pydantic import BaseModel, Field


class AgentMcpServer(BaseModel):
    """An MCP server that the agent can connect to."""
    url: str = Field(..., description='The URL of the MCP server.')
    authorization: bool = Field(False, description='Whether this MCP server uses authorization.')

