# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from pydantic import BaseModel, Field


class AgentUsageAgent(BaseModel):
    """Usage statistics for an Agent."""
    requests: int = Field(..., description='Total number of requests made with this Agent.', ge=0, json_schema_extra={'format': 'uint64'})
    completion_tokens: int = Field(..., description='Total completion tokens generated.', ge=0, json_schema_extra={'format': 'uint64'})
    prompt_tokens: int = Field(..., description='Total prompt tokens processed.', ge=0, json_schema_extra={'format': 'uint64'})
    total_cost: float = Field(..., description='Total cost incurred.', json_schema_extra={'format': 'double'})

