// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package streaming

type FunctionProfileComputationChunk struct {
	Created uint64 `json:"created" min:"0" max:"18446744073709551615"`
	Executions []any `json:"executions" items_ref:"functions.profiles.computations.response.streaming.FunctionExecutionChunk"`
	ExecutionsErrors *bool `json:"executions_errors,omitempty" nullable:"true"`
	FittingStats any `json:"fitting_stats,omitempty" nullable:"true" ref:"functions.profiles.computations.response.FittingStats"`
	Function *string `json:"function,omitempty" nullable:"true"`
	ID string `json:"id"`
	Object any `json:"object" ref:"functions.profiles.computations.response.streaming.Object"`
	Profile any `json:"profile,omitempty" nullable:"true" ref:"functions.InlineTasksProfile"`
	RetryToken *string `json:"retry_token,omitempty" nullable:"true"`
	Usage any `json:"usage,omitempty" nullable:"true" ref:"agent.completions.response.Usage"`
}

func (FunctionProfileComputationChunk) SchemaTitle() string { return "functions.profiles.computations.response.streaming.FunctionProfileComputationChunk" }
func (FunctionProfileComputationChunk) SchemaDescription() string { return "" }
