// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

// OpenRouter upstream marker.
type AgentOpenrouterUpstream struct {
	// OpenRouter upstream marker.
	Variant1 string `validate:"oneof=openrouter"`
}

func (v AgentOpenrouterUpstream) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.Variant1)
}

func (v *AgentOpenrouterUpstream) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.Variant1); err != nil {
		return err
	}
	return v.Validate()
}

func (v AgentOpenrouterUpstream) Validate() error {
	return variantValidator.Struct(v)
}

type AgentOpenrouterUpstreamSchema struct{}

func (AgentOpenrouterUpstreamSchema) SchemaTitle() string { return "agent.openrouter.Upstream" }
func (AgentOpenrouterUpstreamSchema) SchemaDescription() string { return "OpenRouter upstream marker." }
func (AgentOpenrouterUpstreamSchema) Body() map[string]any {
	return map[string]any{
		"type": "string",
		"enum": []any{"openrouter"},
	}
}
