// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

// A validated remote agent with description and optional fallbacks.
type AgentRemoteAgentWithFallbacks struct {
	AgentInlineAgentWithFallbacks
	Description string `json:"description"`
}

func (AgentRemoteAgentWithFallbacks) SchemaTitle() string { return "agent.RemoteAgentWithFallbacks" }
func (v AgentRemoteAgentWithFallbacks) Validate() error {
	return variantValidator.Struct(v)
}
