// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

// The reason the model stopped generating.
type AgentCompletionsResponseFinishReason struct {
	// The model reached a natural stop point or stop sequence.
	Stop *string `validate:"oneof=stop"`
	// The model reached the maximum token limit.
	Length *string `validate:"oneof=length"`
	// The model decided to call one or more tools.
	ToolCalls *string `validate:"oneof=tool_calls"`
	// The response was filtered due to content policy.
	ContentFilter *string `validate:"oneof=content_filter"`
	// An error occurred during generation.
	Error *string `validate:"oneof=error"`
}

func (v AgentCompletionsResponseFinishReason) MarshalJSON() ([]byte, error) {
	if v.Stop != nil {
		return json.Marshal(v.Stop)
	}
	if v.Length != nil {
		return json.Marshal(v.Length)
	}
	if v.ToolCalls != nil {
		return json.Marshal(v.ToolCalls)
	}
	if v.ContentFilter != nil {
		return json.Marshal(v.ContentFilter)
	}
	if v.Error != nil {
		return json.Marshal(v.Error)
	}
	return []byte("null"), nil
}

func (v *AgentCompletionsResponseFinishReason) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return nil
	}
	{
		var try string
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := AgentCompletionsResponseFinishReason{}
			candidate.Stop = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try string
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := AgentCompletionsResponseFinishReason{}
			candidate.Length = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try string
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := AgentCompletionsResponseFinishReason{}
			candidate.ToolCalls = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try string
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := AgentCompletionsResponseFinishReason{}
			candidate.ContentFilter = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try string
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := AgentCompletionsResponseFinishReason{}
			candidate.Error = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	return fmt.Errorf("data did not match any variant of AgentCompletionsResponseFinishReason")
}

func (v AgentCompletionsResponseFinishReason) Validate() error {
	count := 0
	if v.Stop != nil { count++ }
	if v.Length != nil { count++ }
	if v.ToolCalls != nil { count++ }
	if v.ContentFilter != nil { count++ }
	if v.Error != nil { count++ }
	if count != 1 {
		return fmt.Errorf("AgentCompletionsResponseFinishReason: exactly one variant must be set, got %d", count)
	}
	return variantValidator.Struct(v)
}

