// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

// Detailed cost breakdown.
type AgentCompletionsResponseCostDetails struct {
	// Cost charged by the immediate upstream (e.g., OpenRouter).
	UpstreamInferenceCost float64 `json:"upstream_inference_cost" validate:"min=-3.4028234663852886e+38,max=3.4028234663852886e+38"`
	// Cost charged by the upstream's upstream (e.g., the actual model provider).
	UpstreamUpstreamInferenceCost float64 `json:"upstream_upstream_inference_cost" validate:"min=-3.4028234663852886e+38,max=3.4028234663852886e+38"`
}

func (AgentCompletionsResponseCostDetails) SchemaTitle() string { return "agent.completions.response.CostDetails" }
func (v AgentCompletionsResponseCostDetails) Validate() error {
	return variantValidator.Struct(v)
}
