// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

// Response containing a single Agent with creation timestamp.
type AgentGetAgentResponse any

func (AgentGetAgentResponse) SchemaTitle() string { return "agent.GetAgentResponse" }
