// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

// A validated remote Agent with metadata and computed content-addressed ID.
type AgentRemoteAgent struct {
	AgentInlineAgent
	Description string `json:"description"`
}

func (AgentRemoteAgent) SchemaTitle() string { return "agent.RemoteAgent" }
func (v AgentRemoteAgent) Validate() error {
	return variantValidator.Struct(v)
}
