// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

// Expression variant of [`AssistantToolCallFunction`] for dynamic content.
type AgentCompletionsMessageAssistantToolCallFunctionExpression struct {
	// The arguments expression.
	//
	// A value that can be either a literal or an expression.
	//
	// This allows Function definitions to mix static values with dynamic
	// expressions. During compilation, expressions are evaluated while
	// literal values pass through unchanged.
	//
	// # Example
	//
	// Literal value:
	// ```json
	// "hello world"
	// ```
	//
	// JMESPath expression:
	// ```json
	// {"$jmespath": "input.greeting"}
	// ```
	//
	// Starlark expression:
	// ```json
	// {"$starlark": "input['greeting']"}
	// ```
	Arguments any `json:"arguments"`
	// The function name expression.
	//
	// A value that can be either a literal or an expression.
	//
	// This allows Function definitions to mix static values with dynamic
	// expressions. During compilation, expressions are evaluated while
	// literal values pass through unchanged.
	//
	// # Example
	//
	// Literal value:
	// ```json
	// "hello world"
	// ```
	//
	// JMESPath expression:
	// ```json
	// {"$jmespath": "input.greeting"}
	// ```
	//
	// Starlark expression:
	// ```json
	// {"$starlark": "input['greeting']"}
	// ```
	Name any `json:"name"`
}

func (v AgentCompletionsMessageAssistantToolCallFunctionExpression) Validate() error {
	return variantValidator.Struct(v)
}
