// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

type AgentCompletionsResponseToolRole struct {
	Agent.completions.response.ToolRole string `validate:"oneof=tool"`
}

func (v AgentCompletionsResponseToolRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.Agent.completions.response.ToolRole)
}

func (v *AgentCompletionsResponseToolRole) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.Agent.completions.response.ToolRole); err != nil {
		return err
	}
	return v.Validate()
}

func (v AgentCompletionsResponseToolRole) Validate() error {
	return variantValidator.Struct(v)
}

