// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

// An [`InlineAgentBase`] with optional fallbacks (no description).
type AgentInlineAgentBaseWithFallbacks struct {
	AgentInlineAgentBase
	// Fallback agents to try if the primary fails.
	Fallbacks []AgentInlineAgentBase `json:"fallbacks,omitempty"`
}

func (AgentInlineAgentBaseWithFallbacks) SchemaTitle() string { return "agent.InlineAgentBaseWithFallbacks" }
func (v AgentInlineAgentBaseWithFallbacks) Validate() error {
	return variantValidator.Struct(v)
}
