// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

// Data collection policy for providers.
type AgentCompletionsRequestProviderDataCollection struct {
	// Do not allow data collection.
	Variant1 *string `validate:"oneof=deny"`
	// Allow data collection.
	Variant2 *string `validate:"oneof=allow"`
}

func (v AgentCompletionsRequestProviderDataCollection) MarshalJSON() ([]byte, error) {
	if v.Variant1 != nil {
		return json.Marshal(v.Variant1)
	}
	if v.Variant2 != nil {
		return json.Marshal(v.Variant2)
	}
	return []byte("null"), nil
}

func (v *AgentCompletionsRequestProviderDataCollection) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return nil
	}
	{
		var try string
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := AgentCompletionsRequestProviderDataCollection{}
			candidate.Variant1 = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try string
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := AgentCompletionsRequestProviderDataCollection{}
			candidate.Variant2 = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	return fmt.Errorf("data did not match any variant of AgentCompletionsRequestProviderDataCollection")
}

func (v AgentCompletionsRequestProviderDataCollection) Validate() error {
	count := 0
	if v.Variant1 != nil { count++ }
	if v.Variant2 != nil { count++ }
	if count != 1 {
		return fmt.Errorf("AgentCompletionsRequestProviderDataCollection: exactly one variant must be set, got %d", count)
	}
	return variantValidator.Struct(v)
}

type AgentCompletionsRequestProviderDataCollectionSchema struct{}

func (AgentCompletionsRequestProviderDataCollectionSchema) SchemaTitle() string { return "agent.completions.request.ProviderDataCollection" }
func (AgentCompletionsRequestProviderDataCollectionSchema) SchemaDescription() string { return "Data collection policy for providers." }
func (AgentCompletionsRequestProviderDataCollectionSchema) Body() map[string]any {
	return map[string]any{
		"anyOf": []any{
			map[string]any{
			"description": "Do not allow data collection.",
			"type": "string",
			"enum": []any{"deny"},
		},
			map[string]any{
			"description": "Allow data collection.",
			"type": "string",
			"enum": []any{"allow"},
		},
		},
	}
}
