// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

// The function expression.
//
// A value that can be either a literal or an expression.
//
// This allows Function definitions to mix static values with dynamic
// expressions. During compilation, expressions are evaluated while
// literal values pass through unchanged.
//
// # Example
//
// Literal value:
// ```json
// "hello world"
// ```
//
// JMESPath expression:
// ```json
// {"$jmespath": "input.greeting"}
// ```
//
// Starlark expression:
// ```json
// {"$starlark": "input['greeting']"}
// ```
type AgentCompletionsMessageAssistantToolCallExpressionFunction struct {
	// An expression (JMESPath or Starlark) to evaluate.
	Expression *FunctionsExpressionExpression 
	// A literal value.
	Value *AgentCompletionsMessageAssistantToolCallFunctionExpression 
}

func (v AgentCompletionsMessageAssistantToolCallExpressionFunction) MarshalJSON() ([]byte, error) {
	if v.Expression != nil {
		return json.Marshal(v.Expression)
	}
	if v.Value != nil {
		return json.Marshal(v.Value)
	}
	return []byte("null"), nil
}

func (v *AgentCompletionsMessageAssistantToolCallExpressionFunction) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return nil
	}
	{
		var try FunctionsExpressionExpression
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := AgentCompletionsMessageAssistantToolCallExpressionFunction{}
			candidate.Expression = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try AgentCompletionsMessageAssistantToolCallFunctionExpression
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := AgentCompletionsMessageAssistantToolCallExpressionFunction{}
			candidate.Value = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	return fmt.Errorf("data did not match any variant of AgentCompletionsMessageAssistantToolCallExpressionFunction")
}

func (v AgentCompletionsMessageAssistantToolCallExpressionFunction) Validate() error {
	count := 0
	if v.Expression != nil { count++ }
	if v.Value != nil { count++ }
	if count != 1 {
		return fmt.Errorf("AgentCompletionsMessageAssistantToolCallExpressionFunction: exactly one variant must be set, got %d", count)
	}
	return variantValidator.Struct(v)
}
type AgentCompletionsMessageAssistantToolCallExpressionIDValue string

func (AgentCompletionsMessageAssistantToolCallExpressionIDValue) SchemaVariantTitle() string { return "Value" }

// The tool call ID expression.
//
// A value that can be either a literal or an expression.
//
// This allows Function definitions to mix static values with dynamic
// expressions. During compilation, expressions are evaluated while
// literal values pass through unchanged.
//
// # Example
//
// Literal value:
// ```json
// "hello world"
// ```
//
// JMESPath expression:
// ```json
// {"$jmespath": "input.greeting"}
// ```
//
// Starlark expression:
// ```json
// {"$starlark": "input['greeting']"}
// ```
type AgentCompletionsMessageAssistantToolCallExpressionID struct {
	// An expression (JMESPath or Starlark) to evaluate.
	Expression *FunctionsExpressionExpression 
	// A literal value.
	Value *AgentCompletionsMessageAssistantToolCallExpressionIDValue 
}

func (v AgentCompletionsMessageAssistantToolCallExpressionID) MarshalJSON() ([]byte, error) {
	if v.Expression != nil {
		return json.Marshal(v.Expression)
	}
	if v.Value != nil {
		return json.Marshal(v.Value)
	}
	return []byte("null"), nil
}

func (v *AgentCompletionsMessageAssistantToolCallExpressionID) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return nil
	}
	{
		var try FunctionsExpressionExpression
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := AgentCompletionsMessageAssistantToolCallExpressionID{}
			candidate.Expression = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try AgentCompletionsMessageAssistantToolCallExpressionIDValue
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := AgentCompletionsMessageAssistantToolCallExpressionID{}
			candidate.Value = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	return fmt.Errorf("data did not match any variant of AgentCompletionsMessageAssistantToolCallExpressionID")
}

func (v AgentCompletionsMessageAssistantToolCallExpressionID) Validate() error {
	count := 0
	if v.Expression != nil { count++ }
	if v.Value != nil { count++ }
	if count != 1 {
		return fmt.Errorf("AgentCompletionsMessageAssistantToolCallExpressionID: exactly one variant must be set, got %d", count)
	}
	return variantValidator.Struct(v)
}
// A function call expression.
type AgentCompletionsMessageAssistantToolCallExpression struct {
	// The function expression.
	//
	// A value that can be either a literal or an expression.
	//
	// This allows Function definitions to mix static values with dynamic
	// expressions. During compilation, expressions are evaluated while
	// literal values pass through unchanged.
	//
	// # Example
	//
	// Literal value:
	// ```json
	// "hello world"
	// ```
	//
	// JMESPath expression:
	// ```json
	// {"$jmespath": "input.greeting"}
	// ```
	//
	// Starlark expression:
	// ```json
	// {"$starlark": "input['greeting']"}
	// ```
	Function AgentCompletionsMessageAssistantToolCallExpressionFunction `json:"function"`
	// The tool call ID expression.
	//
	// A value that can be either a literal or an expression.
	//
	// This allows Function definitions to mix static values with dynamic
	// expressions. During compilation, expressions are evaluated while
	// literal values pass through unchanged.
	//
	// # Example
	//
	// Literal value:
	// ```json
	// "hello world"
	// ```
	//
	// JMESPath expression:
	// ```json
	// {"$jmespath": "input.greeting"}
	// ```
	//
	// Starlark expression:
	// ```json
	// {"$starlark": "input['greeting']"}
	// ```
	ID AgentCompletionsMessageAssistantToolCallExpressionID `json:"id"`
	Type string `json:"type" validate:"oneof=function"`
}

func (AgentCompletionsMessageAssistantToolCallExpression) SchemaTitle() string { return "agent.completions.message.AssistantToolCallExpression" }
func (v AgentCompletionsMessageAssistantToolCallExpression) Validate() error {
	return variantValidator.Struct(v)
}
