// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

// How to sort/prioritize providers.
type AgentCompletionsRequestProviderSort struct {
	// Prioritize by price (cheapest first).
	Price *string `validate:"oneof=price"`
	// Prioritize by throughput (fastest first).
	Throughput *string `validate:"oneof=throughput"`
	// Prioritize by latency (lowest first).
	Latency *string `validate:"oneof=latency"`
}

func (v AgentCompletionsRequestProviderSort) MarshalJSON() ([]byte, error) {
	if v.Price != nil {
		return json.Marshal(v.Price)
	}
	if v.Throughput != nil {
		return json.Marshal(v.Throughput)
	}
	if v.Latency != nil {
		return json.Marshal(v.Latency)
	}
	return []byte("null"), nil
}

func (v *AgentCompletionsRequestProviderSort) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return nil
	}
	{
		var try string
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := AgentCompletionsRequestProviderSort{}
			candidate.Price = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try string
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := AgentCompletionsRequestProviderSort{}
			candidate.Throughput = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try string
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := AgentCompletionsRequestProviderSort{}
			candidate.Latency = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	return fmt.Errorf("data did not match any variant of AgentCompletionsRequestProviderSort")
}

func (v AgentCompletionsRequestProviderSort) Validate() error {
	count := 0
	if v.Price != nil { count++ }
	if v.Throughput != nil { count++ }
	if v.Latency != nil { count++ }
	if count != 1 {
		return fmt.Errorf("AgentCompletionsRequestProviderSort: exactly one variant must be set, got %d", count)
	}
	return variantValidator.Struct(v)
}

