// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

// A text part.
type AgentCompletionsMessageSimpleContentPart struct {
	// The text content.
	Text string `json:"text"`
	Type string `json:"type" validate:"oneof=text"`
}

func (v AgentCompletionsMessageSimpleContentPart) Validate() error {
	return variantValidator.Struct(v)
}
