// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

// A developer message (similar to system, but from the developer).
type AgentCompletionsMessageMessageDeveloper struct {
	AgentCompletionsMessageDeveloperMessage
	Role string `json:"role" validate:"oneof=developer"`
}
func (AgentCompletionsMessageMessageDeveloper) SchemaVariantTitle() string { return "Developer" }

// A system message setting context or instructions.
type AgentCompletionsMessageMessageSystem struct {
	AgentCompletionsMessageSystemMessage
	Role string `json:"role" validate:"oneof=system"`
}
func (AgentCompletionsMessageMessageSystem) SchemaVariantTitle() string { return "System" }

// A user message from the end user.
type AgentCompletionsMessageMessageUser struct {
	AgentCompletionsMessageUserMessage
	Role string `json:"role" validate:"oneof=user"`
}
func (AgentCompletionsMessageMessageUser) SchemaVariantTitle() string { return "User" }

// An assistant message (model's previous response).
type AgentCompletionsMessageMessageAssistant struct {
	AgentCompletionsMessageAssistantMessage
	Role string `json:"role" validate:"oneof=assistant"`
}
func (AgentCompletionsMessageMessageAssistant) SchemaVariantTitle() string { return "Assistant" }

// A tool message containing the result of a tool call.
type AgentCompletionsMessageMessageTool struct {
	AgentCompletionsMessageToolMessage
	Role string `json:"role" validate:"oneof=tool"`
}
func (AgentCompletionsMessageMessageTool) SchemaVariantTitle() string { return "Tool" }

// A message in the conversation.
type AgentCompletionsMessageMessage struct {
	// A developer message (similar to system, but from the developer).
	Developer *AgentCompletionsMessageMessageDeveloper 
	// A system message setting context or instructions.
	System *AgentCompletionsMessageMessageSystem 
	// A user message from the end user.
	User *AgentCompletionsMessageMessageUser 
	// An assistant message (model's previous response).
	Assistant *AgentCompletionsMessageMessageAssistant 
	// A tool message containing the result of a tool call.
	Tool *AgentCompletionsMessageMessageTool 
}

func (v AgentCompletionsMessageMessage) MarshalJSON() ([]byte, error) {
	if v.Developer != nil {
		return json.Marshal(v.Developer)
	}
	if v.System != nil {
		return json.Marshal(v.System)
	}
	if v.User != nil {
		return json.Marshal(v.User)
	}
	if v.Assistant != nil {
		return json.Marshal(v.Assistant)
	}
	if v.Tool != nil {
		return json.Marshal(v.Tool)
	}
	return []byte("null"), nil
}

func (v *AgentCompletionsMessageMessage) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return nil
	}
	{
		var try AgentCompletionsMessageMessageDeveloper
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := AgentCompletionsMessageMessage{}
			candidate.Developer = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try AgentCompletionsMessageMessageSystem
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := AgentCompletionsMessageMessage{}
			candidate.System = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try AgentCompletionsMessageMessageUser
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := AgentCompletionsMessageMessage{}
			candidate.User = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try AgentCompletionsMessageMessageAssistant
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := AgentCompletionsMessageMessage{}
			candidate.Assistant = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try AgentCompletionsMessageMessageTool
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := AgentCompletionsMessageMessage{}
			candidate.Tool = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	return fmt.Errorf("data did not match any variant of AgentCompletionsMessageMessage")
}

func (v AgentCompletionsMessageMessage) Validate() error {
	count := 0
	if v.Developer != nil { count++ }
	if v.System != nil { count++ }
	if v.User != nil { count++ }
	if v.Assistant != nil { count++ }
	if v.Tool != nil { count++ }
	if count != 1 {
		return fmt.Errorf("AgentCompletionsMessageMessage: exactly one variant must be set, got %d", count)
	}
	return variantValidator.Struct(v)
}
func (AgentCompletionsMessageMessage) SchemaTitle() string { return "agent.completions.message.Message" }

