// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

// Response containing the user's OpenRouter BYOK API key.
type AuthGetOpenRouterByokApiKeyResponse struct {
	// The OpenRouter API key, or `None` if not configured.
	APIKey *string `json:"api_key,omitempty"`
}

func (AuthGetOpenRouterByokApiKeyResponse) SchemaTitle() string { return "auth.GetOpenRouterByokApiKeyResponse" }
func (AuthGetOpenRouterByokApiKeyResponse) SchemaDescription() string { return "Response containing the user's OpenRouter BYOK API key." }
func (AuthGetOpenRouterByokApiKeyResponse) FieldDescriptions() map[string]string {
	return map[string]string{
		"api_key": "The OpenRouter API key, or `None` if not configured.",
	}
}
func (v AuthGetOpenRouterByokApiKeyResponse) Validate() error {
	return variantValidator.Struct(v)
}
