// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"time"
)

// Request to create a new API key.
//
// # Fields
//
// * `expires` - Optional expiration timestamp. If `None`, the key never expires.
// * `name` - A user-provided name for identifying the key.
// * `description` - Optional description providing additional context.
type AuthCreateApiKeyRequest struct {
	// An optional description providing additional context about the key's purpose.
	Description *string `json:"description,omitempty"`
	// The expiration timestamp for the API key, or `None` for a non-expiring key.
	Expires *time.Time `json:"expires,omitempty"`
	// A user-provided name to identify this API key.
	Name string `json:"name"`
}

func (AuthCreateApiKeyRequest) SchemaTitle() string { return "auth.CreateApiKeyRequest" }
func (v AuthCreateApiKeyRequest) Validate() error {
	return variantValidator.Struct(v)
}
