// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type ConfigFavorite struct {
	RemotePathCommitOptional
	Name string `json:"name"`
	Note string `json:"note"`
}

func (ConfigFavorite) SchemaTitle() string { return "config.Favorite" }
func (v ConfigFavorite) Validate() error {
	return variantValidator.Struct(v)
}
