// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type ConfigApiConfig struct {
	Headers *ConfigApiHeadersConfig `json:"headers,omitempty"`
	Local *ConfigApiLocalConfig `json:"local,omitempty"`
	Mode ConfigApiMode `json:"mode,omitempty"`
	Remote *ConfigApiRemoteConfig `json:"remote,omitempty"`
}

func (v ConfigApiConfig) Validate() error {
	return variantValidator.Struct(v)
}
