// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

// A generated secret/signature pair for viewer authentication.
//
// The viewer server stores the `secret`. The API client stores the `signature`.
// The signature is `sha256=<hex of SHA256(secret)>`. The viewer server validates
// by computing SHA256(secret) and comparing against the incoming header value.
// Knowing the signature does not reveal the secret (preimage resistance).
type ConfigViewerSecretSignaturePair struct {
	// The secret for the viewer server.
	Secret string `json:"secret"`
	// The pre-computed signature for the API client (`sha256=<hex>`).
	Signature string `json:"signature"`
}

func (v ConfigViewerSecretSignaturePair) Validate() error {
	return variantValidator.Struct(v)
}
