// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

// Response containing a single Ensemble with creation timestamp.
type EnsembleGetEnsemble struct {
	EnsembleEnsemble
	// Unix timestamp when this Ensemble was first used.
	Created uint64 `json:"created" validate:"min=0,max=18446744073709551615"`
}

func (EnsembleGetEnsemble) SchemaTitle() string { return "ensemble.GetEnsemble" }
func (EnsembleGetEnsemble) SchemaDescription() string { return "Response containing a single Ensemble with creation timestamp." }
func (EnsembleGetEnsemble) FieldDescriptions() map[string]string {
	return map[string]string{
		"created": "Unix timestamp when this Ensemble was first used.",
	}
}
func (v EnsembleGetEnsemble) Validate() error {
	return variantValidator.Struct(v)
}

func (EnsembleGetEnsemble) Body() map[string]any {
	return map[string]any{
		"$ref": "ensemble.Ensemble",
	}
}
