// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

type FunctionsExpressionImageInputSchemaType struct {
	Functions.expression.ImageInputSchemaType string `validate:"oneof=image"`
}

func (v FunctionsExpressionImageInputSchemaType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.Functions.expression.ImageInputSchemaType)
}

func (v *FunctionsExpressionImageInputSchemaType) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.Functions.expression.ImageInputSchemaType); err != nil {
		return err
	}
	return v.Validate()
}

func (v FunctionsExpressionImageInputSchemaType) Validate() error {
	return variantValidator.Struct(v)
}

