// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

type FunctionsAlphaVectorVectorFunctionTaskExpression struct {
	RemotePath
	Input FunctionsAlphaVectorExpressionVectorFunctionInputValueExpression `json:"input"`
	Skip *FunctionsExpressionExpression `json:"skip,omitempty"`
}

func (FunctionsAlphaVectorVectorFunctionTaskExpression) SchemaTitle() string { return "functions.alpha_vector.VectorFunctionTaskExpression" }
func (v FunctionsAlphaVectorVectorFunctionTaskExpression) Validate() error {
	return variantValidator.Struct(v)
}

func (v *FunctionsAlphaVectorVectorFunctionTaskExpression) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	for _, key := range []string{"input"} {
		if _, ok := raw[key]; !ok {
			return fmt.Errorf("FunctionsAlphaVectorVectorFunctionTaskExpression: missing required field %q", key)
		}
	}
	type Alias FunctionsAlphaVectorVectorFunctionTaskExpression
	var alias Alias
	if err := json.Unmarshal(data, &alias); err != nil {
		return err
	}
	*v = FunctionsAlphaVectorVectorFunctionTaskExpression(alias)
	return nil
}
