// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

type FunctionsProfilesComputationsResponseStreamingObject struct {
	Functions.profiles.computations.response.streaming.Object string `validate:"oneof=function.profile.computation.chunk"`
}

func (v FunctionsProfilesComputationsResponseStreamingObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.Functions.profiles.computations.response.streaming.Object)
}

func (v *FunctionsProfilesComputationsResponseStreamingObject) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.Functions.profiles.computations.response.streaming.Object); err != nil {
		return err
	}
	return v.Validate()
}

func (v FunctionsProfilesComputationsResponseStreamingObject) Validate() error {
	return variantValidator.Struct(v)
}

