// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type FunctionsInventionsEssayTasksObject struct {
	EssayTasks string `json:"essay_tasks"`
}

func (FunctionsInventionsEssayTasksObject) SchemaTitle() string { return "functions.inventions.EssayTasksObject" }
func (v FunctionsInventionsEssayTasksObject) Validate() error {
	return variantValidator.Struct(v)
}
