// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

// An input value that may contain expressions (pre-compilation).
//
// Similar to [`InputValue`] but object values and array elements can be
// expressions (JMESPath or Starlark) that are evaluated during compilation.
type FunctionsExpressionInputValueExpression struct {
	// Rich content (image, audio, video, file).
	Variant1 *AgentCompletionsMessageRichContentPart 
	// An object with values that may be expressions.
	Variant2 map[string]any 
	// An array with elements that may be expressions.
	Variant3 []any 
	// A string value.
	Variant4 *string 
	// An integer value.
	Variant5 *int64 `validate:"min=-9223372036854775808,max=9223372036854775807"`
	// A floating-point number.
	Variant6 *float64 `validate:"min=-3.4028234663852886e+38,max=3.4028234663852886e+38"`
	// A boolean value.
	Variant7 *bool 
}

func (v FunctionsExpressionInputValueExpression) MarshalJSON() ([]byte, error) {
	if v.Variant1 != nil {
		return json.Marshal(v.Variant1)
	}
	if v.Variant2 != nil {
		return json.Marshal(v.Variant2)
	}
	if v.Variant3 != nil {
		return json.Marshal(v.Variant3)
	}
	if v.Variant4 != nil {
		return json.Marshal(v.Variant4)
	}
	if v.Variant5 != nil {
		return json.Marshal(v.Variant5)
	}
	if v.Variant6 != nil {
		return json.Marshal(v.Variant6)
	}
	if v.Variant7 != nil {
		return json.Marshal(v.Variant7)
	}
	return []byte("null"), nil
}

func (v *FunctionsExpressionInputValueExpression) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return nil
	}
	{
		var try AgentCompletionsMessageRichContentPart
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := FunctionsExpressionInputValueExpression{}
			candidate.Variant1 = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try map[string]any
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := FunctionsExpressionInputValueExpression{}
			candidate.Variant2 = try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try []any
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := FunctionsExpressionInputValueExpression{}
			candidate.Variant3 = try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try string
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := FunctionsExpressionInputValueExpression{}
			candidate.Variant4 = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try int64
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := FunctionsExpressionInputValueExpression{}
			candidate.Variant5 = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try float64
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := FunctionsExpressionInputValueExpression{}
			candidate.Variant6 = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try bool
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := FunctionsExpressionInputValueExpression{}
			candidate.Variant7 = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	return fmt.Errorf("data did not match any variant of FunctionsExpressionInputValueExpression")
}

func (v FunctionsExpressionInputValueExpression) Validate() error {
	count := 0
	if v.Variant1 != nil { count++ }
	if v.Variant2 != nil { count++ }
	if v.Variant3 != nil { count++ }
	if v.Variant4 != nil { count++ }
	if v.Variant5 != nil { count++ }
	if v.Variant6 != nil { count++ }
	if v.Variant7 != nil { count++ }
	if count != 1 {
		return fmt.Errorf("FunctionsExpressionInputValueExpression: exactly one variant must be set, got %d", count)
	}
	return variantValidator.Struct(v)
}

type FunctionsExpressionInputValueExpressionSchema struct{}

func (FunctionsExpressionInputValueExpressionSchema) SchemaTitle() string { return "functions.expression.InputValueExpression" }
func (FunctionsExpressionInputValueExpressionSchema) SchemaDescription() string { return "An input value that may contain expressions (pre-compilation).\n\nSimilar to [`InputValue`] but object values and array elements can be\nexpressions (JMESPath or Starlark) that are evaluated during compilation." }
func (FunctionsExpressionInputValueExpressionSchema) Body() map[string]any {
	return map[string]any{
		"anyOf": []any{
			map[string]any{
			"description": "Rich content (image, audio, video, file).",
			"$ref": "agent.completions.message.RichContentPart",
		},
			map[string]any{
			"description": "An object with values that may be expressions.",
			"type": "object",
			"additionalProperties": map[string]any{"anyOf": []any{map[string]any{"$ref": "functions.expression.Expression", "description": "An expression (JMESPath or Starlark) to evaluate."}, map[string]any{"$ref": "functions.expression.InputValueExpression", "description": "A literal value."}}, "description": "A value that can be either a literal or an expression.\n\nThis allows Function definitions to mix static values with dynamic\nexpressions. During compilation, expressions are evaluated while\nliteral values pass through unchanged.\n\n# Example\n\nLiteral value:\n```json\n\"hello world\"\n```\n\nJMESPath expression:\n```json\n{\"$jmespath\": \"input.greeting\"}\n```\n\nStarlark expression:\n```json\n{\"$starlark\": \"input['greeting']\"}\n```"},
		},
			map[string]any{
			"description": "An array with elements that may be expressions.",
			"type": "array",
			"items": map[string]any{"anyOf": []any{map[string]any{"$ref": "functions.expression.Expression", "description": "An expression (JMESPath or Starlark) to evaluate."}, map[string]any{"$ref": "functions.expression.InputValueExpression", "description": "A literal value."}}, "description": "A value that can be either a literal or an expression.\n\nThis allows Function definitions to mix static values with dynamic\nexpressions. During compilation, expressions are evaluated while\nliteral values pass through unchanged.\n\n# Example\n\nLiteral value:\n```json\n\"hello world\"\n```\n\nJMESPath expression:\n```json\n{\"$jmespath\": \"input.greeting\"}\n```\n\nStarlark expression:\n```json\n{\"$starlark\": \"input['greeting']\"}\n```"},
		},
			map[string]any{
			"description": "A string value.",
			"type": "string",
		},
			map[string]any{
			"description": "An integer value.",
			"type": "integer",
			"minimum": json.Number("-9223372036854775808"),
			"maximum": json.Number("9223372036854775807"),
		},
			map[string]any{
			"description": "A floating-point number.",
			"type": "number",
			"minimum": json.Number("-3.4028234663852886e+38"),
			"maximum": json.Number("3.4028234663852886e+38"),
		},
			map[string]any{
			"description": "A boolean value.",
			"type": "boolean",
		},
		},
	}
}
