// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

type FunctionsExpressionVideoInputSchemaType struct {
	Functions.expression.VideoInputSchemaType string `validate:"oneof=video"`
}

func (v FunctionsExpressionVideoInputSchemaType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.Functions.expression.VideoInputSchemaType)
}

func (v *FunctionsExpressionVideoInputSchemaType) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.Functions.expression.VideoInputSchemaType); err != nil {
		return err
	}
	return v.Validate()
}

func (v FunctionsExpressionVideoInputSchemaType) Validate() error {
	return variantValidator.Struct(v)
}

