// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

type FunctionsExecutionsResponseUnaryObject struct {
	Functions.executions.response.unary.Object string `validate:"oneof=scalar.function.execution vector.function.execution"`
}

func (v FunctionsExecutionsResponseUnaryObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.Functions.executions.response.unary.Object)
}

func (v *FunctionsExecutionsResponseUnaryObject) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.Functions.executions.response.unary.Object); err != nil {
		return err
	}
	return v.Validate()
}

func (v FunctionsExecutionsResponseUnaryObject) Validate() error {
	return variantValidator.Struct(v)
}

