// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type FunctionsExecutionsRequestReasoning struct {
	Agent AgentInlineAgentBaseWithFallbacksOrRemoteCommitOptional `json:"agent"`
}

func (FunctionsExecutionsRequestReasoning) SchemaTitle() string { return "functions.executions.request.Reasoning" }
func (v FunctionsExecutionsRequestReasoning) Validate() error {
	return variantValidator.Struct(v)
}
