// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

type FunctionsExpressionArrayInputSchemaType struct {
	Functions.expression.ArrayInputSchemaType string `validate:"oneof=array"`
}

func (v FunctionsExpressionArrayInputSchemaType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.Functions.expression.ArrayInputSchemaType)
}

func (v *FunctionsExpressionArrayInputSchemaType) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.Functions.expression.ArrayInputSchemaType); err != nil {
		return err
	}
	return v.Validate()
}

func (v FunctionsExpressionArrayInputSchemaType) Validate() error {
	return variantValidator.Struct(v)
}

