// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

// Response from listing function-profile pairs.
type FunctionsListFunctionProfilePairResponse struct {
	// List of available function-profile pairs.
	Data []FunctionsListFunctionProfilePairItem `json:"data"`
}

func (FunctionsListFunctionProfilePairResponse) SchemaTitle() string { return "functions.ListFunctionProfilePairResponse" }
func (v FunctionsListFunctionProfilePairResponse) Validate() error {
	return variantValidator.Struct(v)
}
