// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

// Schema for validating Function input.
//
// Defines the expected structure and constraints for input data.
// Used by remote Functions to document and validate their inputs.
type FunctionsExpressionInputSchema struct {
	// A union of schemas - input must match at least one.
	AnyOf *FunctionsExpressionAnyOfInputSchema `ref:"functions.expression.AnyOfInputSchema"`
	// An object with named properties.
	Object *FunctionsExpressionObjectInputSchema `ref:"functions.expression.ObjectInputSchema"`
	// An array of items.
	Array *FunctionsExpressionArrayInputSchema `ref:"functions.expression.ArrayInputSchema"`
	// A string value.
	String *FunctionsExpressionStringInputSchema `ref:"functions.expression.StringInputSchema"`
	// An integer value.
	Integer *FunctionsExpressionIntegerInputSchema `ref:"functions.expression.IntegerInputSchema"`
	// A floating-point number.
	Number *FunctionsExpressionNumberInputSchema `ref:"functions.expression.NumberInputSchema"`
	// A boolean value.
	Boolean *FunctionsExpressionBooleanInputSchema `ref:"functions.expression.BooleanInputSchema"`
	// An image (URL or base64).
	Image *FunctionsExpressionImageInputSchema `ref:"functions.expression.ImageInputSchema"`
	// Audio content.
	Audio *FunctionsExpressionAudioInputSchema `ref:"functions.expression.AudioInputSchema"`
	// Video content.
	Video *FunctionsExpressionVideoInputSchema `ref:"functions.expression.VideoInputSchema"`
	// A file.
	File *FunctionsExpressionFileInputSchema `ref:"functions.expression.FileInputSchema"`
}

func (v FunctionsExpressionInputSchema) MarshalJSON() ([]byte, error) {
	if v.AnyOf != nil {
		return json.Marshal(v.AnyOf)
	}
	if v.Object != nil {
		return json.Marshal(v.Object)
	}
	if v.Array != nil {
		return json.Marshal(v.Array)
	}
	if v.String != nil {
		return json.Marshal(v.String)
	}
	if v.Integer != nil {
		return json.Marshal(v.Integer)
	}
	if v.Number != nil {
		return json.Marshal(v.Number)
	}
	if v.Boolean != nil {
		return json.Marshal(v.Boolean)
	}
	if v.Image != nil {
		return json.Marshal(v.Image)
	}
	if v.Audio != nil {
		return json.Marshal(v.Audio)
	}
	if v.Video != nil {
		return json.Marshal(v.Video)
	}
	if v.File != nil {
		return json.Marshal(v.File)
	}
	return []byte("null"), nil
}

func (v *FunctionsExpressionInputSchema) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return nil
	}
	{
		var try FunctionsExpressionAnyOfInputSchema
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := FunctionsExpressionInputSchema{}
			candidate.AnyOf = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try FunctionsExpressionObjectInputSchema
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := FunctionsExpressionInputSchema{}
			candidate.Object = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try FunctionsExpressionArrayInputSchema
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := FunctionsExpressionInputSchema{}
			candidate.Array = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try FunctionsExpressionStringInputSchema
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := FunctionsExpressionInputSchema{}
			candidate.String = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try FunctionsExpressionIntegerInputSchema
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := FunctionsExpressionInputSchema{}
			candidate.Integer = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try FunctionsExpressionNumberInputSchema
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := FunctionsExpressionInputSchema{}
			candidate.Number = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try FunctionsExpressionBooleanInputSchema
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := FunctionsExpressionInputSchema{}
			candidate.Boolean = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try FunctionsExpressionImageInputSchema
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := FunctionsExpressionInputSchema{}
			candidate.Image = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try FunctionsExpressionAudioInputSchema
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := FunctionsExpressionInputSchema{}
			candidate.Audio = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try FunctionsExpressionVideoInputSchema
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := FunctionsExpressionInputSchema{}
			candidate.Video = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try FunctionsExpressionFileInputSchema
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := FunctionsExpressionInputSchema{}
			candidate.File = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	return fmt.Errorf("data did not match any variant of FunctionsExpressionInputSchema")
}

func (v FunctionsExpressionInputSchema) Validate() error {
	count := 0
	if v.AnyOf != nil { count++ }
	if v.Object != nil { count++ }
	if v.Array != nil { count++ }
	if v.String != nil { count++ }
	if v.Integer != nil { count++ }
	if v.Number != nil { count++ }
	if v.Boolean != nil { count++ }
	if v.Image != nil { count++ }
	if v.Audio != nil { count++ }
	if v.Video != nil { count++ }
	if v.File != nil { count++ }
	if count != 1 {
		return fmt.Errorf("FunctionsExpressionInputSchema: exactly one variant must be set, got %d", count)
	}
	return variantValidator.Struct(v)
}
func (FunctionsExpressionInputSchema) SchemaTitle() string { return "functions.expression.InputSchema" }

