// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type FunctionsAlphaScalarPartialPlaceholderBranchTaskExpression struct {
	FunctionsAlphaScalarPartialPlaceholderScalarFunctionTaskExpression
	Type string `json:"type" validate:"oneof=placeholder.alpha.scalar.function"`
}

func (v FunctionsAlphaScalarPartialPlaceholderBranchTaskExpression) Validate() error {
	return variantValidator.Struct(v)
}
