// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

// A function-profile pair in a list response.
type FunctionsListFunctionProfilePairItem struct {
	// The function.
	Function FunctionsListFunctionItem `json:"function"`
	// The profile.
	Profile FunctionsProfilesListProfileItem `json:"profile"`
}

func (FunctionsListFunctionProfilePairItem) SchemaTitle() string { return "functions.ListFunctionProfilePairItem" }
func (FunctionsListFunctionProfilePairItem) SchemaDescription() string { return "A function-profile pair in a list response." }
func (FunctionsListFunctionProfilePairItem) FieldDescriptions() map[string]string {
	return map[string]string{
		"function": "The function.",
		"profile": "The profile.",
	}
}
func (v FunctionsListFunctionProfilePairItem) Validate() error {
	return variantValidator.Struct(v)
}
