// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

type FunctionsFullInlineFunction struct {
	Variant1 *FunctionsAlphaInlineFunction 
	Variant2 *FunctionsInlineFunction 
}

func (v FunctionsFullInlineFunction) MarshalJSON() ([]byte, error) {
	if v.Variant1 != nil {
		return json.Marshal(v.Variant1)
	}
	if v.Variant2 != nil {
		return json.Marshal(v.Variant2)
	}
	return []byte("null"), nil
}

func (v *FunctionsFullInlineFunction) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return nil
	}
	{
		var try FunctionsAlphaInlineFunction
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := FunctionsFullInlineFunction{}
			candidate.Variant1 = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try FunctionsInlineFunction
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := FunctionsFullInlineFunction{}
			candidate.Variant2 = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	return fmt.Errorf("data did not match any variant of FunctionsFullInlineFunction")
}

func (v FunctionsFullInlineFunction) Validate() error {
	count := 0
	if v.Variant1 != nil { count++ }
	if v.Variant2 != nil { count++ }
	if count != 1 {
		return fmt.Errorf("FunctionsFullInlineFunction: exactly one variant must be set, got %d", count)
	}
	return variantValidator.Struct(v)
}

type FunctionsFullInlineFunctionSchema struct{}

func (FunctionsFullInlineFunctionSchema) SchemaTitle() string { return "functions.FullInlineFunction" }
func (FunctionsFullInlineFunctionSchema) SchemaDescription() string { return "" }
func (FunctionsFullInlineFunctionSchema) Body() map[string]any {
	return map[string]any{
		"anyOf": []any{
			map[string]any{
			"$ref": "functions.AlphaInlineFunction",
		},
			map[string]any{
			"$ref": "functions.InlineFunction",
		},
		},
	}
}
