// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type FunctionsAlphaScalarScalarFunctionTaskExpression struct {
	RemotePath
	Input FunctionsExpressionExpression `json:"input"`
	Skip *FunctionsExpressionExpression `json:"skip,omitempty"`
}

func (FunctionsAlphaScalarScalarFunctionTaskExpression) SchemaTitle() string { return "functions.alpha_scalar.ScalarFunctionTaskExpression" }
func (v FunctionsAlphaScalarScalarFunctionTaskExpression) Validate() error {
	return variantValidator.Struct(v)
}
