// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type FunctionsInventionsStateAlphaVectorState struct {
	Depth uint64 `json:"depth" validate:"min=0,max=18446744073709551615"`
	InputSchema *FunctionsAlphaVectorExpressionVectorFunctionInputSchema `json:"input_schema,omitempty"`
	MaxBranchWidth uint64 `json:"max_branch_width" validate:"min=0,max=18446744073709551615"`
	MaxLeafWidth uint64 `json:"max_leaf_width" validate:"min=0,max=18446744073709551615"`
	MinBranchWidth uint64 `json:"min_branch_width" validate:"min=0,max=18446744073709551615"`
	MinLeafWidth uint64 `json:"min_leaf_width" validate:"min=0,max=18446744073709551615"`
	Name string `json:"name"`
	Spec string `json:"spec"`
}

func (v FunctionsInventionsStateAlphaVectorState) Validate() error {
	return variantValidator.Struct(v)
}
