// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

// Calls a scalar function (produces a single score).
type FunctionsTaskScalarFunction struct {
	FunctionsScalarFunctionTask
	Type string `json:"type" validate:"oneof=scalar.function"`
}
func (FunctionsTaskScalarFunction) SchemaVariantTitle() string { return "ScalarFunction" }

// Calls a vector function (produces a vector of scores).
type FunctionsTaskVectorFunction struct {
	FunctionsVectorFunctionTask
	Type string `json:"type" validate:"oneof=vector.function"`
}
func (FunctionsTaskVectorFunction) SchemaVariantTitle() string { return "VectorFunction" }

// Runs a vector completion.
type FunctionsTaskVectorCompletion struct {
	FunctionsVectorCompletionTask
	Type string `json:"type" validate:"oneof=vector.completion"`
}
func (FunctionsTaskVectorCompletion) SchemaVariantTitle() string { return "VectorCompletion" }

// Placeholder scalar function (always outputs 0.5).
type FunctionsTaskPlaceholderScalarFunction struct {
	FunctionsPlaceholderScalarFunctionTask
	Type string `json:"type" validate:"oneof=placeholder.scalar.function"`
}
func (FunctionsTaskPlaceholderScalarFunction) SchemaVariantTitle() string { return "PlaceholderScalarFunction" }

// Placeholder vector function (always outputs equalized vector).
type FunctionsTaskPlaceholderVectorFunction struct {
	FunctionsPlaceholderVectorFunctionTask
	Type string `json:"type" validate:"oneof=placeholder.vector.function"`
}
func (FunctionsTaskPlaceholderVectorFunction) SchemaVariantTitle() string { return "PlaceholderVectorFunction" }

// A compiled task ready for execution.
//
// Produced by compiling a [`TaskExpression`] against input data. All
// expressions have been resolved to concrete values.
type FunctionsTask struct {
	// Calls a scalar function (produces a single score).
	ScalarFunction *FunctionsTaskScalarFunction 
	// Calls a vector function (produces a vector of scores).
	VectorFunction *FunctionsTaskVectorFunction 
	// Runs a vector completion.
	VectorCompletion *FunctionsTaskVectorCompletion 
	// Placeholder scalar function (always outputs 0.5).
	PlaceholderScalarFunction *FunctionsTaskPlaceholderScalarFunction 
	// Placeholder vector function (always outputs equalized vector).
	PlaceholderVectorFunction *FunctionsTaskPlaceholderVectorFunction 
}

func (v FunctionsTask) MarshalJSON() ([]byte, error) {
	if v.ScalarFunction != nil {
		return json.Marshal(v.ScalarFunction)
	}
	if v.VectorFunction != nil {
		return json.Marshal(v.VectorFunction)
	}
	if v.VectorCompletion != nil {
		return json.Marshal(v.VectorCompletion)
	}
	if v.PlaceholderScalarFunction != nil {
		return json.Marshal(v.PlaceholderScalarFunction)
	}
	if v.PlaceholderVectorFunction != nil {
		return json.Marshal(v.PlaceholderVectorFunction)
	}
	return []byte("null"), nil
}

func (v *FunctionsTask) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return nil
	}
	{
		var try FunctionsTaskScalarFunction
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := FunctionsTask{}
			candidate.ScalarFunction = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try FunctionsTaskVectorFunction
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := FunctionsTask{}
			candidate.VectorFunction = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try FunctionsTaskVectorCompletion
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := FunctionsTask{}
			candidate.VectorCompletion = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try FunctionsTaskPlaceholderScalarFunction
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := FunctionsTask{}
			candidate.PlaceholderScalarFunction = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try FunctionsTaskPlaceholderVectorFunction
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := FunctionsTask{}
			candidate.PlaceholderVectorFunction = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	return fmt.Errorf("data did not match any variant of FunctionsTask")
}

func (v FunctionsTask) Validate() error {
	count := 0
	if v.ScalarFunction != nil { count++ }
	if v.VectorFunction != nil { count++ }
	if v.VectorCompletion != nil { count++ }
	if v.PlaceholderScalarFunction != nil { count++ }
	if v.PlaceholderVectorFunction != nil { count++ }
	if count != 1 {
		return fmt.Errorf("FunctionsTask: exactly one variant must be set, got %d", count)
	}
	return variantValidator.Struct(v)
}
func (FunctionsTask) SchemaTitle() string { return "functions.Task" }

