// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

type FunctionsInventionsStateParamsStateAlphaScalarBranch struct {
	FunctionsInventionsStateAlphaScalarBranchState
	Type string `json:"type" validate:"oneof=alpha.scalar.branch.function"`
}
func (FunctionsInventionsStateParamsStateAlphaScalarBranch) SchemaVariantTitle() string { return "AlphaScalarBranch" }

type FunctionsInventionsStateParamsStateAlphaScalarLeaf struct {
	FunctionsInventionsStateAlphaScalarLeafState
	Type string `json:"type" validate:"oneof=alpha.scalar.leaf.function"`
}
func (FunctionsInventionsStateParamsStateAlphaScalarLeaf) SchemaVariantTitle() string { return "AlphaScalarLeaf" }

type FunctionsInventionsStateParamsStateAlphaVectorBranch struct {
	FunctionsInventionsStateAlphaVectorBranchState
	Type string `json:"type" validate:"oneof=alpha.vector.branch.function"`
}
func (FunctionsInventionsStateParamsStateAlphaVectorBranch) SchemaVariantTitle() string { return "AlphaVectorBranch" }

type FunctionsInventionsStateParamsStateAlphaVectorLeaf struct {
	FunctionsInventionsStateAlphaVectorLeafState
	Type string `json:"type" validate:"oneof=alpha.vector.leaf.function"`
}
func (FunctionsInventionsStateParamsStateAlphaVectorLeaf) SchemaVariantTitle() string { return "AlphaVectorLeaf" }

type FunctionsInventionsStateParamsStateAlphaScalar struct {
	FunctionsInventionsStateAlphaScalarState
	Type string `json:"type" validate:"oneof=alpha.scalar.function"`
}
func (FunctionsInventionsStateParamsStateAlphaScalar) SchemaVariantTitle() string { return "AlphaScalar" }

type FunctionsInventionsStateParamsStateAlphaVector struct {
	FunctionsInventionsStateAlphaVectorState
	Type string `json:"type" validate:"oneof=alpha.vector.function"`
}
func (FunctionsInventionsStateParamsStateAlphaVector) SchemaVariantTitle() string { return "AlphaVector" }

type FunctionsInventionsStateParamsState struct {
	AlphaScalarBranch *FunctionsInventionsStateParamsStateAlphaScalarBranch 
	AlphaScalarLeaf *FunctionsInventionsStateParamsStateAlphaScalarLeaf 
	AlphaVectorBranch *FunctionsInventionsStateParamsStateAlphaVectorBranch 
	AlphaVectorLeaf *FunctionsInventionsStateParamsStateAlphaVectorLeaf 
	AlphaScalar *FunctionsInventionsStateParamsStateAlphaScalar 
	AlphaVector *FunctionsInventionsStateParamsStateAlphaVector 
}

func (v FunctionsInventionsStateParamsState) MarshalJSON() ([]byte, error) {
	if v.AlphaScalarBranch != nil {
		return json.Marshal(v.AlphaScalarBranch)
	}
	if v.AlphaScalarLeaf != nil {
		return json.Marshal(v.AlphaScalarLeaf)
	}
	if v.AlphaVectorBranch != nil {
		return json.Marshal(v.AlphaVectorBranch)
	}
	if v.AlphaVectorLeaf != nil {
		return json.Marshal(v.AlphaVectorLeaf)
	}
	if v.AlphaScalar != nil {
		return json.Marshal(v.AlphaScalar)
	}
	if v.AlphaVector != nil {
		return json.Marshal(v.AlphaVector)
	}
	return []byte("null"), nil
}

func (v *FunctionsInventionsStateParamsState) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return nil
	}
	{
		var try FunctionsInventionsStateParamsStateAlphaScalarBranch
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := FunctionsInventionsStateParamsState{}
			candidate.AlphaScalarBranch = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try FunctionsInventionsStateParamsStateAlphaScalarLeaf
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := FunctionsInventionsStateParamsState{}
			candidate.AlphaScalarLeaf = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try FunctionsInventionsStateParamsStateAlphaVectorBranch
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := FunctionsInventionsStateParamsState{}
			candidate.AlphaVectorBranch = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try FunctionsInventionsStateParamsStateAlphaVectorLeaf
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := FunctionsInventionsStateParamsState{}
			candidate.AlphaVectorLeaf = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try FunctionsInventionsStateParamsStateAlphaScalar
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := FunctionsInventionsStateParamsState{}
			candidate.AlphaScalar = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try FunctionsInventionsStateParamsStateAlphaVector
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := FunctionsInventionsStateParamsState{}
			candidate.AlphaVector = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	return fmt.Errorf("data did not match any variant of FunctionsInventionsStateParamsState")
}

func (v FunctionsInventionsStateParamsState) Validate() error {
	count := 0
	if v.AlphaScalarBranch != nil { count++ }
	if v.AlphaScalarLeaf != nil { count++ }
	if v.AlphaVectorBranch != nil { count++ }
	if v.AlphaVectorLeaf != nil { count++ }
	if v.AlphaScalar != nil { count++ }
	if v.AlphaVector != nil { count++ }
	if count != 1 {
		return fmt.Errorf("FunctionsInventionsStateParamsState: exactly one variant must be set, got %d", count)
	}
	return variantValidator.Struct(v)
}
func (FunctionsInventionsStateParamsState) SchemaTitle() string { return "functions.inventions.state.ParamsState" }

