// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

// A compiled scalar function task ready for execution.
type FunctionsScalarFunctionTask struct {
	RemotePath
	// The resolved input to pass to the function.
	Input FunctionsExpressionInputValue `json:"input"`
	// Expression to transform the task result into a valid function output.
	//
	// Receives `output` as the nested function's result (Scalar or Vector).
	// Must return a `TaskOutputOwned` valid for the parent function's type (scalar or vector).
	// See [`ScalarFunctionTaskExpression::output`] for full documentation.
	Output FunctionsExpressionExpression `json:"output"`
}

func (FunctionsScalarFunctionTask) SchemaTitle() string { return "functions.ScalarFunctionTask" }
func (v FunctionsScalarFunctionTask) Validate() error {
	return variantValidator.Struct(v)
}
