// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

type FunctionsInventionsResponseUnaryObject struct {
	Functions.inventions.response.unary.Object string `validate:"oneof=alpha.scalar.function.invention alpha.vector.function.invention"`
}

func (v FunctionsInventionsResponseUnaryObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.Functions.inventions.response.unary.Object)
}

func (v *FunctionsInventionsResponseUnaryObject) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.Functions.inventions.response.unary.Object); err != nil {
		return err
	}
	return v.Validate()
}

func (v FunctionsInventionsResponseUnaryObject) Validate() error {
	return variantValidator.Struct(v)
}

