// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

type FunctionsExpressionAudioInputSchemaType struct {
	Functions.expression.AudioInputSchemaType string `validate:"oneof=audio"`
}

func (v FunctionsExpressionAudioInputSchemaType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.Functions.expression.AudioInputSchemaType)
}

func (v *FunctionsExpressionAudioInputSchemaType) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.Functions.expression.AudioInputSchemaType); err != nil {
		return err
	}
	return v.Validate()
}

func (v FunctionsExpressionAudioInputSchemaType) Validate() error {
	return variantValidator.Struct(v)
}

