// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type FunctionsExecutionsResponseStreamingFunctionExecutionTaskChunk struct {
	Created uint64 `json:"created" validate:"min=0,max=18446744073709551615"`
	Error *ErrorResponseError `json:"error,omitempty"`
	Function *RemotePath `json:"function,omitempty"`
	ID string `json:"id"`
	Index uint64 `json:"index" validate:"min=0,max=18446744073709551615"`
	Object FunctionsExecutionsResponseStreamingObject `json:"object"`
	Output *FunctionsExecutionsResponseOutput `json:"output,omitempty"`
	Profile *RemotePath `json:"profile,omitempty"`
	Reasoning *FunctionsExecutionsResponseStreamingReasoningSummaryChunk `json:"reasoning,omitempty"`
	RetryToken *string `json:"retry_token,omitempty"`
	SwissPoolIndex *uint64 `json:"swiss_pool_index,omitempty" validate:"min=0,max=18446744073709551615"`
	SwissRound *uint64 `json:"swiss_round,omitempty" validate:"min=0,max=18446744073709551615"`
	TaskIndex uint64 `json:"task_index" validate:"min=0,max=18446744073709551615"`
	TaskPath []uint64 `json:"task_path"`
	Tasks []FunctionsExecutionsResponseStreamingTaskChunk `json:"tasks"`
	TasksErrors *bool `json:"tasks_errors,omitempty"`
	Usage *AgentCompletionsResponseUsage `json:"usage,omitempty"`
}

func (FunctionsExecutionsResponseStreamingFunctionExecutionTaskChunk) SchemaTitle() string { return "functions.executions.response.streaming.FunctionExecutionTaskChunk" }
func (v FunctionsExecutionsResponseStreamingFunctionExecutionTaskChunk) Validate() error {
	return variantValidator.Struct(v)
}
