// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

type FunctionsInventionsResponseStreamingObject struct {
	Functions.inventions.response.streaming.Object string `validate:"oneof=alpha.scalar.function.invention.chunk alpha.vector.function.invention.chunk"`
}

func (v FunctionsInventionsResponseStreamingObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.Functions.inventions.response.streaming.Object)
}

func (v *FunctionsInventionsResponseStreamingObject) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.Functions.inventions.response.streaming.Object); err != nil {
		return err
	}
	return v.Validate()
}

func (v FunctionsInventionsResponseStreamingObject) Validate() error {
	return variantValidator.Struct(v)
}

