// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

// A function-profile pair in a list response.
type FunctionsListFunctionProfilePairItem struct {
	// The function.
	Function RemotePath `json:"function"`
	// The profile.
	Profile RemotePath `json:"profile"`
}

func (v FunctionsListFunctionProfilePairItem) Validate() error {
	return variantValidator.Struct(v)
}
