// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

// Source filter for listing function-profile pairs.
type FunctionsListFunctionProfilePairsSource struct {
	// Source filter for listing function-profile pairs.
	Variant1 string `validate:"oneof=objectiveai"`
}

func (v FunctionsListFunctionProfilePairsSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.Variant1)
}

func (v *FunctionsListFunctionProfilePairsSource) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.Variant1); err != nil {
		return err
	}
	return v.Validate()
}

func (v FunctionsListFunctionProfilePairsSource) Validate() error {
	return variantValidator.Struct(v)
}

type FunctionsListFunctionProfilePairsSourceSchema struct{}

func (FunctionsListFunctionProfilePairsSourceSchema) SchemaTitle() string { return "functions.ListFunctionProfilePairsSource" }
func (FunctionsListFunctionProfilePairsSourceSchema) SchemaDescription() string { return "Source filter for listing function-profile pairs." }
func (FunctionsListFunctionProfilePairsSourceSchema) Body() map[string]any {
	return map[string]any{
		"type": "string",
		"enum": []any{"objectiveai"},
	}
}
