// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

type FunctionsAlphaVectorVectorFunctionTaskExpression struct {
	RemotePath
	Input FunctionsAlphaVectorExpressionVectorFunctionInputValueExpression `json:"input"`
	Skip *FunctionsExpressionExpression `json:"skip,omitempty"`
}

func (FunctionsAlphaVectorVectorFunctionTaskExpression) SchemaTitle() string { return "functions.alpha_vector.VectorFunctionTaskExpression" }
func (v FunctionsAlphaVectorVectorFunctionTaskExpression) Validate() error {
	return variantValidator.Struct(v)
}
