// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
	"fmt"
)

// Scalar or Vector
type FunctionsExecutionsRequestStrategyVariant1 struct {
	Type string `json:"type"`
}

// Vector
type FunctionsExecutionsRequestStrategyVariant2 struct {
	// How many vector responses for each execution
	Pool *uint32 `json:"pool,omitempty"`
	// How many sequential rounds of comparison
	Rounds *uint32 `json:"rounds,omitempty"`
	Type string `json:"type"`
}

type FunctionsExecutionsRequestStrategy struct {
	// Scalar or Vector
	Variant1 *FunctionsExecutionsRequestStrategyVariant1 
	// Vector
	Variant2 *FunctionsExecutionsRequestStrategyVariant2 
}

func (v FunctionsExecutionsRequestStrategy) MarshalJSON() ([]byte, error) {
	if v.Variant1 != nil {
		return json.Marshal(v.Variant1)
	}
	if v.Variant2 != nil {
		return json.Marshal(v.Variant2)
	}
	return []byte("null"), nil
}

func (v *FunctionsExecutionsRequestStrategy) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		return nil
	}
	{
		var try FunctionsExecutionsRequestStrategyVariant1
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := FunctionsExecutionsRequestStrategy{}
			candidate.Variant1 = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	{
		var try FunctionsExecutionsRequestStrategyVariant2
		if err := json.Unmarshal(data, &try); err == nil {
			candidate := FunctionsExecutionsRequestStrategy{}
			candidate.Variant2 = &try
			if candidate.Validate() == nil {
				*v = candidate
				return nil
			}
		}
	}
	return fmt.Errorf("data did not match any variant of FunctionsExecutionsRequestStrategy")
}

func (v FunctionsExecutionsRequestStrategy) Validate() error {
	count := 0
	if v.Variant1 != nil { count++ }
	if v.Variant2 != nil { count++ }
	if count != 1 {
		return fmt.Errorf("FunctionsExecutionsRequestStrategy: exactly one variant must be set, got %d", count)
	}
	return variantValidator.Struct(v)
}

type FunctionsExecutionsRequestStrategySchema struct{}

func (FunctionsExecutionsRequestStrategySchema) SchemaTitle() string { return "functions.executions.request.Strategy" }
func (FunctionsExecutionsRequestStrategySchema) SchemaDescription() string { return "" }
func (FunctionsExecutionsRequestStrategySchema) Body() map[string]any {
	return map[string]any{
		"anyOf": []any{
			map[string]any{
			"description": "Scalar or Vector",
			"type": "object",
			"properties": map[string]any{"type": map[string]any{"enum": []any{"default"}, "type": "string"}},
		},
			map[string]any{
			"description": "Vector",
			"type": "object",
			"properties": map[string]any{"pool": map[string]any{"anyOf": []any{map[string]any{"maximum": json.Number("4294967295"), "minimum": json.Number("0"), "type": "integer"}, map[string]any{"type": "null"}}, "description": "How many vector responses for each execution"}, "rounds": map[string]any{"anyOf": []any{map[string]any{"maximum": json.Number("4294967295"), "minimum": json.Number("0"), "type": "integer"}, map[string]any{"type": "null"}}, "description": "How many sequential rounds of comparison"}, "type": map[string]any{"enum": []any{"swiss_system"}, "type": "string"}},
		},
		},
	}
}
