// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

// Source filter for listing functions.
type FunctionsListFunctionsSource struct {
	// Source filter for listing functions.
	Functions.ListFunctionsSource string `validate:"oneof=all mock filesystem objectiveai"`
}

func (v FunctionsListFunctionsSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.Functions.ListFunctionsSource)
}

func (v *FunctionsListFunctionsSource) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.Functions.ListFunctionsSource); err != nil {
		return err
	}
	return v.Validate()
}

func (v FunctionsListFunctionsSource) Validate() error {
	return variantValidator.Struct(v)
}

