// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

// A UUID with a 3-character prefix for type-safe identifiers.
//
// This struct wraps a standard UUID and adds a compile-time prefix,
// ensuring that different types of identifiers (API keys, swarm IDs, etc.)
// cannot be confused at the type level.
//
// The prefix is specified as three `const char` generic parameters.
//
// # Type Parameters
//
// * `PFX_1` - First character of the prefix
// * `PFX_2` - Second character of the prefix
// * `PFX_3` - Third character of the prefix
//
// # Examples
//
// ```
// use objectiveai::prefixed_uuid::PrefixedUuid;
//
// // Define an API key type with prefix "apk"
// type ApiKey = PrefixedUuid<'a', 'p', 'k'>;
//
// // Create a new API key
// let key = ApiKey::new();
// println!("{}", key); // Outputs: apk<uuid>
// ```
type PrefixedUuid struct {
	UUID string `json:"uuid"`
}

func (v PrefixedUuid) Validate() error {
	return variantValidator.Struct(v)
}
