// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

// The base configuration for an Ensemble (without computed ID).
//
// Contains a list of agent configurations that will be validated, deduplicated,
// and sorted when converting to [`Ensemble`].
type SwarmSwarmBase struct {
	// The LLMs in this ensemble, with optional counts and fallbacks.
	Agents []AgentAgentBase `json:"agents"`
}

func (SwarmSwarmBase) SchemaTitle() string { return "swarm.SwarmBase" }
func (SwarmSwarmBase) SchemaDescription() string { return "The base configuration for an Ensemble (without computed ID).\n\nContains a list of agent configurations that will be validated, deduplicated,\nand sorted when converting to [`Ensemble`]." }
func (SwarmSwarmBase) FieldDescriptions() map[string]string {
	return map[string]string{
		"agents": "The LLMs in this ensemble, with optional counts and fallbacks.",
	}
}
func (v SwarmSwarmBase) Validate() error {
	return variantValidator.Struct(v)
}
