// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

// A validated remote Swarm with metadata and computed content-addressed ID.
type SwarmRemoteSwarm struct {
	SwarmInlineSwarm
	Description string `json:"description"`
}

func (v SwarmRemoteSwarm) Validate() error {
	return variantValidator.Struct(v)
}
