// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

// Request body for retrieving completion votes by vector completion ID.
type VectorCompletionsCacheGetCompletionVotesRequest struct {
	// The vector completion ID.
	ID string `json:"id"`
}

func (VectorCompletionsCacheGetCompletionVotesRequest) SchemaTitle() string { return "vector.completions.cache.GetCompletionVotesRequest" }
func (v VectorCompletionsCacheGetCompletionVotesRequest) Validate() error {
	return variantValidator.Struct(v)
}
