// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

// A chunk in a streaming vector completion response.
//
// Each chunk contains incremental updates to the completion. Use the
// [`push`](Self::push) method to accumulate chunks into a complete response.
type VectorCompletionsResponseStreamingVectorCompletionChunk struct {
	// Incremental agent completion chunks from each agent.
	Completions []VectorCompletionsResponseStreamingAgentCompletionChunk `json:"completions"`
	// Unix timestamp when the completion was created.
	Created uint64 `json:"created" validate:"min=0,max=18446744073709551615"`
	// Unique identifier for this vector completion.
	ID string `json:"id"`
	// Object type identifier (`"vector.completion.chunk"`).
	Object VectorCompletionsResponseStreamingObject `json:"object"`
	// Current weighted scores. Updated as new votes arrive.
	Scores []float64 `json:"scores" validate:"dive,min=-3.4028234663852886e+38,max=3.4028234663852886e+38"`
	// ID of the swarm used for this completion.
	Swarm string `json:"swarm"`
	// Aggregated usage statistics. Typically present only in the final chunk.
	Usage *AgentCompletionsResponseUsage `json:"usage,omitempty"`
	// Votes received so far. New votes are appended in subsequent chunks.
	Votes []VectorCompletionsResponseVote `json:"votes"`
	// Current weight distribution across responses. Updated as new votes arrive.
	Weights []float64 `json:"weights" validate:"dive,min=-3.4028234663852886e+38,max=3.4028234663852886e+38"`
}

func (VectorCompletionsResponseStreamingVectorCompletionChunk) SchemaTitle() string { return "vector.completions.response.streaming.VectorCompletionChunk" }
func (v VectorCompletionsResponseStreamingVectorCompletionChunk) Validate() error {
	return variantValidator.Struct(v)
}
