// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

import (
	"encoding/json"
)

// A streaming vector completion chunk.
type VectorCompletionsResponseStreamingObject struct {
	// A streaming vector completion chunk.
	Variant1 string `validate:"oneof=vector.completion.chunk"`
}

func (v VectorCompletionsResponseStreamingObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.Variant1)
}

func (v *VectorCompletionsResponseStreamingObject) UnmarshalJSON(data []byte) error {
	if err := json.Unmarshal(data, &v.Variant1); err != nil {
		return err
	}
	return v.Validate()
}

func (v VectorCompletionsResponseStreamingObject) Validate() error {
	return variantValidator.Struct(v)
}

type VectorCompletionsResponseStreamingObjectSchema struct{}

func (VectorCompletionsResponseStreamingObjectSchema) SchemaTitle() string { return "vector.completions.response.streaming.Object" }
func (VectorCompletionsResponseStreamingObjectSchema) SchemaDescription() string { return "A streaming vector completion chunk." }
func (VectorCompletionsResponseStreamingObjectSchema) Body() map[string]any {
	return map[string]any{
		"type": "string",
		"enum": []any{"vector.completion.chunk"},
	}
}
