// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package objectiveai

// An entry in weights with an explicit weight and optional invert flag.
type WeightsEntry struct {
	// If true, invert this agent's vote distribution before combining.
	//
	// When omitted or false, the vote distribution is used as-is.
	Invert *bool `json:"invert,omitempty"`
	// The weight for this agent in the swarm. Must be in [0, 1].
	Weight float64 `json:"weight" validate:"min=-3.4028234663852886e+38,max=3.4028234663852886e+38"`
}

func (v WeightsEntry) Validate() error {
	return variantValidator.Struct(v)
}
