# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from objectiveai.vector.completions.response.unary import VectorCompletion

schema = VectorCompletion.model_json_schema()
