# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_list_profiles_source():
    from objectiveai.functions.profiles import ListProfilesSource
    schema = ListProfilesSource.model_json_schema()
