// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by objectiveai-cli-schema-codegen from objectiveai-json-schema/.

use clap::Subcommand;

#[derive(Subcommand)]
#[command(rename_all = "verbatim")]
pub enum GetCommand {
    #[command(name = "get")]
    Get,
}

#[derive(Subcommand)]
#[command(rename_all = "verbatim")]
pub enum Commands {
    #[command(name = "list")]
    List,
    FunctionInventionChunk {
        #[command(subcommand)]
        command: GetCommand,
    },
    FunctionInventionRecursiveChunk {
        #[command(subcommand)]
        command: GetCommand,
    },
    Object {
        #[command(subcommand)]
        command: GetCommand,
    },
}

impl Commands {
    pub fn handle(self) -> Result<crate::Output, crate::error::Error> {
        match self {
            Commands::List => Ok(crate::Output::Schema("[\"FunctionInventionChunk\",\"FunctionInventionRecursiveChunk\",\"Object\"]")),
            Commands::FunctionInventionChunk { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../../../../objectiveai-json-schema/functions.inventions.recursive.response.streaming.FunctionInventionChunk.json"),
            )),
            Commands::FunctionInventionRecursiveChunk { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../../../../objectiveai-json-schema/functions.inventions.recursive.response.streaming.FunctionInventionRecursiveChunk.json"),
            )),
            Commands::Object { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../../../../objectiveai-json-schema/functions.inventions.recursive.response.streaming.Object.json"),
            )),
        }
    }
}
