// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package request

type AgentCompletionCreateParams struct {
	Agent any `json:"agent" ref:"agent.completions.request.Agent"`
	Agents []any `json:"agents,omitempty" nullable:"true" items_ref:"agent.completions.request.Agent"`
	MCPServerAuthorization map[string]string `json:"mcp_server_authorization,omitempty" nullable:"true"`
	Messages []any `json:"messages" items_ref:"agent.completions.message.Message"`
	Provider any `json:"provider,omitempty" nullable:"true" ref:"agent.completions.request.Provider"`
	ResponseFormat any `json:"response_format,omitempty" nullable:"true" ref:"agent.completions.request.ResponseFormatParam"`
	Seed *int64 `json:"seed,omitempty" nullable:"true" min:"-9223372036854775808" max:"9223372036854775807"`
	Stream *bool `json:"stream,omitempty" nullable:"true"`
}

func (AgentCompletionCreateParams) SchemaTitle() string { return "agent.completions.request.AgentCompletionCreateParams" }
func (AgentCompletionCreateParams) SchemaDescription() string { return "Parameters for creating a agent completion." }
func (AgentCompletionCreateParams) FieldDescriptions() map[string]string {
	return map[string]string{
		"agent": "The agent to use (inline Agent or stored ID).",
		"agents": "Alternative agents to try if the primary agent fails.",
		"mcp_server_authorization": "Map from MCP server URL to authorization header value.",
		"messages": "The conversation messages.",
		"provider": "Provider routing preferences.",
		"response_format": "Output format constraints (text, JSON, or JSON schema).",
		"seed": "Random seed for deterministic generation.",
		"stream": "Whether to stream the response.",
	}
}
