// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package request

type ProviderSort interface {
	isProviderSort()
}

type ProviderSortVariant1 struct{}

func (ProviderSortVariant1) isProviderSort() {}

type ProviderSortVariant2 struct{}

func (ProviderSortVariant2) isProviderSort() {}

type ProviderSortVariant3 struct{}

func (ProviderSortVariant3) isProviderSort() {}

type ProviderSortSchema struct{}

func (ProviderSortSchema) SchemaTitle() string { return "agent.completions.request.ProviderSort" }
func (ProviderSortSchema) SchemaDescription() string { return "How to sort/prioritize providers." }
func (ProviderSortSchema) Body() map[string]any {
	return map[string]any{
		"anyOf": []any{
			map[string]any{
			"description": "Prioritize by price (cheapest first).",
			"type": "string",
			"enum": []any{"price"},
		},
			map[string]any{
			"description": "Prioritize by throughput (fastest first).",
			"type": "string",
			"enum": []any{"throughput"},
		},
			map[string]any{
			"description": "Prioritize by latency (lowest first).",
			"type": "string",
			"enum": []any{"latency"},
		},
		},
	}
}
