// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package request

type ResponseFormat = any

type ResponseFormatSchema struct{}

func (ResponseFormatSchema) JSONSchema() map[string]any {
	return map[string]any{
		"title": "agent.completions.request.ResponseFormat",
		"description": "The format of the model's response.",
		"anyOf": []any{
			map[string]any{
			"description": "Plain text response (default).",
			"type": "object",
			"properties": map[string]any{"type": map[string]any{"enum": []any{"text"}, "type": "string"}},
		},
			map[string]any{
			"description": "Response must be valid JSON.",
			"type": "object",
			"properties": map[string]any{"type": map[string]any{"enum": []any{"json_object"}, "type": "string"}},
		},
			map[string]any{
			"description": "Response must conform to a JSON schema.",
			"type": "object",
			"properties": map[string]any{"schema": map[string]any{"additionalProperties": true, "description": "The JSON Schema definition.", "type": "object"}, "type": map[string]any{"enum": []any{"json_schema"}, "type": "string"}},
		},
			map[string]any{
			"description": "Response must conform to a grammar.",
			"type": "object",
			"properties": map[string]any{"grammar": map[string]any{"type": "string"}, "type": map[string]any{"enum": []any{"grammar"}, "type": "string"}},
		},
			map[string]any{
			"description": "Response must be valid Python code.",
			"type": "object",
			"properties": map[string]any{"type": map[string]any{"enum": []any{"python"}, "type": "string"}},
		},
			map[string]any{
			"description": "The final assistant message will contain this tool call",
			"type": "object",
			"properties": map[string]any{"description": map[string]any{"description": "A description of the tool.", "type": "string"}, "name": map[string]any{"description": "The name of the tool.", "type": "string"}, "required": map[string]any{"anyOf": []any{map[string]any{"type": "boolean"}, map[string]any{"type": "null"}}, "description": "Whether the tool MUST be called."}, "schema": map[string]any{"additionalProperties": true, "description": "The JSON Schema definition.", "type": "object"}, "type": map[string]any{"enum": []any{"tool_call"}, "type": "string"}},
		},
		},
	}
}
