// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package expression

type VectorFunctionInputSchema struct {
	Context any `json:"context,omitempty"`
	Items any `json:"items"`
}

func (VectorFunctionInputSchema) JSONSchema() map[string]any {
	return map[string]any{
		"title": "functions.alpha_vector.expression.VectorFunctionInputSchema",
		"type": "object",
		"properties": map[string]any{
			"context": map[string]any{
			"anyOf": []any{map[string]any{"$ref": "functions.expression.ObjectInputSchema"}, map[string]any{"type": "null"}},
		},
			"items": map[string]any{
			"$ref": "functions.expression.InputSchema",
		},
		},
	}
}
