// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package expression

type VectorFunctionInputValueExpression struct {
	Context any `json:"context,omitempty" nullable:"true" ref:"functions.expression.Expression"`
	Items any `json:"items" ref:"functions.expression.Expression"`
}

func (VectorFunctionInputValueExpression) SchemaTitle() string { return "functions.alpha_vector.expression.VectorFunctionInputValueExpression" }
func (VectorFunctionInputValueExpression) SchemaDescription() string { return "" }
