// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by objectiveai-cli-schema-codegen from objectiveai-json-schema/.

use clap::Subcommand;

#[derive(Subcommand)]
#[command(rename_all = "verbatim")]
pub enum GetCommand {
    #[command(name = "get")]
    Get,
}

#[derive(Subcommand)]
#[command(rename_all = "verbatim")]
pub enum Commands {
    #[command(name = "list")]
    List,
    BranchTaskExpression {
        #[command(subcommand)]
        command: GetCommand,
    },
    InlineFunction {
        #[command(subcommand)]
        command: GetCommand,
    },
    LeafTaskExpression {
        #[command(subcommand)]
        command: GetCommand,
    },
    PartialPlaceholderBranchTaskExpression {
        #[command(subcommand)]
        command: GetCommand,
    },
    PartialPlaceholderScalarFunctionTaskExpression {
        #[command(subcommand)]
        command: GetCommand,
    },
    PlaceholderScalarFunctionTaskExpression {
        #[command(subcommand)]
        command: GetCommand,
    },
    RemoteFunction {
        #[command(subcommand)]
        command: GetCommand,
    },
    ScalarFunctionTaskExpression {
        #[command(subcommand)]
        command: GetCommand,
    },
    VectorCompletionTaskExpression {
        #[command(subcommand)]
        command: GetCommand,
    },
}

impl Commands {
    pub fn handle(self) -> Result<crate::Output, crate::error::Error> {
        match self {
            Commands::List => Ok(crate::Output::Schema("[\"BranchTaskExpression\",\"InlineFunction\",\"LeafTaskExpression\",\"PartialPlaceholderBranchTaskExpression\",\"PartialPlaceholderScalarFunctionTaskExpression\",\"PlaceholderScalarFunctionTaskExpression\",\"RemoteFunction\",\"ScalarFunctionTaskExpression\",\"VectorCompletionTaskExpression\"]")),
            Commands::BranchTaskExpression { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.alpha_scalar.BranchTaskExpression.json"),
            )),
            Commands::InlineFunction { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.alpha_scalar.InlineFunction.json"),
            )),
            Commands::LeafTaskExpression { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.alpha_scalar.LeafTaskExpression.json"),
            )),
            Commands::PartialPlaceholderBranchTaskExpression { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.alpha_scalar.PartialPlaceholderBranchTaskExpression.json"),
            )),
            Commands::PartialPlaceholderScalarFunctionTaskExpression { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.alpha_scalar.PartialPlaceholderScalarFunctionTaskExpression.json"),
            )),
            Commands::PlaceholderScalarFunctionTaskExpression { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.alpha_scalar.PlaceholderScalarFunctionTaskExpression.json"),
            )),
            Commands::RemoteFunction { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.alpha_scalar.RemoteFunction.json"),
            )),
            Commands::ScalarFunctionTaskExpression { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.alpha_scalar.ScalarFunctionTaskExpression.json"),
            )),
            Commands::VectorCompletionTaskExpression { .. } => Ok(crate::Output::Schema(
                include_str!("../../../../../objectiveai-json-schema/functions.alpha_scalar.VectorCompletionTaskExpression.json"),
            )),
        }
    }
}
