# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional, Union
from pydantic import BaseModel
from objectiveai.agent.completions.response.logprob import AgentCompletionsResponseLogprob


class AgentCompletionsResponseLogprobs(BaseModel):
    """Log probabilities for generated tokens."""
    content: Optional[Union[list[AgentCompletionsResponseLogprob], None]] = None
    refusal: Optional[Union[list[AgentCompletionsResponseLogprob], None]] = None

