# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional
from pydantic import BaseModel, Field
from objectiveai.agent.completions.response.completion_tokens_details import AgentCompletionsResponseCompletionTokensDetails
from objectiveai.agent.completions.response.cost_details import AgentCompletionsResponseCostDetails
from objectiveai.agent.completions.response.prompt_tokens_details import AgentCompletionsResponsePromptTokensDetails


class AgentCompletionsResponseUpstreamUsage(BaseModel):
    """Token usage and cost information from an upstream provider.

This is the per-assistant-response usage yielded by upstream clients.
It includes upstream-specific fields like `cost_multiplier` and `is_byok`."""
    completion_tokens: int = Field(..., description='Number of tokens in the completion.', ge=0, json_schema_extra={'format': 'uint64'})
    prompt_tokens: int = Field(..., description='Number of tokens in the prompt.', ge=0, json_schema_extra={'format': 'uint64'})
    total_tokens: int = Field(..., description='Total tokens (prompt + completion).', ge=0, json_schema_extra={'format': 'uint64'})
    completion_tokens_details: Optional[AgentCompletionsResponseCompletionTokensDetails] = Field(None, description='Detailed breakdown of completion tokens.')
    prompt_tokens_details: Optional[AgentCompletionsResponsePromptTokensDetails] = Field(None, description='Detailed breakdown of prompt tokens.')
    cost: float = Field(..., description='The cost charged by ObjectiveAI for this request.', json_schema_extra={'format': 'double'})
    cost_details: Optional[AgentCompletionsResponseCostDetails] = Field(None, description='Detailed cost breakdown.')
    total_cost: float = Field(..., description="Total cost including ObjectiveAI's charge plus all upstream charges.\nFor BYOK requests, ObjectiveAI only charges the cost_multiplier difference,\nbut total_cost still includes what the upstream provider charged.", json_schema_extra={'format': 'double'})
    cost_multiplier: float = Field(..., description="The multiplier applied to compute ObjectiveAI's charge.", json_schema_extra={'format': 'double'})
    is_byok: bool = Field(..., description='Whether this request used Bring Your Own Key (BYOK).')

