# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional
from pydantic import BaseModel
from objectiveai.functions.alpha_vector.expression.vector_function_input_schema import FunctionsAlphaVectorExpressionVectorFunctionInputSchema


class FunctionsInventionsStateAlphaVectorState(BaseModel):
    depth: int
    min_branch_width: int
    max_branch_width: int
    min_leaf_width: int
    max_leaf_width: int
    name: str
    spec: str
    input_schema: Optional[FunctionsAlphaVectorExpressionVectorFunctionInputSchema] = None

