# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional, Union
from pydantic import BaseModel, Field
from objectiveai.functions.alpha_vector.expression.vector_function_input_schema import FunctionsAlphaVectorExpressionVectorFunctionInputSchema
from objectiveai.functions.alpha_vector.leaf_task_expression import FunctionsAlphaVectorLeafTaskExpression


class FunctionsInventionsStateAlphaVectorLeafState(BaseModel):
    depth: int = Field(..., ge=0, json_schema_extra={'format': 'uint64'})
    min_branch_width: int = Field(..., ge=0, json_schema_extra={'format': 'uint64'})
    max_branch_width: int = Field(..., ge=0, json_schema_extra={'format': 'uint64'})
    min_leaf_width: int = Field(..., ge=0, json_schema_extra={'format': 'uint64'})
    max_leaf_width: int = Field(..., ge=0, json_schema_extra={'format': 'uint64'})
    name: str
    spec: str
    essay: Optional[Union[str, None]] = None
    input_schema: Optional[FunctionsAlphaVectorExpressionVectorFunctionInputSchema] = None
    essay_tasks: Optional[Union[str, None]] = None
    tasks: Optional[Union[list[FunctionsAlphaVectorLeafTaskExpression], None]] = None
    tasks_length: Optional[Union[int, None]] = Field(None, ge=0, json_schema_extra={'format': 'uint64'})
    description: Optional[Union[str, None]] = None
    readme: Optional[Union[str, None]] = None

