# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from objectiveai.functions.inventions.recursive.response.unary import FunctionInventionRecursive

schema = FunctionInventionRecursive.model_json_schema()
