// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";

export const ConfigApiLocalConfigSchema = z.object({
  claude_agent_sdk: z.boolean().nullable().optional(),
}).meta({ title: "config.ApiLocalConfig" });
export type ConfigApiLocalConfig = z.infer<typeof ConfigApiLocalConfigSchema>;
