// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { RemotePathCommitOptionalSchema } from "../remotePathCommitOptional";

export const ConfigFavoriteSchema = RemotePathCommitOptionalSchema.and(z.object({
  name: z.string(),
  note: z.string(),
})).meta({ title: "config.Favorite" });
export type ConfigFavorite = z.infer<typeof ConfigFavoriteSchema>;
