// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { FunctionsExpressionExpressionSchema } from "../expression/expression";
import { FunctionsRemoteSchema } from "../remote";

export const FunctionsAlphaScalarScalarFunctionTaskExpressionSchema = z.object({
  commit: z.string(),
  input: FunctionsExpressionExpressionSchema,
  owner: z.string(),
  remote: FunctionsRemoteSchema,
  repository: z.string(),
  skip: FunctionsExpressionExpressionSchema.nullable().optional(),
}).meta({ title: "functions.alpha_scalar.ScalarFunctionTaskExpression" });
export type FunctionsAlphaScalarScalarFunctionTaskExpression = z.infer<typeof FunctionsAlphaScalarScalarFunctionTaskExpressionSchema>;
