# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Literal


FunctionsExecutionsResponseStreamingObject = Literal['scalar.function.execution.chunk', 'vector.function.execution.chunk']

