# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Union
from pydantic import ConfigDict, RootModel
from objectiveai.functions.executions.response.streaming.vector_completion_task_chunk import VectorCompletionTaskChunk


class TaskChunkVariant1(RootModel):
    root: FunctionExecutionTaskChunk


class TaskChunkVariant2(RootModel):
    root: VectorCompletionTaskChunk


class TaskChunk(RootModel):
    model_config = ConfigDict(title='functions.executions.response.streaming.TaskChunk')

    root: Union[TaskChunkVariant1, TaskChunkVariant2]


# Deferred imports to break circular dependencies
from objectiveai.functions.executions.response.streaming.function_execution_task_chunk import FunctionExecutionTaskChunk  # noqa: E402
