# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional, Union
from pydantic import BaseModel
from objectiveai.agent.completions.response.usage import AgentCompletionsResponseUsage
from objectiveai.response_error import ResponseError
from objectiveai.vector.completions.response.streaming.agent_completion_chunk import VectorCompletionsResponseStreamingAgentCompletionChunk
from objectiveai.vector.completions.response.streaming.object import VectorCompletionsResponseStreamingObject
from objectiveai.vector.completions.response.vote import VectorCompletionsResponseVote


class FunctionsExecutionsResponseStreamingVectorCompletionTaskChunk(BaseModel):
    """A chunk in a streaming vector completion response.

Each chunk contains incremental updates to the completion. Use the
[`push`](Self::push) method to accumulate chunks into a complete response."""
    index: int
    task_index: int
    task_path: list[int]
    id: str
    completions: list[VectorCompletionsResponseStreamingAgentCompletionChunk]
    votes: list[VectorCompletionsResponseVote]
    scores: list[Union[str, float]]
    weights: list[Union[str, float]]
    created: int
    ensemble: str
    object: VectorCompletionsResponseStreamingObject
    usage: Optional[AgentCompletionsResponseUsage] = None
    error: Optional[ResponseError] = None

