// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package request

import "encoding/json"

var _ json.Number // suppress unused import

type Strategy = any

type StrategySchema struct{}

func (StrategySchema) JSONSchema() map[string]any {
	return map[string]any{
		"title": "functions.executions.request.Strategy",
		"anyOf": []any{
			map[string]any{
			"description": "Scalar or Vector",
			"type": "object",
			"properties": map[string]any{"type": map[string]any{"enum": []any{"default"}, "type": "string"}},
		},
			map[string]any{
			"description": "Vector",
			"type": "object",
			"properties": map[string]any{"pool": map[string]any{"anyOf": []any{map[string]any{"maximum": json.Number("4294967295"), "minimum": json.Number("0"), "type": "integer"}, map[string]any{"type": "null"}}, "description": "How many vector responses for each execution"}, "rounds": map[string]any{"anyOf": []any{map[string]any{"maximum": json.Number("4294967295"), "minimum": json.Number("0"), "type": "integer"}, map[string]any{"type": "null"}}, "description": "How many sequential rounds of comparison"}, "type": map[string]any{"enum": []any{"swiss_system"}, "type": "string"}},
		},
		},
	}
}
