// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package request

import (
	"encoding/json"
)

var _ json.Number // suppress unused import

type Strategy interface {
	isStrategy()
}

type StrategyVariant1 struct {
	Type string `json:"type"`
}

func (StrategyVariant1) isStrategy() {}

type StrategyVariant2 struct {
	Pool *uint32 `json:"pool,omitempty"`
	Rounds *uint32 `json:"rounds,omitempty"`
	Type string `json:"type"`
}

func (StrategyVariant2) isStrategy() {}

type StrategySchema struct{}

func (StrategySchema) SchemaTitle() string { return "functions.executions.request.Strategy" }
func (StrategySchema) SchemaDescription() string { return "" }
func (StrategySchema) Body() map[string]any {
	return map[string]any{
		"anyOf": []any{
			map[string]any{
			"description": "Scalar or Vector",
			"type": "object",
			"properties": map[string]any{"type": map[string]any{"enum": []any{"default"}, "type": "string"}},
		},
			map[string]any{
			"description": "Vector",
			"type": "object",
			"properties": map[string]any{"pool": map[string]any{"anyOf": []any{map[string]any{"maximum": json.Number("4294967295"), "minimum": json.Number("0"), "type": "integer"}, map[string]any{"type": "null"}}, "description": "How many vector responses for each execution"}, "rounds": map[string]any{"anyOf": []any{map[string]any{"maximum": json.Number("4294967295"), "minimum": json.Number("0"), "type": "integer"}, map[string]any{"type": "null"}}, "description": "How many sequential rounds of comparison"}, "type": map[string]any{"enum": []any{"swiss_system"}, "type": "string"}},
		},
		},
	}
}
