// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package agent

import "encoding/json"

var _ json.Number // suppress unused import

type GetAgent struct {
	Created uint64 `json:"created"`
}

func (GetAgent) JSONSchema() map[string]any {
	return map[string]any{
		"title": "agent.GetAgent",
		"description": "Response containing a single Agent with creation timestamp.",
		"type": "object",
		"anyOf": []any{
			map[string]any{
			"$ref": "agent.openrouter.Agent",
		},
			map[string]any{
			"$ref": "agent.claude_agent_sdk.Agent",
		},
			map[string]any{
			"$ref": "agent.mock.Agent",
		},
		},
		"properties": map[string]any{
			"created": map[string]any{
			"description": "Unix timestamp when this Agent was first used.",
			"type": "integer",
			"minimum": json.Number("0"),
			"maximum": json.Number("18446744073709551615"),
		},
		},
	}
}
