// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package agent

type ListAgentItem struct {
	ID string `json:"id"`
}

func (ListAgentItem) JSONSchema() map[string]any {
	return map[string]any{
		"title": "agent.ListAgentItem",
		"description": "Summary information for a listed Agent.",
		"type": "object",
		"properties": map[string]any{
			"id": map[string]any{
			"description": "The unique content-addressed ID of the Agent.",
			"type": "string",
		},
		},
	}
}
