// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package agent

type McpServer struct {
	Authorization bool `json:"authorization,omitempty" def:"false"`
	URL string `json:"url"`
}

func (McpServer) SchemaTitle() string { return "agent.McpServer" }
func (McpServer) SchemaDescription() string { return "An MCP server that the agent can connect to." }
func (McpServer) FieldDescriptions() map[string]string {
	return map[string]string{
		"authorization": "Whether this MCP server uses authorization.",
		"url": "The URL of the MCP server.",
	}
}
