// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package agent

type WithFallbacksAndCountAgentAgent struct {
	Count uint64 `json:"count,omitempty" min:"0" max:"18446744073709551615" def:"1"`
	Fallbacks []any `json:"fallbacks,omitempty" nullable:"true" items_ref:"agent.Agent"`
}

func (WithFallbacksAndCountAgentAgent) SchemaTitle() string { return "agent.WithFallbacksAndCount.agent.Agent" }
func (WithFallbacksAndCountAgentAgent) SchemaDescription() string { return "Wrapper that adds fallback agents and a count to any agent type.\n\nUsed to specify how many instances of an agent to include in an ensemble,\nalong with fallback agents to try if the primary fails." }
func (WithFallbacksAndCountAgentAgent) FieldDescriptions() map[string]string {
	return map[string]string{
		"count": "Number of instances of this agent in the ensemble. Defaults to 1.",
		"fallbacks": "Fallback agents to try if the primary fails.",
	}
}

func (WithFallbacksAndCountAgentAgent) Body() map[string]any {
	return map[string]any{
		"anyOf": []any{
			map[string]any{
			"$ref": "agent.openrouter.Agent",
		},
			map[string]any{
			"$ref": "agent.claude_agent_sdk.Agent",
		},
			map[string]any{
			"$ref": "agent.mock.Agent",
		},
		},
	}
}

type WithFallbacksAndCountAgentAgentBase struct {
	Count uint64 `json:"count,omitempty" min:"0" max:"18446744073709551615" def:"1"`
	Fallbacks []any `json:"fallbacks,omitempty" nullable:"true" items_ref:"agent.AgentBase"`
}

func (WithFallbacksAndCountAgentAgentBase) SchemaTitle() string { return "agent.WithFallbacksAndCount.agent.AgentBase" }
func (WithFallbacksAndCountAgentAgentBase) SchemaDescription() string { return "Wrapper that adds fallback agents and a count to any agent type.\n\nUsed to specify how many instances of an agent to include in an ensemble,\nalong with fallback agents to try if the primary fails." }
func (WithFallbacksAndCountAgentAgentBase) FieldDescriptions() map[string]string {
	return map[string]string{
		"count": "Number of instances of this agent in the ensemble. Defaults to 1.",
		"fallbacks": "Fallback agents to try if the primary fails.",
	}
}

func (WithFallbacksAndCountAgentAgentBase) Body() map[string]any {
	return map[string]any{
		"anyOf": []any{
			map[string]any{
			"$ref": "agent.openrouter.AgentBase",
		},
			map[string]any{
			"$ref": "agent.claude_agent_sdk.AgentBase",
		},
			map[string]any{
			"$ref": "agent.mock.AgentBase",
		},
		},
	}
}
