// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package alpha_vector

type InlineFunction interface {
	isInlineFunction()
}

type InlineFunctionVariant1 struct {
	Tasks []any `json:"tasks"`
	Type string `json:"type"`
}

func (InlineFunctionVariant1) isInlineFunction() {}

type InlineFunctionVariant2 struct {
	Tasks []any `json:"tasks"`
	Type string `json:"type"`
}

func (InlineFunctionVariant2) isInlineFunction() {}

type InlineFunctionSchema struct{}

func (InlineFunctionSchema) SchemaTitle() string { return "functions.alpha_vector.InlineFunction" }
func (InlineFunctionSchema) SchemaDescription() string { return "" }
func (InlineFunctionSchema) Body() map[string]any {
	return map[string]any{
		"anyOf": []any{
			map[string]any{
			"type": "object",
			"properties": map[string]any{"tasks": map[string]any{"items": map[string]any{"$ref": "functions.alpha_vector.BranchTaskExpression"}, "type": "array"}, "type": map[string]any{"enum": []any{"alpha.vector.branch.function"}, "type": "string"}},
		},
			map[string]any{
			"type": "object",
			"properties": map[string]any{"tasks": map[string]any{"items": map[string]any{"$ref": "functions.alpha_vector.LeafTaskExpression"}, "type": "array"}, "type": map[string]any{"enum": []any{"alpha.vector.leaf.function"}, "type": "string"}},
		},
		},
	}
}
