// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package alpha_vector

type InlineFunction = any

type InlineFunctionSchema struct{}

func (InlineFunctionSchema) JSONSchema() map[string]any {
	return map[string]any{
		"title": "functions.alpha_vector.InlineFunction",
		"anyOf": []any{
			map[string]any{
			"type": "object",
			"properties": map[string]any{"tasks": map[string]any{"items": map[string]any{"$ref": "functions.alpha_vector.BranchTaskExpression"}, "type": "array"}, "type": map[string]any{"enum": []any{"alpha.vector.branch.function"}, "type": "string"}},
		},
			map[string]any{
			"type": "object",
			"properties": map[string]any{"tasks": map[string]any{"items": map[string]any{"$ref": "functions.alpha_vector.LeafTaskExpression"}, "type": "array"}, "type": map[string]any{"enum": []any{"alpha.vector.leaf.function"}, "type": "string"}},
		},
		},
	}
}
