// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package alpha_vector

type PartialPlaceholderVectorFunctionTaskExpression struct {
	Input any `json:"input" ref:"functions.alpha_vector.expression.VectorFunctionInputValueExpression"`
	InputSchema any `json:"input_schema" ref:"functions.alpha_vector.expression.VectorFunctionInputSchema"`
	Skip any `json:"skip,omitempty" nullable:"true" ref:"functions.expression.Expression"`
	Spec string `json:"spec"`
}

func (PartialPlaceholderVectorFunctionTaskExpression) SchemaTitle() string { return "functions.alpha_vector.PartialPlaceholderVectorFunctionTaskExpression" }
func (PartialPlaceholderVectorFunctionTaskExpression) SchemaDescription() string { return "" }
