// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package alpha_vector

type PartialPlaceholderBranchTaskExpression interface {
	isPartialPlaceholderBranchTaskExpression()
}

type PartialPlaceholderBranchTaskExpressionVariant1 struct {
	Type string `json:"type"`
}

func (PartialPlaceholderBranchTaskExpressionVariant1) isPartialPlaceholderBranchTaskExpression() {}

type PartialPlaceholderBranchTaskExpressionVariant2 struct {
	Type string `json:"type"`
}

func (PartialPlaceholderBranchTaskExpressionVariant2) isPartialPlaceholderBranchTaskExpression() {}

type PartialPlaceholderBranchTaskExpressionSchema struct{}

func (PartialPlaceholderBranchTaskExpressionSchema) SchemaTitle() string { return "functions.alpha_vector.PartialPlaceholderBranchTaskExpression" }
func (PartialPlaceholderBranchTaskExpressionSchema) SchemaDescription() string { return "" }
func (PartialPlaceholderBranchTaskExpressionSchema) Body() map[string]any {
	return map[string]any{
		"anyOf": []any{
			map[string]any{
			"type": "object",
			"$ref": "functions.alpha_vector.PartialPlaceholderScalarFunctionTaskExpression",
			"properties": map[string]any{"type": map[string]any{"enum": []any{"placeholder.alpha.scalar.function"}, "type": "string"}},
		},
			map[string]any{
			"type": "object",
			"$ref": "functions.alpha_vector.PartialPlaceholderVectorFunctionTaskExpression",
			"properties": map[string]any{"type": map[string]any{"enum": []any{"placeholder.alpha.vector.function"}, "type": "string"}},
		},
		},
	}
}
