// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package alpha_vector

type PlaceholderVectorFunctionTaskExpression struct {
	Depth uint64 `json:"depth" min:"0" max:"18446744073709551615"`
	Input any `json:"input" ref:"functions.alpha_vector.expression.VectorFunctionInputValueExpression"`
	InputSchema any `json:"input_schema" ref:"functions.alpha_vector.expression.VectorFunctionInputSchema"`
	MaxBranchWidth uint64 `json:"max_branch_width" min:"0" max:"18446744073709551615"`
	MaxLeafWidth uint64 `json:"max_leaf_width" min:"0" max:"18446744073709551615"`
	MinBranchWidth uint64 `json:"min_branch_width" min:"0" max:"18446744073709551615"`
	MinLeafWidth uint64 `json:"min_leaf_width" min:"0" max:"18446744073709551615"`
	Name string `json:"name"`
	Skip any `json:"skip,omitempty" nullable:"true" ref:"functions.expression.Expression"`
	Spec string `json:"spec"`
}

func (PlaceholderVectorFunctionTaskExpression) SchemaTitle() string { return "functions.alpha_vector.PlaceholderVectorFunctionTaskExpression" }
func (PlaceholderVectorFunctionTaskExpression) SchemaDescription() string { return "" }
