# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_input_value_array():
    from objectiveai.functions.expression import InputValueArray
    schema = InputValueArray.model_json_schema()
