# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_function_remote_profile_inline_request_path():
    from objectiveai.functions.executions.request import FunctionRemoteProfileInlineRequestPath
    schema = FunctionRemoteProfileInlineRequestPath.model_json_schema()
