# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from objectiveai.functions.executions.request import FunctionExecutionCreateParamsVariant4

schema = FunctionExecutionCreateParamsVariant4.model_json_schema()
