# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_request_variant3():
    from objectiveai.functions.executions.request import RequestVariant3
    schema = RequestVariant3.model_json_schema()
