// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package streaming

type FunctionInventionChunk struct {
	Completions []any `json:"completions" items_ref:"functions.inventions.response.streaming.AgentCompletionChunk"`
	Created uint64 `json:"created" min:"0" max:"18446744073709551615"`
	Error any `json:"error,omitempty" nullable:"true" ref:"ResponseError"`
	Function any `json:"function,omitempty" nullable:"true" ref:"functions.FullRemoteFunction"`
	ID string `json:"id"`
	Index uint64 `json:"index" min:"0" max:"18446744073709551615"`
	Object any `json:"object" ref:"functions.inventions.response.streaming.Object"`
	Path any `json:"path,omitempty" nullable:"true" ref:"functions.RemoteFunctionPath"`
	State any `json:"state,omitempty" nullable:"true" ref:"functions.inventions.state.State"`
	Usage any `json:"usage,omitempty" nullable:"true" ref:"agent.completions.response.Usage"`
}

func (FunctionInventionChunk) SchemaTitle() string { return "functions.inventions.recursive.response.streaming.FunctionInventionChunk" }
func (FunctionInventionChunk) SchemaDescription() string { return "" }
