// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package computations

type RetryToken = []*string

type RetryTokenSchema struct{}

func (RetryTokenSchema) JSONSchema() map[string]any {
	return map[string]any{
		"title": "functions.profiles.computations.RetryToken",
		"type": "array",
		"items": map[string]any{
			"anyOf": []any{map[string]any{"type": "string"}, map[string]any{"type": "null"}},
		},
	}
}
