# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional, Union
from pydantic import BaseModel, ConfigDict, Field, RootModel
from objectiveai.agent.agent import Agent
from objectiveai.agent.claude_agent_sdk.agent import Agent as AgentClaudeAgentSdkAgent
from objectiveai.agent.mock.agent import Agent as AgentMockAgent
from objectiveai.agent.openrouter.agent import Agent as AgentOpenrouterAgent


class SwarmAgentsItemVariant1(AgentOpenrouterAgent):
    count: int = Field(1, description='Number of instances of this agent in the swarm. Defaults to 1.', ge=0, le=18446744073709551615)
    fallbacks: Optional[list[Agent]] = Field(None, description='Fallback agents to try if the primary fails.')


class SwarmAgentsItemVariant2(AgentClaudeAgentSdkAgent):
    count: int = Field(1, description='Number of instances of this agent in the swarm. Defaults to 1.', ge=0, le=18446744073709551615)
    fallbacks: Optional[list[Agent]] = Field(None, description='Fallback agents to try if the primary fails.')


class SwarmAgentsItemVariant3(AgentMockAgent):
    count: int = Field(1, description='Number of instances of this agent in the swarm. Defaults to 1.', ge=0, le=18446744073709551615)
    fallbacks: Optional[list[Agent]] = Field(None, description='Fallback agents to try if the primary fails.')


class SwarmAgentsItem(RootModel):
    """Wrapper that adds fallback agents and a count to any agent type.

Used to specify how many instances of an agent to include in an swarm,
along with fallback agents to try if the primary fails."""
    model_config = ConfigDict(json_schema_extra={'_expanded_ref': 'agent.Agent', '_expanded_ref_props': ['count', 'fallbacks']})

    root: Union[SwarmAgentsItemVariant1, SwarmAgentsItemVariant2, SwarmAgentsItemVariant3]


class Swarm(BaseModel):
    """A validated Swarm with its computed content-addressed ID.

Created by converting from [`SwarmBase`] via [`TryFrom`]. The conversion:
1. Validates and normalizes each agent
2. Merges duplicate LLMs (by full_id) and sums their counts
3. Sorts LLMs by full_id for deterministic ordering
4. Computes the swarm ID from the sorted (full_id, count) pairs

# Constraints

- Individual LLMs with `count: 0` are skipped
- Total agent count (sum of all counts) must be between 1 and 128"""
    model_config = ConfigDict(title='swarm.Swarm')

    agents: list[SwarmAgentsItem] = Field(..., description='The validated and deduplicated LLMs, sorted by full_id.')
    id: str = Field(..., description='The deterministic content-addressed ID (22-character base62 string).')

