# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from objectiveai.functions.executions.response.unary import FunctionExecution

schema = FunctionExecution.model_json_schema()
