# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_list_swarm():
    from objectiveai.swarm import ListSwarm
    schema = ListSwarm.model_json_schema()
