# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_usage_swarm_response():
    from objectiveai.swarm import UsageSwarmResponse
    schema = UsageSwarmResponse.model_json_schema()
