# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_inline_agent_base_with_fallbacks_variant2():
    from objectiveai.agent import InlineAgentBaseWithFallbacksVariant2
    schema = InlineAgentBaseWithFallbacksVariant2.model_json_schema()
