# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_inline_agent_base_variant1():
    from objectiveai.agent import InlineAgentBaseVariant1
    schema = InlineAgentBaseVariant1.model_json_schema()
