# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from objectiveai.agent import WithFallbacksAndCount_AgentAgentVariant2

schema = WithFallbacksAndCount_AgentAgentVariant2.model_json_schema()
