# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_inline_agent_variant1():
    from objectiveai.agent import InlineAgentVariant1
    schema = InlineAgentVariant1.model_json_schema()
