# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_upstream_variant3():
    from objectiveai.agent import UpstreamVariant3
    schema = UpstreamVariant3.model_json_schema()
