# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_get_agent_variant2():
    from objectiveai.agent import GetAgentVariant2
    schema = GetAgentVariant2.model_json_schema()
