# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_inline_agent_base_with_fallbacks_or_remote_commit_optional_variant2():
    from objectiveai.agent import InlineAgentBaseWithFallbacksOrRemoteCommitOptionalVariant2
    schema = InlineAgentBaseWithFallbacksOrRemoteCommitOptionalVariant2.model_json_schema()
