# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_get_agent_response_variant2():
    from objectiveai.agent import GetAgentResponseVariant2
    schema = GetAgentResponseVariant2.model_json_schema()
