# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from objectiveai.agent import WithFallbacksAndCount_AgentAgentBaseVariant2

schema = WithFallbacksAndCount_AgentAgentBaseVariant2.model_json_schema()
