# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_verbosity():
    from objectiveai.agent.openrouter import Verbosity
    schema = Verbosity.model_json_schema()
