# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from objectiveai.functions.inventions.state import ParamsStateVariant3Variant1

schema = ParamsStateVariant3Variant1.model_json_schema()
