# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Union
from pydantic import BaseModel


class FunctionsProfilesComputationsResponseFittingStats(BaseModel):
    loss: Union[str, float]
    executions: int
    starts: int
    rounds: int
    errors: int

