// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package streaming

type TaskChunk interface {
	isTaskChunk()
}

type TaskChunkVariant1 struct {
	Inner FunctionExecutionTaskChunk
}

func (TaskChunkVariant1) isTaskChunk() {}

type TaskChunkVariant2 struct {
	Inner VectorCompletionTaskChunk
}

func (TaskChunkVariant2) isTaskChunk() {}

type TaskChunkSchema struct{}

func (TaskChunkSchema) SchemaTitle() string { return "functions.executions.response.streaming.TaskChunk" }
func (TaskChunkSchema) SchemaDescription() string { return "" }
func (TaskChunkSchema) Body() map[string]any {
	return map[string]any{
		"anyOf": []any{
			map[string]any{
			"$ref": "functions.executions.response.streaming.FunctionExecutionTaskChunk",
		},
			map[string]any{
			"$ref": "functions.executions.response.streaming.VectorCompletionTaskChunk",
		},
		},
	}
}
