# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Annotated, Union
from pydantic import ConfigDict, Field, RootModel
from objectiveai.weights_entry import WeightsEntry


class WeightsVariant1(RootModel):
    """Simple vector of decimal weights."""
    root: list[Annotated[float, Field(ge=-3.4028234663852886e+38, le=3.4028234663852886e+38)]]


class WeightsVariant2(RootModel):
    """Vector of entries with optional invert flags."""
    root: list[WeightsEntry]


class Weights(RootModel):
    """Weights for a swarm's agents.

- `Weights(Vec<Decimal>)` - simple representation (no inversion)
- `Entries(Vec<WeightsEntry>)` - weights with optional per-agent `invert`"""
    model_config = ConfigDict(title='Weights')

    root: Union[WeightsVariant1, WeightsVariant2]

