// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package message

type AssistantToolCallType = string

type AssistantToolCallTypeSchema struct{}

func (AssistantToolCallTypeSchema) SchemaTitle() string { return "agent.completions.message.AssistantToolCallType" }
func (AssistantToolCallTypeSchema) SchemaDescription() string { return "A function call." }
func (AssistantToolCallTypeSchema) Body() map[string]any {
	return map[string]any{
		"type": "string",
		"enum": []any{"function"},
	}
}
