// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package message

type InputAudio struct {
	Data string `json:"data"`
	Format string `json:"format"`
}

func (InputAudio) SchemaTitle() string { return "agent.completions.message.InputAudio" }
func (InputAudio) SchemaDescription() string { return "Audio input for multimodal messages." }
func (InputAudio) FieldDescriptions() map[string]string {
	return map[string]string{
		"data": "Base64-encoded audio data.",
		"format": "The audio format (e.g., \"wav\", \"mp3\").",
	}
}
