// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package message

type SimpleContentPartExpression struct {
	Text any `json:"text" ref:"functions.expression.WithExpression.string"`
	Type string `json:"type" enum:"text"`
}

func (SimpleContentPartExpression) SchemaTitle() string { return "agent.completions.message.SimpleContentPartExpression" }
func (SimpleContentPartExpression) SchemaDescription() string { return "A text part expression." }
func (SimpleContentPartExpression) FieldDescriptions() map[string]string {
	return map[string]string{
		"text": "The text expression.",
	}
}
