// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package message

type SimpleContentExpression = any

type SimpleContentExpressionSchema struct{}

func (SimpleContentExpressionSchema) JSONSchema() map[string]any {
	return map[string]any{
		"title": "agent.completions.message.SimpleContentExpression",
		"description": "Expression variant of [`SimpleContent`] for dynamic content.",
		"anyOf": []any{
			map[string]any{
			"description": "Plain text content.",
			"type": "string",
		},
			map[string]any{
			"description": "Multi-part text content expressions.",
			"type": "array",
			"items": map[string]any{"$ref": "functions.expression.WithExpression.agent.completions.message.SimpleContentPartExpression"},
		},
		},
	}
}
