// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package message

type ToolMessageExpression struct {
	Content any `json:"content"`
	ToolCallID any `json:"tool_call_id"`
}

func (ToolMessageExpression) JSONSchema() map[string]any {
	return map[string]any{
		"title": "agent.completions.message.ToolMessageExpression",
		"description": "Expression variant of [`ToolMessage`] for dynamic content.",
		"type": "object",
		"properties": map[string]any{
			"content": map[string]any{
			"description": "The content expression.",
			"$ref": "functions.expression.WithExpression.agent.completions.message.RichContentExpression",
		},
			"tool_call_id": map[string]any{
			"description": "The tool call ID expression.",
			"$ref": "functions.expression.WithExpression.string",
		},
		},
	}
}
