// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package message

type ToolMessage struct {
	Content any `json:"content"`
	ToolCallID string `json:"tool_call_id"`
}

func (ToolMessage) JSONSchema() map[string]any {
	return map[string]any{
		"title": "agent.completions.message.ToolMessage",
		"description": "A tool message containing the result of a tool call.",
		"type": "object",
		"properties": map[string]any{
			"content": map[string]any{
			"description": "The content of the tool response.",
			"$ref": "agent.completions.message.RichContent",
		},
			"tool_call_id": map[string]any{
			"description": "The ID of the tool call this message responds to.",
			"type": "string",
		},
		},
	}
}
