# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from pydantic import BaseModel
from objectiveai.agent.with_fallbacks_and_count import AgentWithFallbacksAndCountAgentAgentBase


class EnsembleEnsembleBase(BaseModel):
    """The base configuration for an Ensemble (without computed ID).

Contains a list of agent configurations that will be validated, deduplicated,
and sorted when converting to [`Ensemble`]."""
    agents: list[AgentWithFallbacksAndCountAgentAgentBase]

