# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional
from pydantic import BaseModel, ConfigDict, Field
from objectiveai.config.favorite import Favorite


class AgentsConfig(BaseModel):
    model_config = ConfigDict(title='config.AgentsConfig')

    favorites: Optional[list[Favorite]] = Field(None, json_schema_extra={'omitempty': True})

