# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Literal


AgentOpenrouterReasoningSummaryVerbosity = Literal['auto', 'concise', 'detailed']
"""Verbosity of the reasoning summary included in responses.

Only supported by some models."""

