# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional, Union
from pydantic import BaseModel, Field
from objectiveai.agent.openrouter.reasoning_effort import AgentOpenrouterReasoningEffort
from objectiveai.agent.openrouter.reasoning_summary_verbosity import AgentOpenrouterReasoningSummaryVerbosity


class AgentOpenrouterReasoning(BaseModel):
    """Configuration for model reasoning/thinking capabilities.

Some models (like o1, o3, Claude with extended thinking) support
explicit reasoning modes where they can "think" before responding.
This struct configures those capabilities.

**Note:** The `max_tokens`, `effort`, and `summary_verbosity` fields are
only supported by some models. Unsupported fields are silently ignored."""
    enabled: Optional[Union[bool, None]] = Field(None, description='Whether reasoning is enabled. Defaults to `true` if other fields are set.')
    max_tokens: Optional[Union[int, None]] = Field(None, description='Maximum tokens for the reasoning/thinking output.\n\nOnly supported by some models.', ge=0, json_schema_extra={'format': 'uint64'})
    effort: Optional[AgentOpenrouterReasoningEffort] = Field(None, description='The reasoning effort level.\n\nOnly supported by some models.')
    summary_verbosity: Optional[AgentOpenrouterReasoningSummaryVerbosity] = Field(None, description='Verbosity of reasoning summaries in the response.\n\nOnly supported by some models.')

