# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_message_developer():
    from objectiveai.agent.completions.message import MessageDeveloper
    schema = MessageDeveloper.model_json_schema()
