# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_inline_function_variant2():
    from objectiveai.functions.alpha_vector import InlineFunctionVariant2
    schema = InlineFunctionVariant2.model_json_schema()
