// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { SwarmSwarmSchema } from "./swarm";

export const SwarmGetSwarmSchema = SwarmSwarmSchema.and(z.object({
  created: z.number().int().min(0).max(18446744073709552000).describe("Unix timestamp when this Swarm was first used."),
})).describe("Response containing a single Swarm with creation timestamp.").meta({ title: "swarm.GetSwarm" });
export type SwarmGetSwarm = z.infer<typeof SwarmGetSwarmSchema>;
