# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_task_profile_remote():
    from objectiveai.functions import TaskProfileRemote
    schema = TaskProfileRemote.model_json_schema()
