# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_vector_function_task_expression_mock():
    from objectiveai.functions import VectorFunctionTaskExpressionMock
    schema = VectorFunctionTaskExpressionMock.model_json_schema()
