# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from objectiveai.functions.check import ScalarFieldsValidation

schema = ScalarFieldsValidation.model_json_schema()
