# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_provider_sort_variant3():
    from objectiveai.agent.completions.request import ProviderSortVariant3
    schema = ProviderSortVariant3.model_json_schema()
