# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_provider_sort_variant1():
    from objectiveai.agent.completions.request import ProviderSortVariant1
    schema = ProviderSortVariant1.model_json_schema()
