# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from objectiveai.agent.completions.request import ResponseFormatParamVariant1

schema = ResponseFormatParamVariant1.model_json_schema()
