# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from objectiveai.agent.completions.request import ProviderSortVariant2

schema = ProviderSortVariant2.model_json_schema()
