# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional, Union
from pydantic import BaseModel
from objectiveai.agent.completions.response.usage import AgentCompletionsResponseUsage
from objectiveai.functions.executions.response.streaming.object import FunctionsExecutionsResponseStreamingObject
from objectiveai.functions.executions.response.streaming.reasoning_summary_chunk import FunctionsExecutionsResponseStreamingReasoningSummaryChunk
from objectiveai.functions.executions.response.streaming.task_chunk import FunctionsExecutionsResponseStreamingTaskChunk
from objectiveai.functions.expression.task_output_owned import FunctionsExpressionTaskOutputOwned
from objectiveai.response_error import ResponseError


class FunctionsProfilesComputationsResponseStreamingFunctionExecutionChunk(BaseModel):
    index: int
    dataset: int
    n: int
    retry: int
    id: str
    tasks: list[FunctionsExecutionsResponseStreamingTaskChunk]
    tasks_errors: Optional[Union[bool, None]] = None
    reasoning: Optional[FunctionsExecutionsResponseStreamingReasoningSummaryChunk] = None
    output: Optional[FunctionsExpressionTaskOutputOwned] = None
    error: Optional[ResponseError] = None
    retry_token: Optional[Union[str, None]] = None
    created: int
    function: Optional[Union[str, None]] = None
    profile: Optional[Union[str, None]] = None
    object: FunctionsExecutionsResponseStreamingObject
    usage: Optional[AgentCompletionsResponseUsage] = None

