# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional
from pydantic import BaseModel, ConfigDict, Field
from objectiveai.agent.completions.response.usage import AgentCompletionsResponseUsage
from objectiveai.functions.inline_tasks_profile import FunctionsInlineTasksProfile
from objectiveai.functions.profiles.computations.response.fitting_stats import FunctionsProfilesComputationsResponseFittingStats
from objectiveai.functions.profiles.computations.response.streaming.function_execution_chunk import FunctionsProfilesComputationsResponseStreamingFunctionExecutionChunk
from objectiveai.functions.profiles.computations.response.streaming.object import FunctionsProfilesComputationsResponseStreamingObject


class FunctionsProfilesComputationsResponseStreamingFunctionProfileComputationChunk(BaseModel):
    model_config = ConfigDict(title='functions.profiles.computations.response.streaming.FunctionProfileComputationChunk')

    created: int = Field(..., ge=0, le=18446744073709551615)
    executions: list[FunctionsProfilesComputationsResponseStreamingFunctionExecutionChunk]
    executions_errors: Optional[bool] = None
    fitting_stats: Optional[FunctionsProfilesComputationsResponseFittingStats] = None
    function: Optional[str] = None
    id: str
    object: FunctionsProfilesComputationsResponseStreamingObject
    profile: Optional[FunctionsInlineTasksProfile] = None
    retry_token: Optional[str] = None
    usage: Optional[AgentCompletionsResponseUsage] = None

