# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.


def test_target_variant1():
    from objectiveai.functions.profiles.computations.request import TargetVariant1
    schema = TargetVariant1.model_json_schema()
