# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from objectiveai.functions.profiles.computations.request import TargetVariant2

schema = TargetVariant2.model_json_schema()
