# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from objectiveai.functions.profiles.computations.request import FunctionProfileComputationCreateParamsVariant1

schema = FunctionProfileComputationCreateParamsVariant1.model_json_schema()
