// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package response

type FittingStats struct {
	Errors uint32 `json:"errors" min:"0" max:"4294967295"`
	Executions uint32 `json:"executions" min:"0" max:"4294967295"`
	Loss float64 `json:"loss" min:"-3.4028234663852886e+38" max:"3.4028234663852886e+38"`
	Rounds uint32 `json:"rounds" min:"0" max:"4294967295"`
	Starts uint32 `json:"starts" min:"0" max:"4294967295"`
}

func (FittingStats) SchemaTitle() string { return "functions.profiles.computations.response.FittingStats" }
func (FittingStats) SchemaDescription() string { return "" }
