// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install-zod.cjs from objectiveai-json-schema/.
import { z } from "zod";
import { VectorCompletionsCacheCacheVoteRequestOwnedSchema } from "./cacheVoteRequestOwned";
import { VectorCompletionsCacheCacheVoteRequestRefSchema } from "./cacheVoteRequestRef";

export const VectorCompletionsCacheCacheVoteRequestSchema = z.union([z.object({
  Ref: VectorCompletionsCacheCacheVoteRequestRefSchema,
}).strict(), z.object({
  Owned: VectorCompletionsCacheCacheVoteRequestOwnedSchema,
}).strict()]).meta({ title: "vector.completions.cache.CacheVoteRequest" });
export type VectorCompletionsCacheCacheVoteRequest = z.infer<typeof VectorCompletionsCacheCacheVoteRequestSchema>;
