//! ObjectiveAI SDK for Rust.
//!
//! This crate provides data structures, validation, and client-side compilation
//! for the ObjectiveAI API - a platform for scoring, ranking, and simulating
//! preferences using ensembles of agents.
//!
//! # Core Concepts
//!
//! - **Agent**: A configured instance of a single upstream language model
//! - **Ensemble**: A collection of Agents used together for voting
//! - **Vector Completion**: Runs multiple agents to vote on responses, producing weighted scores
//! - **Function**: A composable scoring pipeline built from Vector Completions
//! - **Profile**: Learned weights for a Function, trained on example data
//!
//! # Features
//!
//! - `http` (default): Enables the HTTP client for making API requests
//!
//! # Modules
//!
//! - [`auth`] - API authentication types
//! - [`agent`] - Agent definitions, configuration, and completion APIs
//! - [`ensemble`] - Ensemble definitions and validation
//! - [`error`] - Error types
//! - [`functions`] - Function definitions, execution, and client-side compilation
//! - [`prefixed_uuid`] - UUID utilities
//! - [`vector`] - Vector completion APIs
//!
//! When the `http` feature is enabled:
//! - [`HttpClient`] - HTTP client for API requests
//! - [`HttpError`] - HTTP error types

pub mod agent;
pub mod arbitrary_util;
pub mod auth;
pub mod ensemble;
pub mod error;
pub mod functions;
pub mod json_schema;
pub mod prefixed_uuid;
pub mod vector;

#[cfg(test)]
mod tests;

#[cfg(test)]
mod util;

#[cfg(feature = "http")]
mod http;

#[cfg(feature = "http")]
pub use http::*;

/// Returns JSON Schemas for all public types that derive `JsonSchema`.
///
/// Each schema is generated via `schemars::schema_for!()` and includes
/// the type's `$defs` for referenced types. The schema title matches
/// the `#[schemars(rename = "...")]` attribute on each type.
pub fn json_schemas() -> Vec<schemars::Schema> {
    vec![
        schemars::schema_for!(agent::AgentBase),
        schemars::schema_for!(agent::Agent),
        schemars::schema_for!(agent::claude_agent_sdk::AgentBase),
        schemars::schema_for!(agent::claude_agent_sdk::Agent),
        schemars::schema_for!(agent::claude_agent_sdk::Effort),
        schemars::schema_for!(agent::claude_agent_sdk::OutputMode),
        schemars::schema_for!(agent::claude_agent_sdk::Upstream),
        schemars::schema_for!(agent::completions::message::AssistantMessage),
        schemars::schema_for!(agent::completions::message::AssistantMessageExpression),
        schemars::schema_for!(agent::completions::message::AssistantToolCall),
        schemars::schema_for!(agent::completions::message::AssistantToolCallExpression),
        schemars::schema_for!(agent::completions::message::AssistantToolCallFunction),
        schemars::schema_for!(agent::completions::message::AssistantToolCallDelta),
        schemars::schema_for!(agent::completions::message::AssistantToolCallType),
        schemars::schema_for!(agent::completions::message::AssistantToolCallFunctionDelta),
        schemars::schema_for!(agent::completions::message::AssistantToolCallFunctionExpression),
        schemars::schema_for!(agent::completions::message::DeveloperMessage),
        schemars::schema_for!(agent::completions::message::DeveloperMessageExpression),
        schemars::schema_for!(agent::completions::message::Message),
        schemars::schema_for!(agent::completions::message::MessageExpression),
        schemars::schema_for!(agent::completions::message::RichContent),
        schemars::schema_for!(agent::completions::message::RichContentExpression),
        schemars::schema_for!(agent::completions::message::RichContentPart),
        schemars::schema_for!(agent::completions::message::RichContentPartExpression),
        schemars::schema_for!(agent::completions::message::ImageUrl),
        schemars::schema_for!(agent::completions::message::ImageUrlDetail),
        schemars::schema_for!(agent::completions::message::InputAudio),
        schemars::schema_for!(agent::completions::message::VideoUrl),
        schemars::schema_for!(agent::completions::message::File),
        schemars::schema_for!(agent::completions::message::SimpleContent),
        schemars::schema_for!(agent::completions::message::SimpleContentExpression),
        schemars::schema_for!(agent::completions::message::SimpleContentPart),
        schemars::schema_for!(agent::completions::message::SimpleContentPartExpression),
        schemars::schema_for!(agent::completions::message::SystemMessage),
        schemars::schema_for!(agent::completions::message::SystemMessageExpression),
        schemars::schema_for!(agent::completions::message::ToolMessage),
        schemars::schema_for!(agent::completions::message::ToolMessageExpression),
        schemars::schema_for!(agent::completions::message::UserMessage),
        schemars::schema_for!(agent::completions::message::UserMessageExpression),
        schemars::schema_for!(agent::completions::request::Agent),
        schemars::schema_for!(agent::completions::request::AgentCompletionCreateParams),
        schemars::schema_for!(agent::completions::request::Provider),
        schemars::schema_for!(agent::completions::request::ProviderDataCollection),
        schemars::schema_for!(agent::completions::request::ProviderSort),
        schemars::schema_for!(agent::completions::request::ProviderMaxPrice),
        schemars::schema_for!(agent::completions::request::ResponseFormat),
        schemars::schema_for!(agent::completions::request::ResponseFormatParam),
        schemars::schema_for!(agent::completions::response::AssistantRole),
        schemars::schema_for!(agent::completions::response::FinishReason),
        schemars::schema_for!(agent::completions::response::Logprobs),
        schemars::schema_for!(agent::completions::response::Logprob),
        schemars::schema_for!(agent::completions::response::TopLogprob),
        schemars::schema_for!(agent::completions::response::streaming::AgentCompletionChunk),
        schemars::schema_for!(agent::completions::response::streaming::AssistantResponseChunk),
        schemars::schema_for!(agent::completions::response::streaming::MessageChunk),
        schemars::schema_for!(agent::completions::response::streaming::Object),
        schemars::schema_for!(agent::completions::response::ToolResponse),
        schemars::schema_for!(agent::completions::response::ToolRole),
        schemars::schema_for!(agent::completions::response::unary::AgentCompletion),
        schemars::schema_for!(agent::completions::response::unary::AssistantResponse),
        schemars::schema_for!(agent::completions::response::unary::Message),
        schemars::schema_for!(agent::completions::response::unary::Object),
        schemars::schema_for!(agent::completions::response::UpstreamUsage),
        schemars::schema_for!(agent::completions::response::Usage),
        schemars::schema_for!(agent::completions::response::CompletionTokensDetails),
        schemars::schema_for!(agent::completions::response::PromptTokensDetails),
        schemars::schema_for!(agent::completions::response::CostDetails),
        schemars::schema_for!(agent::McpServer),
        schemars::schema_for!(agent::mock::AgentBase),
        schemars::schema_for!(agent::mock::Agent),
        schemars::schema_for!(agent::mock::OutputMode),
        schemars::schema_for!(agent::mock::Upstream),
        schemars::schema_for!(agent::openrouter::AgentBase),
        schemars::schema_for!(agent::openrouter::Agent),
        schemars::schema_for!(agent::openrouter::OutputMode),
        schemars::schema_for!(agent::openrouter::Provider),
        schemars::schema_for!(agent::openrouter::ProviderQuantization),
        schemars::schema_for!(agent::openrouter::Reasoning),
        schemars::schema_for!(agent::openrouter::ReasoningEffort),
        schemars::schema_for!(agent::openrouter::ReasoningSummaryVerbosity),
        schemars::schema_for!(agent::openrouter::Stop),
        schemars::schema_for!(agent::openrouter::Upstream),
        schemars::schema_for!(agent::openrouter::Verbosity),
        schemars::schema_for!(agent::OutputMode),
        schemars::schema_for!(agent::response::ListAgent),
        schemars::schema_for!(agent::response::ListAgentItem),
        schemars::schema_for!(agent::response::GetAgent),
        schemars::schema_for!(agent::response::UsageAgent),
        schemars::schema_for!(agent::Upstream),
        schemars::schema_for!(auth::ApiKeyWithMetadata),
        schemars::schema_for!(auth::request::CreateApiKeyRequest),
        schemars::schema_for!(auth::request::DisableApiKeyRequest),
        schemars::schema_for!(auth::request::CreateOpenRouterByokApiKeyRequest),
        schemars::schema_for!(auth::response::GetCreditsResponse),
        schemars::schema_for!(auth::response::ListApiKeyResponse),
        schemars::schema_for!(auth::response::ListApiKeyItem),
        schemars::schema_for!(auth::response::GetOpenRouterByokApiKeyResponse),
        schemars::schema_for!(ensemble::EnsembleBase),
        schemars::schema_for!(ensemble::Ensemble),
        schemars::schema_for!(ensemble::response::ListEnsemble),
        schemars::schema_for!(ensemble::response::ListEnsembleItem),
        schemars::schema_for!(ensemble::response::GetEnsemble),
        schemars::schema_for!(ensemble::response::UsageEnsemble),
        schemars::schema_for!(error::ResponseError),
        schemars::schema_for!(error::request::ErrorCreateParams),
        schemars::schema_for!(error::response::ErrorResponse),
        schemars::schema_for!(functions::alpha_scalar::RemoteFunction),
        schemars::schema_for!(functions::alpha_scalar::InlineFunction),
        schemars::schema_for!(functions::alpha_scalar::BranchTaskExpression),
        schemars::schema_for!(functions::alpha_scalar::PartialPlaceholderBranchTaskExpression),
        schemars::schema_for!(functions::alpha_scalar::LeafTaskExpression),
        schemars::schema_for!(functions::alpha_scalar::ScalarFunctionTaskExpression),
        schemars::schema_for!(functions::alpha_scalar::PlaceholderScalarFunctionTaskExpression),
        schemars::schema_for!(functions::alpha_scalar::PartialPlaceholderScalarFunctionTaskExpression),
        schemars::schema_for!(functions::alpha_scalar::VectorCompletionTaskExpression),
        schemars::schema_for!(functions::alpha_vector::expression::VectorFunctionInputSchema),
        schemars::schema_for!(functions::alpha_vector::expression::VectorFunctionInputValueExpression),
        schemars::schema_for!(functions::alpha_vector::expression::VectorFunctionInputValue),
        schemars::schema_for!(functions::alpha_vector::RemoteFunction),
        schemars::schema_for!(functions::alpha_vector::InlineFunction),
        schemars::schema_for!(functions::alpha_vector::BranchTaskExpression),
        schemars::schema_for!(functions::alpha_vector::PartialPlaceholderBranchTaskExpression),
        schemars::schema_for!(functions::alpha_vector::LeafTaskExpression),
        schemars::schema_for!(functions::alpha_vector::ScalarFunctionTaskExpression),
        schemars::schema_for!(functions::alpha_vector::VectorFunctionTaskExpression),
        schemars::schema_for!(functions::alpha_vector::PlaceholderScalarFunctionTaskExpression),
        schemars::schema_for!(functions::alpha_vector::PartialPlaceholderScalarFunctionTaskExpression),
        schemars::schema_for!(functions::alpha_vector::PlaceholderVectorFunctionTaskExpression),
        schemars::schema_for!(functions::alpha_vector::PartialPlaceholderVectorFunctionTaskExpression),
        schemars::schema_for!(functions::alpha_vector::VectorCompletionTaskExpression),
        schemars::schema_for!(functions::check::ScalarFieldsValidation),
        schemars::schema_for!(functions::check::VectorFieldsValidation),
        schemars::schema_for!(functions::executions::request::FunctionInlineProfileInlineRequestBody),
        schemars::schema_for!(functions::executions::request::FunctionInlineProfileRemoteRequestBody),
        schemars::schema_for!(functions::executions::request::FunctionRemoteProfileInlineRequestBody),
        schemars::schema_for!(functions::executions::request::FunctionRemoteProfileRemoteRequestBody),
        schemars::schema_for!(functions::executions::request::FunctionRemoteProfileInlineRequestPath),
        schemars::schema_for!(functions::executions::request::FunctionInlineProfileRemoteRequestPath),
        schemars::schema_for!(functions::executions::request::FunctionRemoteProfileRemoteRequestPath),
        schemars::schema_for!(functions::executions::request::Reasoning),
        schemars::schema_for!(functions::executions::request::Request),
        schemars::schema_for!(functions::executions::request::FunctionExecutionCreateParams),
        schemars::schema_for!(functions::executions::request::Strategy),
        schemars::schema_for!(functions::executions::response::streaming::FunctionExecutionChunk),
        schemars::schema_for!(functions::executions::response::streaming::FunctionExecutionTaskChunk),
        schemars::schema_for!(functions::executions::response::streaming::Object),
        schemars::schema_for!(functions::executions::response::streaming::ReasoningSummaryChunk),
        schemars::schema_for!(functions::executions::response::streaming::TaskChunk),
        schemars::schema_for!(functions::executions::response::streaming::VectorCompletionTaskChunk),
        schemars::schema_for!(functions::executions::response::unary::FunctionExecution),
        schemars::schema_for!(functions::executions::response::unary::FunctionExecutionTask),
        schemars::schema_for!(functions::executions::response::unary::Object),
        schemars::schema_for!(functions::executions::response::unary::ReasoningSummary),
        schemars::schema_for!(functions::executions::response::unary::Task),
        schemars::schema_for!(functions::executions::response::unary::VectorCompletionTask),
        schemars::schema_for!(functions::executions::RetryToken),
        schemars::schema_for!(functions::expression::Expression),
        schemars::schema_for!(functions::expression::InputValue),
        schemars::schema_for!(functions::expression::InputValueExpression),
        schemars::schema_for!(functions::expression::InputSchema),
        schemars::schema_for!(functions::expression::AnyOfInputSchema),
        schemars::schema_for!(functions::expression::ObjectInputSchema),
        schemars::schema_for!(functions::expression::ArrayInputSchema),
        schemars::schema_for!(functions::expression::StringInputSchema),
        schemars::schema_for!(functions::expression::IntegerInputSchema),
        schemars::schema_for!(functions::expression::NumberInputSchema),
        schemars::schema_for!(functions::expression::BooleanInputSchema),
        schemars::schema_for!(functions::expression::ImageInputSchema),
        schemars::schema_for!(functions::expression::AudioInputSchema),
        schemars::schema_for!(functions::expression::VideoInputSchema),
        schemars::schema_for!(functions::expression::FileInputSchema),
        schemars::schema_for!(functions::expression::ObjectInputSchemaType),
        schemars::schema_for!(functions::expression::ArrayInputSchemaType),
        schemars::schema_for!(functions::expression::StringInputSchemaType),
        schemars::schema_for!(functions::expression::IntegerInputSchemaType),
        schemars::schema_for!(functions::expression::NumberInputSchemaType),
        schemars::schema_for!(functions::expression::BooleanInputSchemaType),
        schemars::schema_for!(functions::expression::ImageInputSchemaType),
        schemars::schema_for!(functions::expression::AudioInputSchemaType),
        schemars::schema_for!(functions::expression::VideoInputSchemaType),
        schemars::schema_for!(functions::expression::FileInputSchemaType),
        schemars::schema_for!(functions::expression::Params<'static, 'static>),
        schemars::schema_for!(functions::expression::ParamsOwned),
        schemars::schema_for!(functions::expression::ParamsRef<'static, 'static>),
        schemars::schema_for!(functions::expression::TaskOutput<'static>),
        schemars::schema_for!(functions::expression::TaskOutputOwned),
        schemars::schema_for!(functions::expression::TaskOutputRef<'static>),
        schemars::schema_for!(functions::expression::Special),
        schemars::schema_for!(functions::FullRemoteFunction),
        schemars::schema_for!(functions::FullInlineFunction),
        schemars::schema_for!(functions::AlphaRemoteFunction),
        schemars::schema_for!(functions::AlphaInlineFunction),
        schemars::schema_for!(functions::Function),
        schemars::schema_for!(functions::RemoteFunction),
        schemars::schema_for!(functions::InlineFunction),
        schemars::schema_for!(functions::FunctionType),
        schemars::schema_for!(functions::inventions::recursive::request::FunctionInventionRecursiveCreateParams),
        schemars::schema_for!(functions::inventions::recursive::response::streaming::FunctionInventionChunk),
        schemars::schema_for!(functions::inventions::recursive::response::streaming::FunctionInventionRecursiveChunk),
        schemars::schema_for!(functions::inventions::recursive::response::streaming::Object),
        schemars::schema_for!(functions::inventions::recursive::response::unary::FunctionInvention),
        schemars::schema_for!(functions::inventions::recursive::response::unary::FunctionInventionRecursive),
        schemars::schema_for!(functions::inventions::recursive::response::unary::Object),
        schemars::schema_for!(functions::inventions::request::FunctionInventionCreateParams),
        schemars::schema_for!(functions::inventions::response::streaming::AgentCompletionChunk),
        schemars::schema_for!(functions::inventions::response::streaming::FunctionInventionChunk),
        schemars::schema_for!(functions::inventions::response::streaming::Object),
        schemars::schema_for!(functions::inventions::response::unary::AgentCompletion),
        schemars::schema_for!(functions::inventions::response::unary::FunctionInvention),
        schemars::schema_for!(functions::inventions::response::unary::Object),
        schemars::schema_for!(functions::inventions::IndexObject),
        schemars::schema_for!(functions::inventions::EssayObject),
        schemars::schema_for!(functions::inventions::EssayTasksObject),
        schemars::schema_for!(functions::inventions::TasksLengthObject),
        schemars::schema_for!(functions::inventions::DescriptionObject),
        schemars::schema_for!(functions::inventions::AlphaScalarBranchState),
        schemars::schema_for!(functions::inventions::AlphaScalarLeafState),
        schemars::schema_for!(functions::inventions::AlphaScalarState),
        schemars::schema_for!(functions::inventions::AlphaVectorBranchState),
        schemars::schema_for!(functions::inventions::AlphaVectorLeafState),
        schemars::schema_for!(functions::inventions::AlphaVectorState),
        schemars::schema_for!(functions::inventions::State),
        schemars::schema_for!(functions::inventions::ParamsState),
        schemars::schema_for!(functions::inventions::Params),
        schemars::schema_for!(functions::RemoteFunctionPath),
        schemars::schema_for!(functions::Profile),
        schemars::schema_for!(functions::RemoteProfile),
        schemars::schema_for!(functions::InlineProfile),
        schemars::schema_for!(functions::RemoteTasksProfile),
        schemars::schema_for!(functions::RemoteAutoProfile),
        schemars::schema_for!(functions::InlineTasksProfile),
        schemars::schema_for!(functions::InlineAutoProfile),
        schemars::schema_for!(functions::TaskProfile),
        schemars::schema_for!(functions::profiles::computations::request::FunctionInlineRequestBody),
        schemars::schema_for!(functions::profiles::computations::request::FunctionRemoteRequestBody),
        schemars::schema_for!(functions::profiles::computations::request::DatasetItem),
        schemars::schema_for!(functions::profiles::computations::request::Target),
        schemars::schema_for!(functions::profiles::computations::request::FunctionRemoteRequestPath),
        schemars::schema_for!(functions::profiles::computations::request::Request),
        schemars::schema_for!(functions::profiles::computations::request::FunctionProfileComputationCreateParams),
        schemars::schema_for!(functions::profiles::computations::response::FittingStats),
        schemars::schema_for!(functions::profiles::computations::response::streaming::FunctionExecutionChunk),
        schemars::schema_for!(functions::profiles::computations::response::streaming::FunctionProfileComputationChunk),
        schemars::schema_for!(functions::profiles::computations::response::streaming::Object),
        schemars::schema_for!(functions::profiles::computations::response::unary::FunctionExecution),
        schemars::schema_for!(functions::profiles::computations::response::unary::FunctionProfileComputation),
        schemars::schema_for!(functions::profiles::computations::response::unary::Object),
        schemars::schema_for!(functions::profiles::computations::RetryToken),
        schemars::schema_for!(functions::profiles::request::ListProfilesQueryParameters),
        schemars::schema_for!(functions::profiles::request::ListProfilesSource),
        schemars::schema_for!(functions::profiles::response::ListProfile),
        schemars::schema_for!(functions::profiles::response::ListProfileItem),
        schemars::schema_for!(functions::profiles::response::GetProfile),
        schemars::schema_for!(functions::profiles::response::UsageProfile),
        schemars::schema_for!(functions::Remote),
        schemars::schema_for!(functions::request::ListFunctionsQueryParameters),
        schemars::schema_for!(functions::request::ListFunctionsSource),
        schemars::schema_for!(functions::request::ListFunctionProfilePairsQueryParameters),
        schemars::schema_for!(functions::request::ListFunctionProfilePairsSource),
        schemars::schema_for!(functions::response::ListFunction),
        schemars::schema_for!(functions::response::ListFunctionItem),
        schemars::schema_for!(functions::response::GetFunction),
        schemars::schema_for!(functions::response::UsageFunction),
        schemars::schema_for!(functions::response::ListFunctionProfilePair),
        schemars::schema_for!(functions::response::ListFunctionProfilePairItem),
        schemars::schema_for!(functions::response::GetFunctionProfilePair),
        schemars::schema_for!(functions::response::UsageFunctionProfilePair),
        schemars::schema_for!(functions::TaskExpression),
        schemars::schema_for!(functions::Task),
        schemars::schema_for!(functions::ScalarFunctionTaskExpression),
        schemars::schema_for!(functions::ScalarFunctionTask),
        schemars::schema_for!(functions::VectorFunctionTaskExpression),
        schemars::schema_for!(functions::VectorFunctionTask),
        schemars::schema_for!(functions::VectorCompletionTaskExpression),
        schemars::schema_for!(functions::VectorCompletionTask),
        schemars::schema_for!(functions::PlaceholderScalarFunctionTaskExpression),
        schemars::schema_for!(functions::PlaceholderScalarFunctionTask),
        schemars::schema_for!(functions::PlaceholderVectorFunctionTaskExpression),
        schemars::schema_for!(functions::PlaceholderVectorFunctionTask),
        schemars::schema_for!(functions::CompiledTask),
        schemars::schema_for!(prefixed_uuid::PrefixedUuid<'a', 'p', 'k'>),
        schemars::schema_for!(vector::completions::cache::request::CacheVoteRequest<'static>),
        schemars::schema_for!(vector::completions::cache::request::CacheVoteRequestRef<'static>),
        schemars::schema_for!(vector::completions::cache::request::CacheVoteRequestOwned),
        schemars::schema_for!(vector::completions::cache::response::CompletionVotes),
        schemars::schema_for!(vector::completions::cache::response::CacheVote),
        schemars::schema_for!(vector::completions::request::Ensemble),
        schemars::schema_for!(vector::completions::request::ProfileEntry),
        schemars::schema_for!(vector::completions::request::Profile),
        schemars::schema_for!(vector::completions::request::VectorCompletionCreateParams),
        schemars::schema_for!(vector::completions::response::streaming::AgentCompletionChunk),
        schemars::schema_for!(vector::completions::response::streaming::Object),
        schemars::schema_for!(vector::completions::response::streaming::VectorCompletionChunk),
        schemars::schema_for!(vector::completions::response::unary::AgentCompletion),
        schemars::schema_for!(vector::completions::response::unary::Object),
        schemars::schema_for!(vector::completions::response::unary::VectorCompletion),
        schemars::schema_for!(vector::completions::response::Vote),
        schemars::schema_for!(vector::completions::VectorResponses),
        schemars::schema_for!(agent::WithFallbacksAndCount<agent::AgentBase>),
        schemars::schema_for!(agent::WithFallbacksAndCount<agent::Agent>),
        schemars::schema_for!(functions::expression::OneOrMany<String>),
        schemars::schema_for!(functions::expression::WithExpression<String>),
        schemars::schema_for!(functions::expression::WithExpression<Option<String>>),
        schemars::schema_for!(functions::expression::WithExpression<functions::expression::InputValueExpression>),
        schemars::schema_for!(functions::expression::WithExpression<agent::completions::message::MessageExpression>),
        schemars::schema_for!(functions::expression::WithExpression<agent::completions::message::AssistantToolCallExpression>),
        schemars::schema_for!(functions::expression::WithExpression<agent::completions::message::AssistantToolCallFunctionExpression>),
        schemars::schema_for!(functions::expression::WithExpression<agent::completions::message::File>),
        schemars::schema_for!(functions::expression::WithExpression<agent::completions::message::ImageUrl>),
        schemars::schema_for!(functions::expression::WithExpression<agent::completions::message::InputAudio>),
        schemars::schema_for!(functions::expression::WithExpression<agent::completions::message::RichContentExpression>),
        schemars::schema_for!(functions::expression::WithExpression<agent::completions::message::RichContentPartExpression>),
        schemars::schema_for!(functions::expression::WithExpression<agent::completions::message::SimpleContentExpression>),
        schemars::schema_for!(functions::expression::WithExpression<agent::completions::message::SimpleContentPartExpression>),
        schemars::schema_for!(functions::expression::WithExpression<agent::completions::message::VideoUrl>),
        schemars::schema_for!(functions::expression::WithExpression<Option<agent::completions::message::RichContentExpression>>),
        schemars::schema_for!(functions::expression::WithExpression<Option<Vec<functions::expression::WithExpression<agent::completions::message::AssistantToolCallExpression>>>>),
        schemars::schema_for!(functions::expression::WithExpression<Vec<functions::expression::WithExpression<agent::completions::message::MessageExpression>>>),
        schemars::schema_for!(functions::expression::WithExpression<Vec<functions::expression::WithExpression<agent::completions::message::RichContentExpression>>>),
    ]
}

/// Schema helper: produces a `$ref` to `T` for use with `#[schemars(schema_with)]`
/// on `#[serde(flatten)]` fields, preventing schemars from merging the inner type's
/// schema into the parent.
pub fn flatten_schema<T: schemars::JsonSchema>(
    generator: &mut schemars::SchemaGenerator,
) -> schemars::Schema {
    generator.subschema_for::<T>()
}
