// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/install_go.go from objectiveai-json-schema/.
package check

type VectorFieldsValidation struct {
	InputMerge any `json:"input_merge" ref:"functions.expression.Expression"`
	InputSchema any `json:"input_schema" ref:"functions.expression.InputSchema"`
	InputSplit any `json:"input_split" ref:"functions.expression.Expression"`
	OutputLength any `json:"output_length" ref:"functions.expression.Expression"`
}

func (VectorFieldsValidation) SchemaTitle() string { return "functions.check.VectorFieldsValidation" }
func (VectorFieldsValidation) SchemaDescription() string { return "The 4 fields needed to validate a vector function's split/merge behavior." }
