# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional, Union
from pydantic import BaseModel
from objectiveai.agent.completions.message.assistant_tool_call import AgentCompletionsMessageAssistantToolCall
from objectiveai.agent.completions.message.rich_content import AgentCompletionsMessageRichContent


class AgentCompletionsMessageAssistantMessage(BaseModel):
    """An assistant message (model's previous response)."""
    content: Optional[AgentCompletionsMessageRichContent] = None
    name: Optional[Union[str, None]] = None
    refusal: Optional[Union[str, None]] = None
    tool_calls: Optional[Union[list[AgentCompletionsMessageAssistantToolCall], None]] = None
    reasoning: Optional[Union[str, None]] = None

