# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional
from pydantic import BaseModel, ConfigDict, Field


class AssistantToolCallFunctionDelta(BaseModel):
    """Function call details in a streaming tool call."""
    model_config = ConfigDict(title='agent.completions.message.AssistantToolCallFunctionDelta')

    arguments: Optional[str] = Field(None, description='The arguments being streamed (accumulated across deltas).')
    name: Optional[str] = Field(None, description='The function name (only present in the first delta).')


import objectiveai.agent.completions.message.assistant_tool_call_function_delta_methods  # noqa: F401, E402
