# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional, Union
from pydantic import BaseModel, Field
from objectiveai.agent.completions.message.assistant_tool_call import AgentCompletionsMessageAssistantToolCall
from objectiveai.agent.completions.message.rich_content import AgentCompletionsMessageRichContent


class AgentCompletionsMessageAssistantMessage(BaseModel):
    """An assistant message (model's previous response)."""
    content: Optional[AgentCompletionsMessageRichContent] = Field(None, description='The message content, if any.')
    name: Optional[Union[str, None]] = Field(None, description='Optional name for the assistant.')
    refusal: Optional[Union[str, None]] = Field(None, description='Refusal message if the model declined to respond.')
    tool_calls: Optional[Union[list[AgentCompletionsMessageAssistantToolCall], None]] = Field(None, description='Tool calls made by the assistant.')
    reasoning: Optional[Union[str, None]] = Field(None, description='Reasoning content from models that support chain-of-thought.')

