# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional
from pydantic import BaseModel, ConfigDict, Field
from objectiveai.agent.completions.message.simple_content import AgentCompletionsMessageSimpleContent


class AgentCompletionsMessageDeveloperMessage(BaseModel):
    """A developer message."""
    model_config = ConfigDict(title='agent.completions.message.DeveloperMessage')

    content: AgentCompletionsMessageSimpleContent = Field(..., description='The message content.')
    name: Optional[str] = Field(None, description='Optional name for the message author.')

