# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import TYPE_CHECKING, Union
from pydantic import RootModel

if TYPE_CHECKING:
    from objectiveai.agent.completions.message.assistant_message_expression import AgentCompletionsMessageAssistantMessageExpression
    from objectiveai.agent.completions.message.developer_message_expression import AgentCompletionsMessageDeveloperMessageExpression
    from objectiveai.agent.completions.message.system_message_expression import AgentCompletionsMessageSystemMessageExpression
    from objectiveai.agent.completions.message.tool_message_expression import AgentCompletionsMessageToolMessageExpression
    from objectiveai.agent.completions.message.user_message_expression import AgentCompletionsMessageUserMessageExpression


class AgentCompletionsMessageMessageExpression(RootModel):
    """A message with expressions for dynamic content.

This is the expression variant of [`Message`] used in function definitions
where message content can be computed from the function input at runtime.
Supports both JMESPath and Starlark expressions."""
    root: Union[AgentCompletionsMessageDeveloperMessageExpression, AgentCompletionsMessageSystemMessageExpression, AgentCompletionsMessageUserMessageExpression, AgentCompletionsMessageAssistantMessageExpression, AgentCompletionsMessageToolMessageExpression]

