# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Union
from pydantic import ConfigDict, RootModel
from objectiveai.agent.completions.message.simple_content_part import SimpleContentPart


class SimpleContentVariant1(RootModel):
    """Plain text content."""
    root: str


class SimpleContentVariant2(RootModel):
    """Multi-part text content."""
    root: list[SimpleContentPart]


class SimpleContent(RootModel):
    """Simple text content for system/developer messages."""
    model_config = ConfigDict(title='agent.completions.message.SimpleContent')

    root: Union[SimpleContentVariant1, SimpleContentVariant2]

