# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional
from pydantic import BaseModel, ConfigDict, Field


class SystemMessageExpression(BaseModel):
    """Expression variant of [`SystemMessage`] for dynamic content."""
    model_config = ConfigDict(title='agent.completions.message.SystemMessageExpression')

    content: WithExpression_AgentCompletionsMessageSimpleContentExpression = Field(..., description='The message content expression.')
    name: Optional[WithExpression_NullableString] = Field(None, description='Optional name expression.')


# Deferred imports to break circular dependencies
from objectiveai.functions.expression.with_expression import WithExpression_AgentCompletionsMessageSimpleContentExpression, WithExpression_NullableString  # noqa: E402
