# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional, Union
from pydantic import BaseModel, ConfigDict, Field
from objectiveai.agent.completions.message.rich_content_expression import RichContentExpression
from objectiveai.functions.expression.expression import Expression


class UserMessageExpression(BaseModel):
    """Expression variant of [`UserMessage`] for dynamic content."""
    model_config = ConfigDict(title='agent.completions.message.UserMessageExpression')

    content: Union[Expression, RichContentExpression] = Field(..., description='A value that can be either a literal or an expression.\n\nThis allows Function definitions to mix static values with dynamic\nexpressions. During compilation, expressions are evaluated while\nliteral values pass through unchanged.\n\n# Example\n\nLiteral value:\n```json\n"hello world"\n```\n\nJMESPath expression:\n```json\n{"$jmespath": "input.greeting"}\n```\n\nStarlark expression:\n```json\n{"$starlark": "input[\'greeting\']"}\n```')
    name: Optional[Union[Expression, Optional[str]]] = Field(None, description='Optional name expression.')

