# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional, Union
from pydantic import BaseModel, ConfigDict, Field, RootModel
from objectiveai.agent.completions.message.rich_content_expression import RichContentExpression
from objectiveai.functions.expression.expression import Expression


class UserMessageExpressionContentVariant1(RootModel):
    """An expression (JMESPath or Starlark) to evaluate."""
    root: Expression


class UserMessageExpressionContentVariant2(RootModel):
    """A literal value."""
    root: RichContentExpression


class UserMessageExpressionContent(RootModel):
    """A value that can be either a literal or an expression.

This allows Function definitions to mix static values with dynamic
expressions. During compilation, expressions are evaluated while
literal values pass through unchanged.

# Example

Literal value:
```json
"hello world"
```

JMESPath expression:
```json
{"$jmespath": "input.greeting"}
```

Starlark expression:
```json
{"$starlark": "input['greeting']"}
```"""
    root: Union[UserMessageExpressionContentVariant1, UserMessageExpressionContentVariant2]


class UserMessageExpressionNameVariant1(RootModel):
    """An expression (JMESPath or Starlark) to evaluate."""
    root: Expression


class UserMessageExpressionNameVariant2(RootModel):
    """A literal value."""
    root: Optional[str]


class UserMessageExpressionName(RootModel):
    """A value that can be either a literal or an expression.

This allows Function definitions to mix static values with dynamic
expressions. During compilation, expressions are evaluated while
literal values pass through unchanged.

# Example

Literal value:
```json
"hello world"
```

JMESPath expression:
```json
{"$jmespath": "input.greeting"}
```

Starlark expression:
```json
{"$starlark": "input['greeting']"}
```"""
    root: Union[UserMessageExpressionNameVariant1, UserMessageExpressionNameVariant2]


class UserMessageExpression(BaseModel):
    """Expression variant of [`UserMessage`] for dynamic content."""
    model_config = ConfigDict(title='agent.completions.message.UserMessageExpression')

    content: UserMessageExpressionContent = Field(..., description='A value that can be either a literal or an expression.\n\nThis allows Function definitions to mix static values with dynamic\nexpressions. During compilation, expressions are evaluated while\nliteral values pass through unchanged.\n\n# Example\n\nLiteral value:\n```json\n"hello world"\n```\n\nJMESPath expression:\n```json\n{"$jmespath": "input.greeting"}\n```\n\nStarlark expression:\n```json\n{"$starlark": "input[\'greeting\']"}\n```')
    name: Optional[UserMessageExpressionName] = Field(None, description='Optional name expression.')

