# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Union
from pydantic import ConfigDict, RootModel
from objectiveai.functions.task import FunctionsTask


class FunctionsCompiledTaskVariant1(RootModel):
    """A single task (no mapping)."""
    root: FunctionsTask


class FunctionsCompiledTaskVariant2(RootModel):
    """Multiple task instances from mapped execution."""
    root: list[FunctionsTask]


class FunctionsCompiledTask(RootModel):
    """The result of compiling a task expression.

Tasks without a `map` field compile to a single task. Tasks with a `map`
expression are expanded into multiple tasks, one per integer index from
0 to the evaluated count."""
    model_config = ConfigDict(title='functions.CompiledTask')

    root: Union[FunctionsCompiledTaskVariant1, FunctionsCompiledTaskVariant2]

