# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Union
from pydantic import ConfigDict, RootModel
from objectiveai.functions.inline_profile import InlineProfile
from objectiveai.remote_path_commit_optional import RemotePathCommitOptional


class InlineProfileOrRemoteCommitOptionalVariant1(RootModel):
    root: InlineProfile


class InlineProfileOrRemoteCommitOptionalVariant2(RootModel):
    root: RemotePathCommitOptional


class InlineProfileOrRemoteCommitOptional(RootModel):
    """A profile specification that is either an inline profile definition
or a remote path reference."""
    model_config = ConfigDict(title='functions.InlineProfileOrRemoteCommitOptional')

    root: Union[InlineProfileOrRemoteCommitOptionalVariant1, InlineProfileOrRemoteCommitOptionalVariant2]

