# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import TYPE_CHECKING, Union
from pydantic import RootModel
from objectiveai.functions.inline_auto_profile import FunctionsInlineAutoProfile

if TYPE_CHECKING:
    from objectiveai.functions.inline_tasks_profile import FunctionsInlineTasksProfile


class FunctionsInlineProfile(RootModel):
    """An inline profile, either tasks-based or auto."""
    root: Union[FunctionsInlineTasksProfile, FunctionsInlineAutoProfile]

