# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Union
from pydantic import ConfigDict, RootModel
from objectiveai.swarm.inline_swarm_base import InlineSwarmBase


class InlineProfileVariant1(RootModel):
    """Tasks-based profile with per-task configuration."""
    root: InlineTasksProfile


class InlineProfileVariant2(RootModel):
    """Auto profile that applies a single swarm+weights to all vector completion tasks."""
    root: InlineSwarmBase


class InlineProfile(RootModel):
    """An inline profile, either tasks-based or auto."""
    model_config = ConfigDict(title='functions.InlineProfile')

    root: Union[InlineProfileVariant1, InlineProfileVariant2]


# Deferred imports to break circular dependencies
from objectiveai.functions.inline_tasks_profile import InlineTasksProfile  # noqa: E402
