# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field
from objectiveai.functions.remote import FunctionsRemote


class FunctionsListFunctionItem(BaseModel):
    """A function in a list response."""
    model_config = ConfigDict(title='functions.ListFunctionItem')

    commit: str = Field(..., description='Git commit SHA.')
    owner: str = Field(..., description='Repository owner.')
    remote: FunctionsRemote = Field(..., description='The remote source where the function is hosted.')
    repository: str = Field(..., description='Repository name.')

