# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional
from pydantic import BaseModel
from objectiveai.functions.list_function_profile_pairs_source import FunctionsListFunctionProfilePairsSource


class FunctionsListFunctionProfilePairsQueryParameters(BaseModel):
    """Query parameters for the list function-profile pairs endpoint."""
    source: Optional[FunctionsListFunctionProfilePairsSource] = None

