# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field
from objectiveai.functions.expression.expression import FunctionsExpressionExpression
from objectiveai.functions.expression.input_schema import FunctionsExpressionInputSchema
from objectiveai.functions.expression.input_value import FunctionsExpressionInputValue


class FunctionsPlaceholderVectorFunctionTask(BaseModel):
    """A compiled placeholder vector function task.

Always produces `Vector(vec![1/N; output_length])` before
the output expression is applied."""
    model_config = ConfigDict(title='functions.PlaceholderVectorFunctionTask')

    input: FunctionsExpressionInputValue = Field(..., description='The resolved input.')
    input_merge: FunctionsExpressionExpression = Field(..., description='Expression merging sub-inputs back into one input.')
    input_schema: FunctionsExpressionInputSchema = Field(..., description='JSON Schema defining the expected input structure.')
    input_split: FunctionsExpressionExpression = Field(..., description='Expression transforming input into sub-inputs for swiss system.')
    output: FunctionsExpressionExpression = Field(..., description='Expression to transform the equalized vector output.')
    output_length: FunctionsExpressionExpression = Field(..., description='Expression computing the expected output vector length.')

