# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from pydantic import BaseModel, ConfigDict
from objectiveai.functions.remote import FunctionsRemote


class FunctionsRemoteFunctionPath(BaseModel):
    model_config = ConfigDict(title='functions.RemoteFunctionPath')

    commit: str
    owner: str
    remote: FunctionsRemote
    repository: str

