# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Union
from objectiveai.functions.remote_auto_profile import FunctionsRemoteAutoProfile
from objectiveai.functions.remote_tasks_profile import FunctionsRemoteTasksProfile


FunctionsRemoteProfile = Union[FunctionsRemoteTasksProfile, FunctionsRemoteAutoProfile]
"""A remote profile, either tasks-based or auto."""

