# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Optional, Union
from pydantic import BaseModel, ConfigDict, Field, RootModel
from objectiveai.functions.expression.expression import Expression
from objectiveai.functions.expression.input_value_expression import InputValueExpression
from objectiveai.remote import Remote


class ScalarFunctionTaskExpressionInputVariant1(RootModel):
    """An expression (JMESPath or Starlark) to evaluate."""
    root: Expression


class ScalarFunctionTaskExpressionInputVariant2(RootModel):
    """A literal value."""
    root: InputValueExpression


class ScalarFunctionTaskExpressionInput(RootModel):
    """Expression for the input to pass to the function.
Receives: `input`, `map` (if mapped).

A value that can be either a literal or an expression.

This allows Function definitions to mix static values with dynamic
expressions. During compilation, expressions are evaluated while
literal values pass through unchanged.

# Example

Literal value:
```json
"hello world"
```

JMESPath expression:
```json
{"$jmespath": "input.greeting"}
```

Starlark expression:
```json
{"$starlark": "input['greeting']"}
```"""
    root: Union[ScalarFunctionTaskExpressionInputVariant1, ScalarFunctionTaskExpressionInputVariant2]


class ScalarFunctionTaskExpression(BaseModel):
    """Expression for a task that calls a scalar function (pre-compilation)."""
    model_config = ConfigDict(title='functions.ScalarFunctionTaskExpression')

    commit: str = Field(..., description='Git commit SHA for the function version.')
    input: ScalarFunctionTaskExpressionInput = Field(..., description='Expression for the input to pass to the function.\nReceives: `input`, `map` (if mapped).\n\nA value that can be either a literal or an expression.\n\nThis allows Function definitions to mix static values with dynamic\nexpressions. During compilation, expressions are evaluated while\nliteral values pass through unchanged.\n\n# Example\n\nLiteral value:\n```json\n"hello world"\n```\n\nJMESPath expression:\n```json\n{"$jmespath": "input.greeting"}\n```\n\nStarlark expression:\n```json\n{"$starlark": "input[\'greeting\']"}\n```')
    map: Optional[Expression] = Field(None, description='Expression that evaluates to the number of mapped task instances.\nEach instance receives `map` as an integer index (0-based).')
    output: Expression = Field(..., description="Expression to transform the task result into a valid function output.\n\nReceives `output` which is one of 4 variants:\n- `Scalar(Decimal)` - a single score\n- `Vector(Vec<Decimal>)` - a vector of scores\n- `Vectors(Vec<Vec<Decimal>>)` - multiple vectors (from mapped tasks)\n- `Err(Value)` - an error\n\nThe expression must return a `TaskOutputOwned` that is valid for the parent function's type:\n- For scalar functions: must return `Scalar(value)` where value is in [0, 1]\n- For vector functions: must return `Vector(values)` where values sum to ~1 and match the expected length\n\nThe function's final output is computed as a weighted average of all task outputs using\nprofile weights. If a function has only one task, that task's output becomes the function's\noutput directly.")
    owner: str = Field(..., description='Repository owner.')
    remote: Remote = Field(..., description='The remote source where the function is hosted.')
    repository: str = Field(..., description='Repository name.')
    skip: Optional[Expression] = Field(None, description='If this expression evaluates to true, skip the task. Receives: `input`.')

