# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from typing import Literal, Optional, Union
from pydantic import BaseModel, ConfigDict, Field, RootModel
from objectiveai.functions.expression.expression import Expression
from objectiveai.functions.expression.input_value_expression import InputValueExpression
from objectiveai.functions.placeholder_scalar_function_task_expression import PlaceholderScalarFunctionTaskExpression
from objectiveai.functions.placeholder_vector_function_task_expression import PlaceholderVectorFunctionTaskExpression
from objectiveai.functions.scalar_function_task_expression import ScalarFunctionTaskExpression
from objectiveai.functions.vector_completion_task_expression import VectorCompletionTaskExpression
from objectiveai.functions.vector_function_task_expression import VectorFunctionTaskExpression


class TaskExpressionVariant1Variant1InputVariant1(RootModel):
    """An expression (JMESPath or Starlark) to evaluate."""
    root: Expression


class TaskExpressionVariant1Variant1InputVariant2(RootModel):
    """A literal value."""
    root: InputValueExpression


class TaskExpressionVariant1Variant1Input(RootModel):
    """Expression for the input to pass to the function.
Receives: `input`, `map` (if mapped).

A value that can be either a literal or an expression.

This allows Function definitions to mix static values with dynamic
expressions. During compilation, expressions are evaluated while
literal values pass through unchanged.

# Example

Literal value:
```json
"hello world"
```

JMESPath expression:
```json
{"$jmespath": "input.greeting"}
```

Starlark expression:
```json
{"$starlark": "input['greeting']"}
```"""
    root: Union[TaskExpressionVariant1Variant1InputVariant1, TaskExpressionVariant1Variant1InputVariant2]


class TaskExpressionVariant1Variant2InputVariant1(RootModel):
    """An expression (JMESPath or Starlark) to evaluate."""
    root: Expression


class TaskExpressionVariant1Variant2InputVariant2(RootModel):
    """A literal value."""
    root: InputValueExpression


class TaskExpressionVariant1Variant2Input(RootModel):
    """Expression for the input to pass to the function.
Receives: `input`, `map` (if mapped).

A value that can be either a literal or an expression.

This allows Function definitions to mix static values with dynamic
expressions. During compilation, expressions are evaluated while
literal values pass through unchanged.

# Example

Literal value:
```json
"hello world"
```

JMESPath expression:
```json
{"$jmespath": "input.greeting"}
```

Starlark expression:
```json
{"$starlark": "input['greeting']"}
```"""
    root: Union[TaskExpressionVariant1Variant2InputVariant1, TaskExpressionVariant1Variant2InputVariant2]


class TaskExpressionVariant1Variant3InputVariant1(RootModel):
    """An expression (JMESPath or Starlark) to evaluate."""
    root: Expression


class TaskExpressionVariant1Variant3InputVariant2(RootModel):
    """A literal value."""
    root: InputValueExpression


class TaskExpressionVariant1Variant3Input(RootModel):
    """Expression for the input to pass to the function.
Receives: `input`, `map` (if mapped).

A value that can be either a literal or an expression.

This allows Function definitions to mix static values with dynamic
expressions. During compilation, expressions are evaluated while
literal values pass through unchanged.

# Example

Literal value:
```json
"hello world"
```

JMESPath expression:
```json
{"$jmespath": "input.greeting"}
```

Starlark expression:
```json
{"$starlark": "input['greeting']"}
```"""
    root: Union[TaskExpressionVariant1Variant3InputVariant1, TaskExpressionVariant1Variant3InputVariant2]


class TaskExpressionVariant2Variant1InputVariant1(RootModel):
    """An expression (JMESPath or Starlark) to evaluate."""
    root: Expression


class TaskExpressionVariant2Variant1InputVariant2(RootModel):
    """A literal value."""
    root: InputValueExpression


class TaskExpressionVariant2Variant1Input(RootModel):
    """Expression for the input to pass to the function.
Receives: `input`, `map` (if mapped).

A value that can be either a literal or an expression.

This allows Function definitions to mix static values with dynamic
expressions. During compilation, expressions are evaluated while
literal values pass through unchanged.

# Example

Literal value:
```json
"hello world"
```

JMESPath expression:
```json
{"$jmespath": "input.greeting"}
```

Starlark expression:
```json
{"$starlark": "input['greeting']"}
```"""
    root: Union[TaskExpressionVariant2Variant1InputVariant1, TaskExpressionVariant2Variant1InputVariant2]


class TaskExpressionVariant2Variant2InputVariant1(RootModel):
    """An expression (JMESPath or Starlark) to evaluate."""
    root: Expression


class TaskExpressionVariant2Variant2InputVariant2(RootModel):
    """A literal value."""
    root: InputValueExpression


class TaskExpressionVariant2Variant2Input(RootModel):
    """Expression for the input to pass to the function.
Receives: `input`, `map` (if mapped).

A value that can be either a literal or an expression.

This allows Function definitions to mix static values with dynamic
expressions. During compilation, expressions are evaluated while
literal values pass through unchanged.

# Example

Literal value:
```json
"hello world"
```

JMESPath expression:
```json
{"$jmespath": "input.greeting"}
```

Starlark expression:
```json
{"$starlark": "input['greeting']"}
```"""
    root: Union[TaskExpressionVariant2Variant2InputVariant1, TaskExpressionVariant2Variant2InputVariant2]


class TaskExpressionVariant2Variant3InputVariant1(RootModel):
    """An expression (JMESPath or Starlark) to evaluate."""
    root: Expression


class TaskExpressionVariant2Variant3InputVariant2(RootModel):
    """A literal value."""
    root: InputValueExpression


class TaskExpressionVariant2Variant3Input(RootModel):
    """Expression for the input to pass to the function.
Receives: `input`, `map` (if mapped).

A value that can be either a literal or an expression.

This allows Function definitions to mix static values with dynamic
expressions. During compilation, expressions are evaluated while
literal values pass through unchanged.

# Example

Literal value:
```json
"hello world"
```

JMESPath expression:
```json
{"$jmespath": "input.greeting"}
```

Starlark expression:
```json
{"$starlark": "input['greeting']"}
```"""
    root: Union[TaskExpressionVariant2Variant3InputVariant1, TaskExpressionVariant2Variant3InputVariant2]


class TaskExpressionVariant1Variant1(BaseModel):
    commit: str
    owner: str
    remote: Literal['github']
    repository: str
    input: TaskExpressionVariant1Variant1Input = Field(..., description='Expression for the input to pass to the function.\nReceives: `input`, `map` (if mapped).\n\nA value that can be either a literal or an expression.\n\nThis allows Function definitions to mix static values with dynamic\nexpressions. During compilation, expressions are evaluated while\nliteral values pass through unchanged.\n\n# Example\n\nLiteral value:\n```json\n"hello world"\n```\n\nJMESPath expression:\n```json\n{"$jmespath": "input.greeting"}\n```\n\nStarlark expression:\n```json\n{"$starlark": "input[\'greeting\']"}\n```')
    map: Optional[Expression] = Field(None, description='Expression that evaluates to the number of mapped task instances.\nEach instance receives `map` as an integer index (0-based).')
    output: Expression = Field(..., description="Expression to transform the task result into a valid function output.\n\nReceives `output` which is one of 4 variants:\n- `Scalar(Decimal)` - a single score\n- `Vector(Vec<Decimal>)` - a vector of scores\n- `Vectors(Vec<Vec<Decimal>>)` - multiple vectors (from mapped tasks)\n- `Err(Value)` - an error\n\nThe expression must return a `TaskOutputOwned` that is valid for the parent function's type:\n- For scalar functions: must return `Scalar(value)` where value is in [0, 1]\n- For vector functions: must return `Vector(values)` where values sum to ~1 and match the expected length\n\nThe function's final output is computed as a weighted average of all task outputs using\nprofile weights. If a function has only one task, that task's output becomes the function's\noutput directly.")
    skip: Optional[Expression] = Field(None, description='If this expression evaluates to true, skip the task. Receives: `input`.')
    type_: Literal['scalar.function'] = Field(..., alias='type')


class TaskExpressionVariant1Variant2(BaseModel):
    commit: str
    owner: str
    remote: Literal['filesystem']
    repository: str
    input: TaskExpressionVariant1Variant2Input = Field(..., description='Expression for the input to pass to the function.\nReceives: `input`, `map` (if mapped).\n\nA value that can be either a literal or an expression.\n\nThis allows Function definitions to mix static values with dynamic\nexpressions. During compilation, expressions are evaluated while\nliteral values pass through unchanged.\n\n# Example\n\nLiteral value:\n```json\n"hello world"\n```\n\nJMESPath expression:\n```json\n{"$jmespath": "input.greeting"}\n```\n\nStarlark expression:\n```json\n{"$starlark": "input[\'greeting\']"}\n```')
    map: Optional[Expression] = Field(None, description='Expression that evaluates to the number of mapped task instances.\nEach instance receives `map` as an integer index (0-based).')
    output: Expression = Field(..., description="Expression to transform the task result into a valid function output.\n\nReceives `output` which is one of 4 variants:\n- `Scalar(Decimal)` - a single score\n- `Vector(Vec<Decimal>)` - a vector of scores\n- `Vectors(Vec<Vec<Decimal>>)` - multiple vectors (from mapped tasks)\n- `Err(Value)` - an error\n\nThe expression must return a `TaskOutputOwned` that is valid for the parent function's type:\n- For scalar functions: must return `Scalar(value)` where value is in [0, 1]\n- For vector functions: must return `Vector(values)` where values sum to ~1 and match the expected length\n\nThe function's final output is computed as a weighted average of all task outputs using\nprofile weights. If a function has only one task, that task's output becomes the function's\noutput directly.")
    skip: Optional[Expression] = Field(None, description='If this expression evaluates to true, skip the task. Receives: `input`.')
    type_: Literal['scalar.function'] = Field(..., alias='type')


class TaskExpressionVariant1Variant3(BaseModel):
    name: str
    remote: Literal['mock']
    input: TaskExpressionVariant1Variant3Input = Field(..., description='Expression for the input to pass to the function.\nReceives: `input`, `map` (if mapped).\n\nA value that can be either a literal or an expression.\n\nThis allows Function definitions to mix static values with dynamic\nexpressions. During compilation, expressions are evaluated while\nliteral values pass through unchanged.\n\n# Example\n\nLiteral value:\n```json\n"hello world"\n```\n\nJMESPath expression:\n```json\n{"$jmespath": "input.greeting"}\n```\n\nStarlark expression:\n```json\n{"$starlark": "input[\'greeting\']"}\n```')
    map: Optional[Expression] = Field(None, description='Expression that evaluates to the number of mapped task instances.\nEach instance receives `map` as an integer index (0-based).')
    output: Expression = Field(..., description="Expression to transform the task result into a valid function output.\n\nReceives `output` which is one of 4 variants:\n- `Scalar(Decimal)` - a single score\n- `Vector(Vec<Decimal>)` - a vector of scores\n- `Vectors(Vec<Vec<Decimal>>)` - multiple vectors (from mapped tasks)\n- `Err(Value)` - an error\n\nThe expression must return a `TaskOutputOwned` that is valid for the parent function's type:\n- For scalar functions: must return `Scalar(value)` where value is in [0, 1]\n- For vector functions: must return `Vector(values)` where values sum to ~1 and match the expected length\n\nThe function's final output is computed as a weighted average of all task outputs using\nprofile weights. If a function has only one task, that task's output becomes the function's\noutput directly.")
    skip: Optional[Expression] = Field(None, description='If this expression evaluates to true, skip the task. Receives: `input`.')
    type_: Literal['scalar.function'] = Field(..., alias='type')


class TaskExpressionVariant1(RootModel):
    model_config = ConfigDict(json_schema_extra={'_expanded_ref': 'functions.ScalarFunctionTaskExpression', '_expanded_ref_props': ['type']})

    root: Union[TaskExpressionVariant1Variant1, TaskExpressionVariant1Variant2, TaskExpressionVariant1Variant3]


class TaskExpressionVariant2Variant1(BaseModel):
    commit: str
    owner: str
    remote: Literal['github']
    repository: str
    input: TaskExpressionVariant2Variant1Input = Field(..., description='Expression for the input to pass to the function.\nReceives: `input`, `map` (if mapped).\n\nA value that can be either a literal or an expression.\n\nThis allows Function definitions to mix static values with dynamic\nexpressions. During compilation, expressions are evaluated while\nliteral values pass through unchanged.\n\n# Example\n\nLiteral value:\n```json\n"hello world"\n```\n\nJMESPath expression:\n```json\n{"$jmespath": "input.greeting"}\n```\n\nStarlark expression:\n```json\n{"$starlark": "input[\'greeting\']"}\n```')
    map: Optional[Expression] = Field(None, description='Expression that evaluates to the number of mapped task instances.\nEach instance receives `map` as an integer index (0-based).')
    output: Expression = Field(..., description="Expression to transform the task result into a valid function output.\n\nReceives `output` which is one of 4 variants:\n- `Scalar(Decimal)` - a single score\n- `Vector(Vec<Decimal>)` - a vector of scores\n- `Vectors(Vec<Vec<Decimal>>)` - multiple vectors (from mapped tasks)\n- `Err(Value)` - an error\n\nThe expression must return a `TaskOutputOwned` that is valid for the parent function's type:\n- For scalar functions: must return `Scalar(value)` where value is in [0, 1]\n- For vector functions: must return `Vector(values)` where values sum to ~1 and match the expected length\n\nThe function's final output is computed as a weighted average of all task outputs using\nprofile weights. If a function has only one task, that task's output becomes the function's\noutput directly.")
    skip: Optional[Expression] = Field(None, description='If this expression evaluates to true, skip the task. Receives: `input`.')
    type_: Literal['vector.function'] = Field(..., alias='type')


class TaskExpressionVariant2Variant2(BaseModel):
    commit: str
    owner: str
    remote: Literal['filesystem']
    repository: str
    input: TaskExpressionVariant2Variant2Input = Field(..., description='Expression for the input to pass to the function.\nReceives: `input`, `map` (if mapped).\n\nA value that can be either a literal or an expression.\n\nThis allows Function definitions to mix static values with dynamic\nexpressions. During compilation, expressions are evaluated while\nliteral values pass through unchanged.\n\n# Example\n\nLiteral value:\n```json\n"hello world"\n```\n\nJMESPath expression:\n```json\n{"$jmespath": "input.greeting"}\n```\n\nStarlark expression:\n```json\n{"$starlark": "input[\'greeting\']"}\n```')
    map: Optional[Expression] = Field(None, description='Expression that evaluates to the number of mapped task instances.\nEach instance receives `map` as an integer index (0-based).')
    output: Expression = Field(..., description="Expression to transform the task result into a valid function output.\n\nReceives `output` which is one of 4 variants:\n- `Scalar(Decimal)` - a single score\n- `Vector(Vec<Decimal>)` - a vector of scores\n- `Vectors(Vec<Vec<Decimal>>)` - multiple vectors (from mapped tasks)\n- `Err(Value)` - an error\n\nThe expression must return a `TaskOutputOwned` that is valid for the parent function's type:\n- For scalar functions: must return `Scalar(value)` where value is in [0, 1]\n- For vector functions: must return `Vector(values)` where values sum to ~1 and match the expected length\n\nThe function's final output is computed as a weighted average of all task outputs using\nprofile weights. If a function has only one task, that task's output becomes the function's\noutput directly.")
    skip: Optional[Expression] = Field(None, description='If this expression evaluates to true, skip the task. Receives: `input`.')
    type_: Literal['vector.function'] = Field(..., alias='type')


class TaskExpressionVariant2Variant3(BaseModel):
    name: str
    remote: Literal['mock']
    input: TaskExpressionVariant2Variant3Input = Field(..., description='Expression for the input to pass to the function.\nReceives: `input`, `map` (if mapped).\n\nA value that can be either a literal or an expression.\n\nThis allows Function definitions to mix static values with dynamic\nexpressions. During compilation, expressions are evaluated while\nliteral values pass through unchanged.\n\n# Example\n\nLiteral value:\n```json\n"hello world"\n```\n\nJMESPath expression:\n```json\n{"$jmespath": "input.greeting"}\n```\n\nStarlark expression:\n```json\n{"$starlark": "input[\'greeting\']"}\n```')
    map: Optional[Expression] = Field(None, description='Expression that evaluates to the number of mapped task instances.\nEach instance receives `map` as an integer index (0-based).')
    output: Expression = Field(..., description="Expression to transform the task result into a valid function output.\n\nReceives `output` which is one of 4 variants:\n- `Scalar(Decimal)` - a single score\n- `Vector(Vec<Decimal>)` - a vector of scores\n- `Vectors(Vec<Vec<Decimal>>)` - multiple vectors (from mapped tasks)\n- `Err(Value)` - an error\n\nThe expression must return a `TaskOutputOwned` that is valid for the parent function's type:\n- For scalar functions: must return `Scalar(value)` where value is in [0, 1]\n- For vector functions: must return `Vector(values)` where values sum to ~1 and match the expected length\n\nThe function's final output is computed as a weighted average of all task outputs using\nprofile weights. If a function has only one task, that task's output becomes the function's\noutput directly.")
    skip: Optional[Expression] = Field(None, description='If this expression evaluates to true, skip the task. Receives: `input`.')
    type_: Literal['vector.function'] = Field(..., alias='type')


class TaskExpressionVariant2(RootModel):
    model_config = ConfigDict(json_schema_extra={'_expanded_ref': 'functions.VectorFunctionTaskExpression', '_expanded_ref_props': ['type']})

    root: Union[TaskExpressionVariant2Variant1, TaskExpressionVariant2Variant2, TaskExpressionVariant2Variant3]


class TaskExpressionVariant3(VectorCompletionTaskExpression):
    type_: Literal['vector.completion'] = Field(..., alias='type')


class TaskExpressionVariant4(PlaceholderScalarFunctionTaskExpression):
    type_: Literal['placeholder.scalar.function'] = Field(..., alias='type')


class TaskExpressionVariant5(PlaceholderVectorFunctionTaskExpression):
    type_: Literal['placeholder.vector.function'] = Field(..., alias='type')


class TaskExpression(RootModel):
    """A task definition with expressions (pre-compilation).

Task expressions contain dynamic fields (JMESPath or Starlark) that are
resolved against input data during compilation. Use [`compile`](Self::compile)
to produce a concrete [`Task`]."""
    model_config = ConfigDict(title='functions.TaskExpression')

    root: Union[TaskExpressionVariant1, TaskExpressionVariant2, TaskExpressionVariant3, TaskExpressionVariant4, TaskExpressionVariant5]

