# THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
# Generated by scripts/install_pydantic.py from objectiveai-json-schema/.
from __future__ import annotations
from pydantic import BaseModel, ConfigDict, Field
from objectiveai.functions.expression.expression import FunctionsExpressionExpression
from objectiveai.functions.expression.input_value import FunctionsExpressionInputValue
from objectiveai.functions.remote import FunctionsRemote


class FunctionsVectorFunctionTask(BaseModel):
    """A compiled vector function task ready for execution."""
    model_config = ConfigDict(title='functions.VectorFunctionTask')

    commit: str = Field(..., description='Git commit SHA for the function version.')
    input: FunctionsExpressionInputValue = Field(..., description='The resolved input to pass to the function.')
    output: FunctionsExpressionExpression = Field(..., description="Expression to transform the task result into a valid function output.\n\nReceives `output` as the nested function's result (Scalar or Vector).\nMust return a `TaskOutputOwned` valid for the parent function's type (scalar or vector).\nSee [`VectorFunctionTaskExpression::output`] for full documentation.")
    owner: str = Field(..., description='Repository owner.')
    remote: FunctionsRemote = Field(..., description='The remote source where the function is hosted.')
    repository: str = Field(..., description='Repository name.')

